### ISSUE TITLE
Required field "querySpec" not provided (not @optional)

### ISSUE THREAD

**Issue by davidlesicnik** [pryorda/vmware_exporter#137]
Recently my vCenter + ESXi host eval licence ran out, which caused them to get disconnected from vCenter. Fixed that up, but ever since then vmware_exporter seems to fail the collection.

Going to to metrics page just returns 
`# Collection failed`

Stack trace from the logs:

`/usr/local/lib/python3.6/site-packages/yamlconfig.py:63: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for
full details.
  config = yaml.load(self.infile)
2019-08-26 19:30:57,754 INFO:Starting web server on port 9272
2019-08-26 19:31:05,475 INFO:Start collecting metrics from 10.99.0.76
2019-08-26 19:31:05,475 INFO:Starting vm metrics collection
2019-08-26 19:31:05,475 INFO:Fetching vim.VirtualMachine inventory
2019-08-26 19:31:05,477 INFO:Retrieving service instance content
2019-08-26 19:31:05,480 INFO:START: _vmware_get_vm_perf_manager_metrics
2019-08-26 19:31:05,480 INFO:Fetching vim.Datastore inventory
2019-08-26 19:31:05,482 INFO:Starting host metrics collection
2019-08-26 19:31:05,482 INFO:Fetching vim.HostSystem inventory
2019-08-26 19:31:05,587 INFO:Retrieved service instance content
2019-08-26 19:31:06,258 INFO:Fetched vim.VirtualMachine inventory (0:00:00.782616)
2019-08-26 19:31:06,270 ERROR:Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/vmware_exporter/vmware_exporter.py", line 845, in _async_render_GET
    yield self.generate_latest_metrics(request)
twisted.internet.defer.FirstError: FirstError[#1, [Failure instance: Traceback: <class 'twisted.internet.defer.FirstError'>: FirstError[#0, [Failure instance: Traceback: <class 'TypeError'>: Required field "querySpec" not provided (not @optional)
/usr/local/lib/python3.6/threading.py:916:_bootstrap_inner
/usr/local/lib/python3.6/threading.py:864:run
/usr/local/lib/python3.6/site-packages/twisted/_threads/_threadworker.py:46:work
/usr/local/lib/python3.6/site-packages/twisted/_threads/_team.py:190:doWork
--- <exception caught here> ---
/usr/local/lib/python3.6/site-packages/twisted/python/threadpool.py:250:inContext
/usr/local/lib/python3.6/site-packages/twisted/python/threadpool.py:266:<lambda>
/usr/local/lib/python3.6/site-packages/twisted/python/context.py:122:callWithContext
/usr/local/lib/python3.6/site-packages/twisted/python/context.py:85:callWithContext
/usr/local/lib/python3.6/site-packages/pyVmomi/VmomiSupport.py:706:<lambda>
/usr/local/lib/python3.6/site-packages/pyVmomi/VmomiSupport.py:511:_InvokeMethod
/usr/local/lib/python3.6/site-packages/pyVmomi/VmomiSupport.py:1041:CheckField
]]
--- <exception caught here> ---
/usr/local/lib/python3.6/site-packages/vmware_exporter/vmware_exporter.py:602:_vmware_get_vm_perf_manager_metrics
/usr/local/lib/python3.6/site-packages/vmware_exporter/defer.py:99:parallelize
]]

2019-08-26 19:31:06,290 INFO:Fetched vim.HostSystem inventory (0:00:00.807913)
2019-08-26 19:31:06,292 INFO:Fetched vim.Datastore inventory (0:00:00.810835)
2019-08-26 19:31:06,382 INFO:Finished vm metrics collection
2019-08-26 19:31:06,382 INFO:Finished host metrics collection
2019-08-26 19:31:10,476 INFO:Start collecting metrics from 10.99.0.76
2019-08-26 19:31:10,476 INFO:Starting vm metrics collection
2019-08-26 19:31:10,477 INFO:Fetching vim.VirtualMachine inventory
2019-08-26 19:31:10,477 INFO:Retrieving service instance content
2019-08-26 19:31:10,480 INFO:START: _vmware_get_vm_perf_manager_metrics
2019-08-26 19:31:10,480 INFO:Fetching vim.Datastore inventory
2019-08-26 19:31:10,481 INFO:Starting host metrics collection
2019-08-26 19:31:10,481 INFO:Fetching vim.HostSystem inventory
2019-08-26 19:31:10,603 INFO:Retrieved service instance content
2019-08-26 19:31:11,155 INFO:Fetched vim.VirtualMachine inventory (0:00:00.677780)
2019-08-26 19:31:11,165 ERROR:Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/vmware_exporter/vmware_exporter.py", line 845, in _async_render_GET
    yield self.generate_latest_metrics(request)
twisted.internet.defer.FirstError: FirstError[#1, [Failure instance: Traceback: <class 'twisted.internet.defer.FirstError'>: FirstError[#0, [Failure instance: Traceback: <class 'TypeError'>: Required field "querySpec" not provided (not @optional)
/usr/local/lib/python3.6/threading.py:916:_bootstrap_inner
/usr/local/lib/python3.6/threading.py:864:run
/usr/local/lib/python3.6/site-packages/twisted/_threads/_threadworker.py:46:work
/usr/local/lib/python3.6/site-packages/twisted/_threads/_team.py:190:doWork
--- <exception caught here> ---
/usr/local/lib/python3.6/site-packages/twisted/python/threadpool.py:250:inContext
/usr/local/lib/python3.6/site-packages/twisted/python/threadpool.py:266:<lambda>
/usr/local/lib/python3.6/site-packages/twisted/python/context.py:122:callWithContext
/usr/local/lib/python3.6/site-packages/twisted/python/context.py:85:callWithContext
/usr/local/lib/python3.6/site-packages/pyVmomi/VmomiSupport.py:706:<lambda>
/usr/local/lib/python3.6/site-packages/pyVmomi/VmomiSupport.py:511:_InvokeMethod
/usr/local/lib/python3.6/site-packages/pyVmomi/VmomiSupport.py:1041:CheckField
]]
--- <exception caught here> ---
/usr/local/lib/python3.6/site-packages/vmware_exporter/vmware_exporter.py:602:_vmware_get_vm_perf_manager_metrics
/usr/local/lib/python3.6/site-packages/vmware_exporter/defer.py:99:parallelize
]]`

And then it just repeats for everytime a new request is sent in.

I've tried many things, I even made a read-only user in case the default admin user has issues (and because it's safer practice), but it still throws out the same error.

**Comment by pryorda** [comment]
I need to know the versiosn and if you've followed the permission portion of the read me. I feel like something is missing in your connection configuration.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by davidlesicnik** [comment]
The vCenter is version 6.7.0, hosts are 6.5.0.

The yml config file:
`default:
    vsphere_host: "10.99.0.76"
    vsphere_user: "[user]"
    vsphere_password: "[pass]"
    ignore_ssl: True
    collect_only:
        vms: True
        vmguests: True
        datastores: True
        hosts: True
        snapshots: True`

Like I said everything was working perfectly until the eval license ran out and I applied an actual licence. Nothing else was changed.

**Comment by davidlesicnik** [comment]
So I seem to have fixed it.... Turns out that sometimes the simplest solutions are the ones that are most overlooked.
I restarted the vCenter Appliance and now vmware_exporter picks it up. I haven't modified anything else.

Seems like it has an issue with the license running out and then getting renewed and not being restarted.
