### ISSUE TITLE
Crash after collecting metrics

### ISSUE THREAD

**Issue by DirkFries** [pryorda/vmware_exporter#139]
Hi @all,

I justed started testing this nice software and I am experiencing some problems.
After Prometheus connects to vmware_exporter it starts to collect metrics pretty nice and fast, but after the metrics are connected I get a Python Exception:

2019-09-20 09:04:07,970 DEBUG:[HostSystem] ----    esx54
2019-09-20 09:04:08,206 DEBUG:[HostSystem] ----    esx50
2019-09-20 09:04:08,437 DEBUG:[ComputeRes] ---     cluster-exch
2019-09-20 09:04:08,444 DEBUG:[HostSystem] ----    esx24b
2019-09-20 09:04:08,544 DEBUG:[HostSystem] ----    esx25b
2019-09-20 09:04:08,674 INFO:Finished vm metrics collection
2019-09-20 09:04:08,711 INFO:FIN: _vmware_get_vm_perf_manager_metrics
2019-09-20 09:04:08,713 INFO:Finished host metrics collection
2019-09-20 09:04:08,722 INFO:Finished collecting metrics from vcenter
2019-09-20 09:04:08,959 ERROR:Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
StopIteration: [<prometheus_client.core.GaugeMetricFamily object at 0x7f6b5504be10>, <prometheus_client.core.GaugeMetricFamily object at 0x7f6b5504b950>, <pr                                ometheus_client.core.GaugeMetricFamily object at 0x7f6b5504bb50>, <prometheus_client.core.GaugeMetricFamily object at 0x7f6b5504b390>, <prometheus_client.cor                                e.GaugeMetricFamily object at 0x7f6b55c50c90>, <prometheus_client.core.GaugeMetricFamily object at 0x7f6b554f9150>, <prometheus_client.core.GaugeMetricFamily                                 object at 0x7f6b554e4110>, <prometheus_client.core.GaugeMetricFamily object at 0x7f6b5c4d3610>, <prometheus_client.core.GaugeMetricFamily object at 0x7f6b5c                                4d3650>, <prometheus_client.core.GaugeMetricFamily object at 0x7f6b5c793950>, <prometheus_client.core.GaugeMetricFamily object at 0x7f6b5c7938d0>, <prometheu                                s_client.core.GaugeMetricFamily object at 0x7f6b5c793ed0>, <prometheus_client.core.GaugeMetricFamily object at 0x7f6b5c793b50>, <prometheus_client.core.Gauge                                MetricFamily object at 0x7f6b5c793050>, <prometheus_client.core.GaugeMetricFamily object at 0x7f6b5c793f10>, <prometheus_client.core.GaugeMetricFamily object                                 at 0x7f6b5c793750>, <prometheus_client.core.GaugeMetricFamily object at 0x7f6b5c793610>, <prometheus_client.core.GaugeMetricFamily object at 0x7f6b5c7939d0>                                , <prometheus_client.core.GaugeMetricFamily object at 0x7f6b5c7934d0>, <prometheus_client.core.GaugeMetricFamily object at 0x7f6b55bb2390>, <prometheus_clien                                t.core.GaugeMetricFamily object at 0x7f6b5d000910>, <prometheus_client.core.GaugeMetricFamily object at 0x7f6b5d000310>, <prometheus_client.core.GaugeMetricF                                amily object at 0x7f6b5d000490>, <prometheus_client.core.GaugeMetricFamily object at 0x7f6b5d000a50>, <prometheus_client.core.GaugeMetricFamily object at 0x7                                f6b5d000950>, <prometheus_client.core.GaugeMetricFamily object at 0x7f6b5d000190>, <prometheus_client.core.GaugeMetricFamily object at 0x7f6b5c0fe0d0>, <prom                                etheus_client.core.GaugeMetricFamily object at 0x7f6b5c0fec50>, <prometheus_client.core.GaugeMetricFamily object at 0x7f6b5c323f90>, <prometheus_client.core.                                GaugeMetricFamily object at 0x7f6b5c323510>, <prometheus_client.core.GaugeMetricFamily object at 0x7f6b5c323990>, <prometheus_client.core.GaugeMetricFamily o                                bject at 0x7f6b5c323210>, <prometheus_client.core.GaugeMetricFamily object at 0x7f6b5c323590>, <prometheus_client.core.GaugeMetricFamily object at 0x7f6b5c32                                3d90>, <prometheus_client.core.GaugeMetricFamily object at 0x7f6b5c389690>, <prometheus_client.core.GaugeMetricFamily object at 0x7f6b5c389790>, <prometheus_                                client.core.GaugeMetricFamily object at 0x7f6b5c389b10>, <prometheus_client.core.GaugeMetricFamily object at 0x7f6b5c389d50>]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/vmware_exporter/vmware_exporter.py", line 868, in _async_render_GET
    yield self.generate_latest_metrics(request)
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/usr/local/lib/python3.7/site-packages/vmware_exporter/vmware_exporter.py", line 916, in generate_latest_metrics
    request.finish()
  File "/usr/local/lib/python3.7/site-packages/twisted/web/server.py", line 268, in finish
    return http.Request.finish(self)
  File "/usr/local/lib/python3.7/site-packages/twisted/web/http.py", line 1071, in finish
    "Request.finish called on a request after its connection was lost; "
RuntimeError: Request.finish called on a request after its connection was lost; use Request.notifyFinish to keep track of this.

^CUnhandled error in Deferred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 501, in errback
    self._startRunCallbacks(fail)
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 568, in _startRunCallbacks
    self._runCallbacks()
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1475, in gotResult
    _inlineCallbacks(r, g, status)
--- <exception caught here> ---
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/local/lib/python3.7/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/local/lib/python3.7/site-packages/vmware_exporter/vmware_exporter.py", line 873, in _async_render_GET
    request.finish()
  File "/usr/local/lib/python3.7/site-packages/twisted/web/server.py", line 268, in finish
    return http.Request.finish(self)
  File "/usr/local/lib/python3.7/site-packages/twisted/web/http.py", line 1071, in finish
    "Request.finish called on a request after its connection was lost; "
builtins.RuntimeError: Request.finish called on a request after its connection was lost; use Request.notifyFinish to keep track of this.

If I try this with a different, much smaller Vsphere Cluster all works fine.

Can anyone give me a hint how I can fix this ?

**Comment by Jc2k** [comment]
That error means Prometheus timed out while waiting for the metrics. The exporter carried on working but when it was done there was no one there to admire its hard work :( :( you can increase the timeout on the Prometheus side and it should work. But the VMware api can be very slow

**Comment by DirkFries** [comment]
Wow ! That was fast :-)
Just tried your hint and it did the job perfectly :-)

Thanks a lot !
