### ISSUE TITLE
Operation Timeout

### ISSUE THREAD

**Issue by arogarth** [pryorda/vmware_exporter#160]
Calling vCenter 6.7 we get a Operation timed out ....

```
[2019-11-19 10:59:04.952304+00:00] Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/vmware_exporter/vmware_exporter.py", line 710, in _async_render_GET
    yield self.generate_latest_metrics(request)
  File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/local/lib/python3.6/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/local/lib/python3.6/site-packages/vmware_exporter/vmware_exporter.py", line 756, in generate_latest_metrics
    metrics = yield collector.collect()
  File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/local/lib/python3.6/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/local/lib/python3.6/site-packages/vmware_exporter/vmware_exporter.py", line 183, in collect
    self.vmware_connection = yield threads.deferToThread(self._vmware_connect)
  File "/usr/local/lib/python3.6/site-packages/twisted/python/threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "/usr/local/lib/python3.6/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/usr/local/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/local/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "/usr/local/lib/python3.6/site-packages/vmware_exporter/vmware_exporter.py", line 251, in _vmware_connect
    sslContext=context,
  File "/usr/local/lib/python3.6/site-packages/pyVim/connect.py", line 847, in SmartConnect
    sslContext)
  File "/usr/local/lib/python3.6/site-packages/pyVim/connect.py", line 726, in __FindSupportedVersion
    httpProxyPort)
  File "/usr/local/lib/python3.6/site-packages/pyVim/connect.py", line 643, in __GetServiceVersionDescription
    httpProxyHost, httpProxyPort)
  File "/usr/local/lib/python3.6/site-packages/pyVim/connect.py", line 608, in __GetElementTree
    conn.request("GET", path)
  File "/usr/local/lib/python3.6/http/client.py", line 1254, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.6/http/client.py", line 1300, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.6/http/client.py", line 1249, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.6/http/client.py", line 1036, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.6/http/client.py", line 974, in send
    self.connect()
  File "/usr/local/lib/python3.6/http/client.py", line 1407, in connect
    super().connect()
  File "/usr/local/lib/python3.6/http/client.py", line 946, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/local/lib/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/usr/local/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Operation timed out
```

**Comment by Jc2k** [comment]
That looks like a fairly low level error rather than something that vmware_exporter is doing to the API, e.g. a timeout on connection creation like this would most likely be - a bug in python 3.6, a typo in your configuration, a networking issue (routing? firewall?). Or maybe something is overloading the API port? (If polling was too frequent and the cluster was massive then you could end up with a backlog and then timeouts, maybe).

You mention vCenter 6.7 - is this the first time connecting to vCenter 6.7? Is it a cluster that used to work and was upgraded? Or is it a new setup?

**Comment by arogarth** [comment]
Hi, the exporter worked for some weeks on vCenter 6.7 - its not the first time...
In my exporter setup I have 4 vCenter in config.

Let me try to split them in separate exporter.

**Comment by arogarth** [comment]
Hmm. Same problem... 

I Tried the following:
* One vCenter per exporter
* Increase Scrape timeout and Intervall to 300s
* Build fresh, new exporter container

But all will be results in Timeout error.

**Comment by Jc2k** [comment]
And it works if you curl the API endpoint from the container?

**Comment by Jc2k** [comment]
And did anything change before the error started happening?

**Comment by pryorda** [comment]
Closing for inactivity
