### ISSUE TITLE
A general system error occurred: Operation was canceled

### ISSUE THREAD

**Issue by finkr** [pryorda/vmware_exporter#166]
I sometime get this error in the log file (the metrics collection fails).

I use vmware_exporter-0.11.0.dist-info
and pyvmomi-6.7.1.2018.12-py3.7.egg-info

    2019-12-03 10:21:11,670 INFO:FIN: _vmware_get_host_perf_manager_metrics
    2019-12-03 10:21:24,279 ERROR:Traceback (most recent call last):
      File "d:\python\python37-32\lib\site-packages\vmware_exporter\vmware_exporter.py", line 997, in _async_render_GET
        yield self.generate_latest_metrics(request)
    twisted.internet.defer.FirstError: FirstError[#1, [Failure instance: Traceback: <class 'twisted.internet.defer.FirstError'>: FirstError[#0, [Failure instance: Traceback: <class 'pyVmomi.VmomiSupport.vmodl.fault.SystemError'>: (vmodl.fault.SystemError) {
       dynamicType = <unset>,
       dynamicProperty = (vmodl.DynamicProperty) [],
       msg = 'A general system error occurred: Operation was canceled',
       faultCause = <unset>,
       faultMessage = (vmodl.LocalizableMessage) [],
       reason = 'Operation was canceled'
    }
    d:\python\python37-32\lib\threading.py:917:_bootstrap_inner
    d:\python\python37-32\lib\threading.py:865:run
    d:\python\python37-32\lib\site-packages\twisted\_threads\_threadworker.py:46:work
    d:\python\python37-32\lib\site-packages\twisted\_threads\_team.py:190:doWork
    --- <exception caught here> ---
    d:\python\python37-32\lib\site-packages\twisted\python\threadpool.py:250:inContext
    d:\python\python37-32\lib\site-packages\twisted\python\threadpool.py:266:<lambda>
    d:\python\python37-32\lib\site-packages\twisted\python\context.py:122:callWithContext
    d:\python\python37-32\lib\site-packages\twisted\python\context.py:85:callWithContext
    d:\python\python37-32\lib\site-packages\pyVmomi\VmomiSupport.py:706:<lambda>
    d:\python\python37-32\lib\site-packages\pyVmomi\VmomiSupport.py:512:_InvokeMethod
    d:\python\python37-32\lib\site-packages\pyVmomi\SoapAdapter.py:1374:InvokeMethod
    ]]
    --- <exception caught here> ---
    d:\python\python37-32\lib\site-packages\vmware_exporter\vmware_exporter.py:644:_vmware_get_vm_perf_manager_metrics
    d:\python\python37-32\lib\site-packages\vmware_exporter\defer.py:99:parallelize
    ]]
    
    Unhandled Error
    Traceback (most recent call last):
      File "D:\Python\Python37-32\Scripts\vmware_exporter.exe\__main__.py", line 7, in <module>
    
      File "d:\python\python37-32\lib\site-packages\vmware_exporter\vmware_exporter.py", line 1112, in main
        reactor.run()
      File "d:\python\python37-32\lib\site-packages\twisted\internet\base.py", line 1272, in run
        self.mainLoop()
      File "d:\python\python37-32\lib\site-packages\twisted\internet\base.py", line 1281, in mainLoop
        self.runUntilCurrent()
    --- <exception caught here> ---
      File "d:\python\python37-32\lib\site-packages\twisted\internet\base.py", line 875, in runUntilCurrent
        f(*a, **kw)
      File "d:\python\python37-32\lib\site-packages\twisted\internet\defer.py", line 501, in errback
        self._startRunCallbacks(fail)
      File "d:\python\python37-32\lib\site-packages\twisted\internet\defer.py", line 568, in _startRunCallbacks
        self._runCallbacks()
      File "d:\python\python37-32\lib\site-packages\twisted\internet\defer.py", line 699, in _runCallbacks
        current.result.cleanFailure()
      File "d:\python\python37-32\lib\site-packages\twisted\python\failure.py", line 627, in cleanFailure
        self.value.__traceback__ = None
      File "d:\python\python37-32\lib\site-packages\pyVmomi\VmomiSupport.py", line 663, in __setattr__
        CheckField(self._GetPropertyInfo(name), val)
      File "d:\python\python37-32\lib\site-packages\pyVmomi\VmomiSupport.py", line 468, in GetPropertyInfo
        raise AttributeError(name)
    builtins.AttributeError: __traceback__

**Comment by pryorda** [comment]
Extend the straight duration and time out on Prometheus side.

**Comment by finkr** [comment]
The expiration is 2minutes, the usual collection time is 30s.
The operation ___seems___ to abort after 60s (no precise log)
