### ISSUE TITLE
fails with: "reason = 'No route to host'"

### ISSUE THREAD

**Issue by finkr** [pryorda/vmware_exporter#167]
I use vmware_exporter-0.11.0.dist-info
and pyvmomi-6.7.1.2018.12-py3.7.egg-info

Sometime the collection fails (up=0).

Actually, sometime the collection fails after 60s (scrape_duration_seconds), despite the scrape_interval=120s and scrape_timeout=110s.

The logs says "reason = 'No route to host'".

Actually, it seems to be due to the fact that some host are under maintenance (reboot).

**Expected result:**

The exporter should:
* handle this error gracefully, so available metrics are reported anyway.
* handle the timeout when multiple hosts are down

**vmware_exporter log**

    2019-12-03 14:32:55,703 INFO:START: _vmware_get_vm_perf_manager_metrics
    2019-12-03 14:32:55,703 INFO:Fetching vim.Datastore inventory
    2019-12-03 14:32:55,703 INFO:Starting host metrics collection
    2019-12-03 14:32:55,703 INFO:Fetching vim.HostSystem inventory
    2019-12-03 14:32:55,703 INFO:START: _vmware_get_host_perf_manager_metrics
    2019-12-03 14:32:55,753 INFO:Retrieved service instance content
    2019-12-03 14:32:56,546 INFO:Fetched vim.HostSystem inventory (0:00:00.843156)
    2019-12-03 14:33:02,954 INFO:Fetched vim.Datastore inventory (0:00:07.250704)
    2019-12-03 14:33:05,518 INFO:Fetched vim.VirtualMachine inventory (0:00:09.815055)
    2019-12-03 14:33:11,844 INFO:Finished vm metrics collection
    2019-12-03 14:33:11,860 INFO:Finished host metrics collection
    2019-12-03 14:33:23,625 INFO:FIN: _vmware_get_vm_perf_manager_metrics
    2019-12-03 14:34:02,878 ERROR:Traceback (most recent call last):
      File "d:\python\python37-32\lib\site-packages\vmware_exporter\vmware_exporter.py", line 997, in _async_render_GET
        yield self.generate_latest_metrics(request)
    twisted.internet.defer.FirstError: FirstError[#4, [Failure instance: Traceback: <class 'twisted.internet.defer.FirstErro
    r'>: FirstError[#0, [Failure instance: Traceback: <class 'pyVmomi.VmomiSupport.vmodl.fault.SystemError'>: (vmodl.fault.S
    ystemError) {
       dynamicType = <unset>,
       dynamicProperty = (vmodl.DynamicProperty) [],
       msg = 'A general system error occurred: No route to host',
       faultCause = <unset>,
       faultMessage = (vmodl.LocalizableMessage) [],
       reason = 'No route to host'
    }
    d:\python\python37-32\lib\threading.py:917:_bootstrap_inner
    d:\python\python37-32\lib\threading.py:865:run
    d:\python\python37-32\lib\site-packages\twisted\_threads\_threadworker.py:46:work
    d:\python\python37-32\lib\site-packages\twisted\_threads\_team.py:190:doWork
    --- <exception caught here> ---
    d:\python\python37-32\lib\site-packages\twisted\python\threadpool.py:250:inContext
    d:\python\python37-32\lib\site-packages\twisted\python\threadpool.py:266:<lambda>
    d:\python\python37-32\lib\site-packages\twisted\python\context.py:122:callWithContext
    d:\python\python37-32\lib\site-packages\twisted\python\context.py:85:callWithContext
    d:\python\python37-32\lib\site-packages\pyVmomi\VmomiSupport.py:706:<lambda>
    d:\python\python37-32\lib\site-packages\pyVmomi\VmomiSupport.py:512:_InvokeMethod
    d:\python\python37-32\lib\site-packages\pyVmomi\SoapAdapter.py:1374:InvokeMethod
    ]]
    --- <exception caught here> ---
    d:\python\python37-32\lib\site-packages\vmware_exporter\vmware_exporter.py:725:_vmware_get_host_perf_manager_metrics
    d:\python\python37-32\lib\site-packages\vmware_exporter\defer.py:99:parallelize
    ]]
    
    Unhandled Error
    Traceback (most recent call last):
      File "D:\Python\Python37-32\Scripts\vmware_exporter.exe\__main__.py", line 7, in <module>
    
      File "d:\python\python37-32\lib\site-packages\vmware_exporter\vmware_exporter.py", line 1112, in main
        reactor.run()
      File "d:\python\python37-32\lib\site-packages\twisted\internet\base.py", line 1272, in run
        self.mainLoop()
      File "d:\python\python37-32\lib\site-packages\twisted\internet\base.py", line 1281, in mainLoop
        self.runUntilCurrent()
    --- <exception caught here> ---
      File "d:\python\python37-32\lib\site-packages\twisted\internet\base.py", line 875, in runUntilCurrent
        f(*a, **kw)
      File "d:\python\python37-32\lib\site-packages\twisted\internet\defer.py", line 501, in errback
        self._startRunCallbacks(fail)
      File "d:\python\python37-32\lib\site-packages\twisted\internet\defer.py", line 568, in _startRunCallbacks
        self._runCallbacks()
      File "d:\python\python37-32\lib\site-packages\twisted\internet\defer.py", line 699, in _runCallbacks
        current.result.cleanFailure()
      File "d:\python\python37-32\lib\site-packages\twisted\python\failure.py", line 627, in cleanFailure
        self.value.__traceback__ = None
      File "d:\python\python37-32\lib\site-packages\pyVmomi\VmomiSupport.py", line 663, in __setattr__
        CheckField(self._GetPropertyInfo(name), val)
      File "d:\python\python37-32\lib\site-packages\pyVmomi\VmomiSupport.py", line 468, in GetPropertyInfo
        raise AttributeError(name)
    builtins.AttributeError: __traceback__
    
    2019-12-03 14:34:55,702 INFO:Start collecting metrics from vxovcsa001
    2019-12-03 14:34:55,702 INFO:Starting vm metrics collection
    2019-12-03 14:34:55,702 INFO:Fetching vim.VirtualMachine inventory
    2019-12-03 14:34:55,702 INFO:Retrieving service instance content

We were doing some maintenance on some of our ESX hosts

    Target: myesx.exemple.com
    Previous Status: Green 
    New Status: Red 
 
    Alarm Definition: 
    ([Red state Is equal to notResponding] AND [Red state Not equal to standBy]) 
 
    Current values for metric/state: 
    State = Not responding AND State = Unknown 
 
    Description: 
    Alarm 'Host connection and power state' on myesx.exemple.com changed from Green to Red

**Comment by dannyk81** [comment]
Interesting, there seem to be few issues here though.

Since the exporter is scraping the vCenter (and not the ESX nodes directly) - that is the case here (right ?) node(s) that goes down/reboots/etc is not expected to affect metrics collection (speaking from personal experience where nodes go up and down all the time in our deployments).

A `no route to host` is an OS level error that suggests that the vCenter could not be reached at some point during the scrape, perhaps the vcenter is a VM on the same node that went down (?)

as to whether we should expose metrics during a partially successful scrape, I'm not sure... would be interesting to check if there's any best practice here or how other exporters handle similar conditions.

**Comment by pryorda** [comment]
Closing due to inactivity.
