### ISSUE TITLE
'Connection refused: The remote service is not running, OR is overloaded, OR a firewall is rejecting connections

### ISSUE THREAD

**Issue by finkr** [pryorda/vmware_exporter#168]
I sometime get this error in the log file (the metrics collection fails, no metrics returned).

I use vmware_exporter-0.11.0.dist-info
and pyvmomi-6.7.1.2018.12-py3.7.egg-info

**Expected behavior:**

I wish the error log was more explicit (especially in debug mode).
Which vcenter was queried ? Which operation was running, which VMware object was queried.

**Log:**

    Unhandled error in Deferred:
    
    Traceback (most recent call last):
    --- <exception caught here> ---
      File "d:\python\python37-32\lib\site-packages\vmware_exporter\vmware_exporter.py", line 725, in _vmware_get_host_perf_manager_metrics
        self.host_labels,
      File "d:\python\python37-32\lib\site-packages\vmware_exporter\defer.py", line 99, in parallelize
        results = yield defer.DeferredList(args, fireOnOneErrback=True)
    twisted.internet.defer.FirstError: FirstError[#0, [Failure instance: Traceback: <class 'pyVmomi.VmomiSupport.vmodl.fault.SystemError'>: (vmodl.fault.SystemError) {
       dynamicType = <unset>,
       dynamicProperty = (vmodl.DynamicProperty) [],
       msg = 'A general system error occurred: Connection refused: The remote service is not running, OR is overloaded, OR a firewall is rejecting connections.',
       faultCause = <unset>,
       faultMessage = (vmodl.LocalizableMessage) [],
       reason = 'Connection refused: The remote service is not running, OR is overloaded, OR a firewall is rejecting connections.'
    }
    d:\python\python37-32\lib\threading.py:917:_bootstrap_inner
    d:\python\python37-32\lib\threading.py:865:run
    d:\python\python37-32\lib\site-packages\twisted\_threads\_threadworker.py:46:work
    d:\python\python37-32\lib\site-packages\twisted\_threads\_team.py:190:doWork
    --- <exception caught here> ---
    d:\python\python37-32\lib\site-packages\twisted\python\threadpool.py:250:inContext
    d:\python\python37-32\lib\site-packages\twisted\python\threadpool.py:266:<lambda>
    d:\python\python37-32\lib\site-packages\twisted\python\context.py:122:callWithContext
    d:\python\python37-32\lib\site-packages\twisted\python\context.py:85:callWithContext
    d:\python\python37-32\lib\site-packages\pyVmomi\VmomiSupport.py:706:<lambda>
    d:\python\python37-32\lib\site-packages\pyVmomi\VmomiSupport.py:512:_InvokeMethod
    d:\python\python37-32\lib\site-packages\pyVmomi\SoapAdapter.py:1374:InvokeMethod
    ]]

**Comment by kremers** [comment]
Can you check with "nc" or "telnet" if you are able to connect from your point of installation to the vmware api server you've configured?

**Comment by ligerard** [comment]
There is a lot of close_wait on the adress:port of the exporter during this period .

**Comment by pryorda** [comment]
Closing due to inactivity.
