### ISSUE TITLE
vmware suddenly stopped working.

### ISSUE THREAD

**Issue by dreiggy** [pryorda/vmware_exporter#180]
Hi,
this night vmware_exporter stopped working:
```
Mar 09 02:40:25 SERVER vmware_exporter[11585]: File "/usr/local/lib/python3.6/site-packages/vmware_exporter-0.11.1-py3.6.egg/vmware_exporter/vmware_exporter.py", line 528, in _vmware_get_data
Mar 09 02:40:25 SERVER vmware_exporter[11585]: results, datastore_labels = yield parallelize(self.datastore_inventory, self.datastore_labels)
Mar 09 02:40:25 SERVER vmware_exporter[11585]: File "/usr/local/lib/python3.6/site-packages/vmware_exporter-0.11.1-py3.6.egg/vmware_exporter/defer.py", line 99, in parallelize
Mar 09 02:40:25 SERVER vmware_exporter[11585]: twisted.internet.defer.FirstError: FirstError[#1, [Failure instance: Traceback: <class 'AttributeError'>: 'NoneType' object has no attribute 'Re
Mar 09 02:40:25 SERVER vmware_exporter[11585]: /usr/local/lib/python3.6/site-packages/Twisted-19.10.0-py3.6-linux-x86_64.egg/twisted/internet/defer.py:501:errback
Mar 09 02:40:25 SERVER vmware_exporter[11585]: /usr/local/lib/python3.6/site-packages/Twisted-19.10.0-py3.6-linux-x86_64.egg/twisted/internet/defer.py:568:_startRunCallbacks
Mar 09 02:40:25 SERVER vmware_exporter[11585]: /usr/local/lib/python3.6/site-packages/Twisted-19.10.0-py3.6-linux-x86_64.egg/twisted/internet/defer.py:654:_runCallbacks
Mar 09 02:40:25 SERVER vmware_exporter[11585]: /usr/local/lib/python3.6/site-packages/Twisted-19.10.0-py3.6-linux-x86_64.egg/twisted/internet/defer.py:1475:gotResult
Mar 09 02:40:25 SERVER vmware_exporter[11585]: --- <exception caught here> ---
Mar 09 02:40:25 SERVER vmware_exporter[11585]: /usr/local/lib/python3.6/site-packages/Twisted-19.10.0-py3.6-linux-x86_64.egg/twisted/internet/defer.py:1416:_inlineCallbacks
Mar 09 02:40:25 SERVER vmware_exporter[11585]: /usr/local/lib/python3.6/site-packages/Twisted-19.10.0-py3.6-linux-x86_64.egg/twisted/python/failure.py:512:throwExceptionIntoGenerator
Mar 09 02:40:25 SERVER vmware_exporter[11585]: /usr/local/lib/python3.6/site-packages/vmware_exporter-0.11.1-py3.6.egg/vmware_exporter/vmware_exporter.py:421:datastore_labels
Mar 09 02:40:25 SERVER vmware_exporter[11585]: /usr/local/lib/python3.6/site-packages/Twisted-19.10.0-py3.6-linux-x86_64.egg/twisted/internet/defer.py:1416:_inlineCallbacks
Mar 09 02:40:25 SERVER vmware_exporter[11585]: /usr/local/lib/python3.6/site-packages/Twisted-19.10.0-py3.6-linux-x86_64.egg/twisted/python/failure.py:512:throwExceptionIntoGenerator
Mar 09 02:40:25 SERVER vmware_exporter[11585]: /usr/local/lib/python3.6/site-packages/vmware_exporter-0.11.1-py3.6.egg/vmware_exporter/vmware_exporter.py:389:datacenter_inventory
Mar 09 02:40:25 SERVER vmware_exporter[11585]: /usr/local/lib/python3.6/site-packages/Twisted-19.10.0-py3.6-linux-x86_64.egg/twisted/internet/defer.py:1418:_inlineCallbacks
Mar 09 02:40:25 SERVER vmware_exporter[11585]: /usr/local/lib/python3.6/site-packages/vmware_exporter-0.11.1-py3.6.egg/vmware_exporter/vmware_exporter.py:273:content
Mar 09 02:40:25 SERVER vmware_exporter[11585]: ]]
Mar 09 02:40:25 SERVER vmware_exporter[11585]: Unhandled error in Deferred:
Mar 09 02:40:25 SERVER vmware_exporter[11585]: Traceback (most recent call last):
Mar 09 02:40:25 SERVER vmware_exporter[11585]: --- <exception caught here> ---
Mar 09 02:40:25 SERVER vmware_exporter[11585]: File "/usr/local/lib/python3.6/site-packages/vmware_exporter-0.11.1-py3.6.egg/vmware_exporter/vmware_exporter.py", line 660, in _vmware_get_host
Mar 09 02:40:25 SERVER vmware_exporter[11585]: host_systems, counter_info = yield parallelize(self.host_system_inventory, self.counter_ids)
Mar 09 02:40:25 SERVER vmware_exporter[11585]: File "/usr/local/lib/python3.6/site-packages/vmware_exporter-0.11.1-py3.6.egg/vmware_exporter/defer.py", line 99, in parallelize
Mar 09 02:40:25 SERVER vmware_exporter[11585]: twisted.internet.defer.FirstError: FirstError[#1, [Failure instance: Traceback: <class 'AttributeError'>: 'NoneType' object has no attribute 'Re
Mar 09 02:40:25 SERVER vmware_exporter[11585]: /usr/local/lib/python3.6/site-packages/Twisted-19.10.0-py3.6-linux-x86_64.egg/twisted/internet/defer.py:501:errback
Mar 09 02:40:25 SERVER vmware_exporter[11585]: /usr/local/lib/python3.6/site-packages/Twisted-19.10.0-py3.6-linux-x86_64.egg/twisted/internet/defer.py:568:_startRunCallbacks
Mar 09 02:40:25 SERVER vmware_exporter[11585]: /usr/local/lib/python3.6/site-packages/Twisted-19.10.0-py3.6-linux-x86_64.egg/twisted/internet/defer.py:654:_runCallbacks
Mar 09 02:40:25 SERVER vmware_exporter[11585]: /usr/local/lib/python3.6/site-packages/Twisted-19.10.0-py3.6-linux-x86_64.egg/twisted/internet/defer.py:1475:gotResult
Mar 09 02:40:25 SERVER vmware_exporter[11585]: --- <exception caught here> ---
Mar 09 02:40:25 SERVER vmware_exporter[11585]: /usr/local/lib/python3.6/site-packages/Twisted-19.10.0-py3.6-linux-x86_64.egg/twisted/internet/defer.py:1416:_inlineCallbacks
Mar 09 02:40:25 SERVER vmware_exporter[11585]: /usr/local/lib/python3.6/site-packages/Twisted-19.10.0-py3.6-linux-x86_64.egg/twisted/python/failure.py:512:throwExceptionIntoGenerator
Mar 09 02:40:25 SERVER vmware_exporter[11585]: /usr/local/lib/python3.6/site-packages/vmware_exporter-0.11.1-py3.6.egg/vmware_exporter/vmware_exporter.py:489:counter_ids
Mar 09 02:40:25 SERVER vmware_exporter[11585]: /usr/local/lib/python3.6/site-packages/Twisted-19.10.0-py3.6-linux-x86_64.egg/twisted/internet/defer.py:1418:_inlineCallbacks
Mar 09 02:40:25 SERVER vmware_exporter[11585]: /usr/local/lib/python3.6/site-packages/vmware_exporter-0.11.1-py3.6.egg/vmware_exporter/vmware_exporter.py:273:content
Mar 09 02:40:25 SERVER vmware_exporter[11585]: ]]
Mar 09 02:40:25 SERVER vmware_exporter[11585]: Unhandled error in Deferred:
Mar 09 02:40:25 SERVER vmware_exporter[11585]: Traceback (most recent call last):
Mar 09 02:40:25 SERVER vmware_exporter[11585]: --- <exception caught here> ---
Mar 09 02:40:25 SERVER vmware_exporter[11585]: File "/usr/local/lib/python3.6/site-packages/vmware_exporter-0.11.1-py3.6.egg/vmware_exporter/vmware_exporter.py", line 744, in _vmware_get_vms
Mar 09 02:40:25 SERVER vmware_exporter[11585]: virtual_machines, vm_labels = yield parallelize(self.vm_inventory, self.vm_labels)
Mar 09 02:40:25 SERVER vmware_exporter[11585]: File "/usr/local/lib/python3.6/site-packages/vmware_exporter-0.11.1-py3.6.egg/vmware_exporter/defer.py", line 99, in parallelize
Mar 09 02:40:25 SERVER vmware_exporter[11585]: twisted.internet.defer.FirstError: FirstError[#1, [Failure instance: Traceback: <class 'twisted.internet.defer.FirstError'>: FirstError[#0, [Fai
Mar 09 02:40:25 SERVER vmware_exporter[11585]: /usr/local/lib/python3.6/site-packages/Twisted-19.10.0-py3.6-linux-x86_64.egg/twisted/internet/defer.py:501:errback
Mar 09 02:40:25 SERVER vmware_exporter[11585]: /usr/local/lib/python3.6/site-packages/Twisted-19.10.0-py3.6-linux-x86_64.egg/twisted/internet/defer.py:568:_startRunCallbacks
Mar 09 02:40:25 SERVER vmware_exporter[11585]: /usr/local/lib/python3.6/site-packages/Twisted-19.10.0-py3.6-linux-x86_64.egg/twisted/internet/defer.py:654:_runCallbacks
Mar 09 02:40:25 SERVER vmware_exporter[11585]: /usr/local/lib/python3.6/site-packages/Twisted-19.10.0-py3.6-linux-x86_64.egg/twisted/internet/defer.py:1475:gotResult
```

Maybe somebody knows how to resolve issue?

**Comment by pryorda** [comment]
@dreiggy What changed before these errors started popping up? Based on all the none types it seems like its failing to get data from vcenter.

**Comment by dreiggy** [comment]
Hi,
found solution, issue was with firewall rules... Everything works well.
