### ISSUE TITLE
Data Collecting stops after ESXi Reboot

### ISSUE THREAD

**Issue by Protoje** [pryorda/vmware_exporter#185]
Hey guys,

a little bit of context before the issue:
we are currently in a transition phase were we want to rebuild our monitoring system. Since about 7 years we used Zabbix and now we want to go for a Prometheus build. Therefore, we try to run the background with prometheus exporters, but still use Zabbix for the foreground, since its our current productive system. And when the switch day comes, we can just switch everything onto Prometheus.
Currently i am testing all the exporters, including this vmware exporter running in a container.  So far, i was pleasently satisfied with what it does. We were able to implement it into the current productive System (zabbix) without real problems. Today, we wanted to test all the triggers and the data collection, but we ran into something very weird.
Everytime my colleague rebooted one of the ESX Hosts, the Exporter stopped collecting the metrics with the message "#Collection failed", as seen in the following picture:

![image](https://user-images.githubusercontent.com/11775627/78343215-ca706b80-759a-11ea-95e6-f068ee8441a7.png)

It took around a minute before it started collecting again (around the time where the vCenter showed the ESX host as "not Responding". 
Zabbix then took around 7-9 minutes before being able to collect the Data again (i had to do a "check now" on the HTTP Item to retrieve the Data instantly and therefore being able to have that little time window where i can check the triggers)

So, we are currently searching for an explanation why this is happening. We tested it on several ESX hosts, but everytime he rebooted one, the Data Collection stopped working for a minute or two. 
Which is weird, cause the Exporter collects the Data from the vcenter itself, not from the esx, right?

Does any of you have an explanation for this or ran into a similiar thing?

Thanks in advance!
Greetings,
Josh

**Comment by pryorda** [comment]
We would need to see the logs on the end nodes. My guess is its an inconsistency with all the data mapping and its causing an exception.

**Comment by Protoje** [comment]
Sorry for my late response, we are swimming in workload atm :'D

I am right now testing it again while retrieving the logs from the container. 
The logs are:
`2020-04-17 09:01:29,144 INFO:Finished host metrics collection
builtins.AttributeError: __traceback__
    raise AttributeError(name)
  File "/usr/local/lib/python3.6/dist-packages/pyVmomi/VmomiSupport.py", line 468, in                        GetPropertyInfo
    CheckField(self._GetPropertyInfo(name), val)
  File "/usr/local/lib/python3.6/dist-packages/pyVmomi/VmomiSupport.py", line 663, in                        __setattr__
    self.value.__traceback__ = None
  File "/usr/local/lib/python3.6/dist-packages/twisted/python/failure.py", line 627,                        in cleanFailure
    current.result.cleanFailure()
  File "/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py", line 699,                        in _runCallbacks
    self._runCallbacks()
  File "/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py", line 568,                        in _startRunCallbacks
    self._startRunCallbacks(fail)
  File "/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py", line 501,                        in errback
    f(*a, **kw)
  File "/usr/local/lib/python3.6/dist-packages/twisted/internet/base.py", line 886, i                       n runUntilCurrent
--- <exception caught here> ---
    self.runUntilCurrent()
  File "/usr/local/lib/python3.6/dist-packages/twisted/internet/base.py", line 1292,                        in mainLoop
    self.mainLoop()
  File "/usr/local/lib/python3.6/dist-packages/twisted/internet/base.py", line 1283,                        in run
    reactor.run()
  File "/usr/local/lib/python3.6/dist-packages/vmware_exporter/vmware_exporter.py", l                       ine 1112, in main
    sys.exit(main())
  File "/usr/local/bin/vmware_exporter", line 11, in <module>
Traceback (most recent call last):
Unhandled Error
]]
/usr/local/lib/python3.6/dist-packages/vmware_exporter/defer.py:99:parallelize
/usr/local/lib/python3.6/dist-packages/vmware_exporter/vmware_exporter.py:725:_vmware                       _get_host_perf_manager_metrics
--- <exception caught here> ---
]]
/usr/local/lib/python3.6/dist-packages/pyVmomi/SoapAdapter.py:1397:InvokeMethod
/usr/local/lib/python3.6/dist-packages/pyVmomi/VmomiSupport.py:512:_InvokeMethod
/usr/local/lib/python3.6/dist-packages/pyVmomi/VmomiSupport.py:706:<lambda>
/usr/local/lib/python3.6/dist-packages/twisted/python/context.py:85:callWithContext
/usr/local/lib/python3.6/dist-packages/twisted/python/context.py:122:callWithContext
/usr/local/lib/python3.6/dist-packages/twisted/python/threadpool.py:266:<lambda>
/usr/local/lib/python3.6/dist-packages/twisted/python/threadpool.py:250:inContext
--- <exception caught here> ---
/usr/local/lib/python3.6/dist-packages/twisted/_threads/_team.py:190:doWork
/usr/local/lib/python3.6/dist-packages/twisted/_threads/_threadworker.py:46:work
/usr/lib/python3.6/threading.py:864:run
/usr/lib/python3.6/threading.py:916:_bootstrap_inner
}
   reason = 'Connection refused: The remote service is not running, OR is overloaded,                        OR a firewall is rejecting connections.'
   faultMessage = (vmodl.LocalizableMessage) [],
   faultCause = <unset>,
   msg = 'A general system error occurred: Connection refused: The remote service is                        not running, OR is overloaded, OR a firewall is rejecting connections.',
   dynamicProperty = (vmodl.DynamicProperty) [],
   dynamicType = <unset>,
twisted.internet.defer.FirstError: FirstError[#2, [Failure instance: Traceback: <clas                       s 'twisted.internet.defer.FirstError'>: FirstError[#0, [Failure instance: Traceback:                        <class 'pyVmomi.VmomiSupport.vmodl.fault.SystemError'>: (vmodl.fault.SystemError) {
    yield self.generate_latest_metrics(request)
  File "/usr/local/lib/python3.6/dist-packages/vmware_exporter/vmware_exporter.py", l                       ine 997, in _async_render_GET
2020-04-17 09:01:28,531 ERROR:Traceback (most recent call last):
2020-04-17 09:01:28,506 INFO:Fetched vim.Datastore inventory (0:00:00.454875)
2020-04-17 09:01:28,505 INFO:Fetched vim.HostSystem inventory (0:00:00.452160)
2020-04-17 09:01:28,166 INFO:Retrieved service instance content
2020-04-17 09:01:28,053 INFO:START: _vmware_get_host_perf_manager_metrics
2020-04-17 09:01:28,053 INFO:Fetching vim.HostSystem inventory
2020-04-17 09:01:28,052 INFO:Starting host metrics collection
2020-04-17 09:01:28,052 INFO:Retrieving service instance content
2020-04-17 09:01:28,051 INFO:Fetching vim.Datastore inventory
2020-04-17 09:01:28,051 INFO:Start collecting metrics from vcenterxa02.id.dvag.com
2020-04-17 09:01:26,593 INFO:Finished host metrics collection
builtins.AttributeError: __traceback__
    raise AttributeError(name)
  File "/usr/local/lib/python3.6/dist-packages/pyVmomi/VmomiSupport.py", line 468, in                        GetPropertyInfo
    CheckField(self._GetPropertyInfo(name), val)
  File "/usr/local/lib/python3.6/dist-packages/pyVmomi/VmomiSupport.py", line 663, in                        __setattr__
    self.value.__traceback__ = None
  File "/usr/local/lib/python3.6/dist-packages/twisted/python/failure.py", line 627,                        in cleanFailure
    current.result.cleanFailure()
  File "/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py", line 699,                        in _runCallbacks
    self._runCallbacks()
  File "/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py", line 568,                        in _startRunCallbacks
    self._startRunCallbacks(fail)
  File "/usr/local/lib/python3.6/dist-packages/twisted/internet/defer.py", line 501,                        in errback
    f(*a, **kw)
  File "/usr/local/lib/python3.6/dist-packages/twisted/internet/base.py", line 886, i                       n runUntilCurrent
--- <exception caught here> ---
    self.runUntilCurrent()
  File "/usr/local/lib/python3.6/dist-packages/twisted/internet/base.py", line 1292,                        in mainLoop
    self.mainLoop()
  File "/usr/local/lib/python3.6/dist-packages/twisted/internet/base.py", line 1283,                        in run
    reactor.run()
  File "/usr/local/lib/python3.6/dist-packages/vmware_exporter/vmware_exporter.py", l                       ine 1112, in main
    sys.exit(main())
  File "/usr/local/bin/vmware_exporter", line 11, in <module>
Traceback (most recent call last):
Unhandled Error
]]
/usr/local/lib/python3.6/dist-packages/vmware_exporter/defer.py:99:parallelize
/usr/local/lib/python3.6/dist-packages/vmware_exporter/vmware_exporter.py:725:_vmware                       _get_host_perf_manager_metrics
--- <exception caught here> ---
]]`

Looks like the following issue:
https://github.com/pryorda/vmware_exporter/issues/168

We also checked connecting to the api from a local admin vm while the exporter wasn't able to collect the data and we also got refused.
For us, it currently looks like its a problem on the vcenter/vmware side and not the exporters. 

i will close this issue for now. We are now creating an issue at vmwares side to get that  checked. If i find any further information on this issue, i will keep you updated.
If we get to the conclusion that it might be the exporters side, i will reopen this issue, if thats ok for you.
