### ISSUE TITLE
Collecting `hosts` and `vms` fails with `Request.finish called on a request after its connection was lost`

### ISSUE THREAD

**Issue by MrStrix** [pryorda/vmware_exporter#186]
We have a rather big vSphere cluster with >2000 VMs and ~80 Hosts. We tried to install the vmware_exporter with the helm chart [kremers/vmware-exporter](https://github.com/kremers/charts-vmware-exporter). When I enable `VSPHERE_COLLECT_HOSTS` or `VSPHERE_COLLECT_VMS` python fails with the following error:

```
2020-04-09 12:26:39,143 ERROR:Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
StopIteration: [<prometheus_client.core.GaugeMetricFamily object at 0x7f609d327da0>, <prometheus_client.core.GaugeMetricFamily object at 0x7f609d327780>, <prometheus_client.core.GaugeMetricFamily object at 0x7f609d327b00>, <prometheus_client.core.GaugeMetricFamily object at 0x7f609d55be10>, <prometheus_client.core.GaugeMetricFamily object at 0x7f609d55beb8>, <prometheus_client.core.GaugeMetricFamily object at 0x7f609d55be80>, <prometheus_client.core.GaugeMetricFamily object at 0x7f609d55bf28>, <prometheus_client.core.GaugeMetricFamily object at 0x7f609d55bfd0>, <prometheus_client.core.GaugeMetricFamily object at 0x7f609d55bf98>, <prometheus_client.core.GaugeMetricFamily object at 0x7f609d55bf60>, <prometheus_client.core.GaugeMetricFamily object at 0x7f609d4fed68>, <prometheus_client.core.GaugeMetricFamily object at 0x7f609d4384e0>, <prometheus_client.core.GaugeMetricFamily object at 0x7f609d564278>, <prometheus_client.core.GaugeMetricFamily object at 0x7f609d5642b0>, <prometheus_client.core.GaugeMetricFamily object at 0x7f609d5642e8>, <prometheus_client.core.GaugeMetricFamily object at 0x7f609d564320>, <prometheus_client.core.GaugeMetricFamily object at 0x7f609d564358>, <prometheus_client.core.GaugeMetricFamily object at 0x7f609d564390>, <prometheus_client.core.GaugeMetricFamily object at 0x7f609d5643c8>, <prometheus_client.core.GaugeMetricFamily object at 0x7f609d564400>, <prometheus_client.core.GaugeMetricFamily object at 0x7f609d564438>, <prometheus_client.core.GaugeMetricFamily object at 0x7f609d564470>, <prometheus_client.core.GaugeMetricFamily object at 0x7f609d5644a8>, <prometheus_client.core.GaugeMetricFamily object at 0x7f609d564550>, <prometheus_client.core.GaugeMetricFamily object at 0x7f609d564588>, <prometheus_client.core.GaugeMetricFamily object at 0x7f609d5645c0>, <prometheus_client.core.GaugeMetricFamily object at 0x7f609d5645f8>, <prometheus_client.core.GaugeMetricFamily object at 0x7f609d564630>, <prometheus_client.core.GaugeMetricFamily object at 0x7f609d564668>, <prometheus_client.core.GaugeMetricFamily object at 0x7f609d5646a0>, <prometheus_client.core.GaugeMetricFamily object at 0x7f609d5646d8>, <prometheus_client.core.GaugeMetricFamily object at 0x7f609d569588>, <prometheus_client.core.GaugeMetricFamily object at 0x7f609d5690f0>, <prometheus_client.core.GaugeMetricFamily object at 0x7f6095dbe2b0>, <prometheus_client.core.GaugeMetricFamily object at 0x7f6095dbe160>, <prometheus_client.core.GaugeMetricFamily object at 0x7f6095dbe3c8>, <prometheus_client.core.GaugeMetricFamily object at 0x7f6095dbe400>, <prometheus_client.core.GaugeMetricFamily object at 0x7f6095dbe438>, <prometheus_client.core.GaugeMetricFamily object at 0x7f6095dbe358>, <prometheus_client.core.GaugeMetricFamily object at 0x7f6095dbe470>, <prometheus_client.core.GaugeMetricFamily object at 0x7f6095dbe4a8>, <prometheus_client.core.GaugeMetricFamily object at 0x7f6095dbe4e0>, <prometheus_client.core.GaugeMetricFamily object at 0x7f6095dbe5f8>, <prometheus_client.core.GaugeMetricFamily object at 0x7f6095dbe518>, <prometheus_client.core.GaugeMetricFamily object at 0x7f6095dbe5c0>, <prometheus_client.core.GaugeMetricFamily object at 0x7f6095dbe630>, <prometheus_client.core.GaugeMetricFamily object at 0x7f6095dbe668>, <prometheus_client.core.GaugeMetricFamily object at 0x7f6095dbe710>, <prometheus_client.core.GaugeMetricFamily object at 0x7f6095dbe6a0>, <prometheus_client.core.GaugeMetricFamily object at 0x7f6095dbe6d8>, <prometheus_client.core.GaugeMetricFamily object at 0x7f6095dbe588>, <prometheus_client.core.GaugeMetricFamily object at 0x7f6095dbe7f0>, <prometheus_client.core.GaugeMetricFamily object at 0x7f6095dbe828>, <prometheus_client.core.GaugeMetricFamily object at 0x7f6095dbe860>, <prometheus_client.core.GaugeMetricFamily object at 0x7f6095dbe780>, <prometheus_client.core.GaugeMetricFamily object at 0x7f6095dbe898>, <prometheus_client.core.GaugeMetricFamily object at 0x7f6095dbe8d0>, <prometheus_client.core.GaugeMetricFamily object at 0x7f609d134ba8>, <prometheus_client.core.GaugeMetricFamily object at 0x7f60958a4160>, <prometheus_client.core.GaugeMetricFamily object at 0x7f60958a4ef0>, <prometheus_client.core.GaugeMetricFamily object at 0x7f60958a4a20>, <prometheus_client.core.GaugeMetricFamily object at 0x7f60958a4860>, <prometheus_client.core.GaugeMetricFamily object at 0x7f60958a49b0>, <prometheus_client.core.GaugeMetricFamily object at 0x7f60958a4d30>, <prometheus_client.core.GaugeMetricFamily object at 0x7f60958a4d68>, <prometheus_client.core.GaugeMetricFamily object at 0x7f60958a40f0>, <prometheus_client.core.GaugeMetricFamily object at 0x7f60958a4278>, <prometheus_client.core.GaugeMetricFamily object at 0x7f6096bbea20>, <prometheus_client.core.GaugeMetricFamily object at 0x7f6096bbe630>, <prometheus_client.core.GaugeMetricFamily object at 0x7f6096bbe8d0>, <prometheus_client.core.GaugeMetricFamily object at 0x7f6096bbea90>, <prometheus_client.core.GaugeMetricFamily object at 0x7f6096bbe978>, <prometheus_client.core.GaugeMetricFamily object at 0x7f6096bbeef0>, <prometheus_client.core.GaugeMetricFamily object at 0x7f6096bbecc0>, <prometheus_client.core.GaugeMetricFamily object at 0x7f6096bbedd8>, <prometheus_client.core.GaugeMetricFamily object at 0x7f6096bbee80>, <prometheus_client.core.GaugeMetricFamily object at 0x7f6096bbee10>, <prometheus_client.core.GaugeMetricFamily object at 0x7f6096bbe550>, <prometheus_client.core.GaugeMetricFamily object at 0x7f60968762b0>, <prometheus_client.core.GaugeMetricFamily object at 0x7f6096876160>, <prometheus_client.core.GaugeMetricFamily object at 0x7f6096876358>]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/vmware_exporter/vmware_exporter.py", line 992, in _async_render_GET
    yield self.generate_latest_metrics(request)
  File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/usr/local/lib/python3.6/site-packages/vmware_exporter/vmware_exporter.py", line 1040, in generate_latest_metrics
    request.finish()
  File "/usr/local/lib/python3.6/site-packages/twisted/web/server.py", line 268, in finish
    return http.Request.finish(self)
  File "/usr/local/lib/python3.6/site-packages/twisted/web/http.py", line 1071, in finish
    "Request.finish called on a request after its connection was lost; "
RuntimeError: Request.finish called on a request after its connection was lost; use Request.notifyFinish to keep track of this.
```

Any ideas where this might come from?

**Comment by Jc2k** [comment]
Prometheus closed the connection before the results were delivered from vsphere. So the metrics were collected (probably) but the process that asked for them got bored and wandered off. Try increasing the Prometheus timeout. The vSphere API is slow, especially at that scale, so you might not be able to pull the metrics as often as you would like either.

**Comment by joereyna** [comment]
I have the same problem.  Can we add a prometheus timeout to the deployment.yml file under annotations?  Maybe something like this?  I've tried it, but I still get the same problem as MrStrix:

`annotations:
        prometheus.io/port: "9272"
        prometheus.io/scrape: "true"
        prometheus.io/scrape_timeout: "180"
        prometheus.io/timeout: "180"`

**Comment by MrStrix** [comment]
As I had configured prometheus with a `static_scrape` config, I increased the values to `scrape_timeout: 2m` and `scrape_interval: 4m` which seems to work

**Comment by pryorda** [comment]
Going to close this out as it seems there is a resolution around this.
