### ISSUE TITLE
All nodes become down when two or more failed nodes are unavailable

### ISSUE THREAD

**Issue by linkingli** [pryorda/vmware_exporter#205]
version：
```
pryorda/vmware_exporter:v0.11.0
```

There are two or more failed vcenter nodes in the vcenter list. About 1 hour later, the Targets page of Prometheus shows that the vcenter state that could normally be connected turns DOWN, resulting in abnormal monitoring and warning functions of all vcenters.

It looks like something is taking up the CPU. After rebooting the pod of k8s, everything is fine

**Comment by pryorda** [comment]
@linkingli Are you seeing this happen continuously and what is your scrape interval/timeout set to?

**Comment by pryorda** [comment]
Can you test with 0.13.1 and let me know if it still happens?

**Comment by linkingli** [comment]
I try to use 0.13.1,It looks like something bad didn't happen the only difference is the crawling time of promethus, 15s->20s,
I will follow up for a while and close the issue if it doesn’t appear,

**Comment by maxkushnir** [comment]
Created configuration with hosts which are down. Receiving error:
```
Unhandled error in Deferred:

Traceback (most recent call last):
--- <exception caught here> ---
  File "/usr/local/lib/python3.7/site-packages/vmware_exporter/vmware_exporter.py", line 1372, in _vmware_get_host_perf_manager_metrics
    host_systems, counter_info = yield parallelize(self.host_system_inventory, self.counter_ids)
  File "/usr/local/lib/python3.7/site-packages/vmware_exporter/defer.py", line 99, in parallelize
    results = yield defer.DeferredList(args, fireOnOneErrback=True)
twisted.internet.defer.FirstError: FirstError[#1, [Failure instance: Traceback: <class 'socket.gaierror'>: [Errno -2] Name does not resolve
/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py:501:errback
/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py:568:_startRunCallbacks
/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py:654:_runCallbacks
/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py:1475:gotResult
--- <exception caught here> ---
/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py:1416:_inlineCallbacks
/usr/local/lib/python3.7/site-packages/twisted/python/failure.py:512:throwExceptionIntoGenerator
/usr/local/lib/python3.7/site-packages/vmware_exporter/vmware_exporter.py:1098:counter_ids
/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py:1416:_inlineCallbacks
/usr/local/lib/python3.7/site-packages/twisted/python/failure.py:512:throwExceptionIntoGenerator
/usr/local/lib/python3.7/site-packages/vmware_exporter/vmware_exporter.py:560:content
/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py:1416:_inlineCallbacks
/usr/local/lib/python3.7/site-packages/twisted/python/failure.py:512:throwExceptionIntoGenerator
/usr/local/lib/python3.7/site-packages/vmware_exporter/vmware_exporter.py:548:connection
/usr/local/lib/python3.7/site-packages/twisted/python/threadpool.py:250:inContext
/usr/local/lib/python3.7/site-packages/twisted/python/threadpool.py:266:<lambda>
/usr/local/lib/python3.7/site-packages/twisted/python/context.py:122:callWithContext
/usr/local/lib/python3.7/site-packages/twisted/python/context.py:85:callWithContext
/usr/local/lib/python3.7/site-packages/pyVim/connect.py:847:SmartConnect
/usr/local/lib/python3.7/site-packages/pyVim/connect.py:726:__FindSupportedVersion
/usr/local/lib/python3.7/site-packages/pyVim/connect.py:643:__GetServiceVersionDescription
/usr/local/lib/python3.7/site-packages/pyVim/connect.py:608:__GetElementTree
/usr/local/lib/python3.7/http/client.py:1277:request
/usr/local/lib/python3.7/http/client.py:1323:_send_request
/usr/local/lib/python3.7/http/client.py:1272:endheaders
/usr/local/lib/python3.7/http/client.py:1032:_send_output
/usr/local/lib/python3.7/http/client.py:972:send
/usr/local/lib/python3.7/http/client.py:1439:connect
/usr/local/lib/python3.7/http/client.py:944:connect
/usr/local/lib/python3.7/socket.py:707:create_connection
/usr/local/lib/python3.7/socket.py:752:getaddrinfo
]]
```
Also, Prometheus shows that **all hosts** are down, which strange.
```
scrape_interval: 240s
scrape_timeout: 60s
```
Using the latest vmware_exporter version from docker hub. Running in docker-compose. 
Python 3.7. 
ESXi 6.7.0 Update 3 (Build 15160138)

**Comment by pryorda** [comment]
Closing due to inactivity.
