### ISSUE TITLE
Traceback error when running exporter

### ISSUE THREAD

**Issue by NosIreland** [pryorda/vmware_exporter#207]
Hi,
I tried to run exporter and getting traceback error:
```
2020-06-08 13:14:52,885 INFO:Starting web server on port 9272
2020-06-08 13:15:02,413 ERROR:Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/vmware_exporter/vmware_exporter.py", line 1838, in _async_render_GET
    yield self.generate_latest_metrics(request)
KeyError: 'specs_size'
```
I created my own container image from git. I get the same error if I pull image from docker hub, just different line.
```
2020-06-08 12:41:37,372 INFO:Starting web server on port 9272
2020-06-08 12:42:44,539 ERROR:Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/vmware_exporter/vmware_exporter.py", line 1638, in _async_render_GET
    yield self.generate_latest_metrics(request)
KeyError: 'specs_size'
```
Any idea what could be the cause?
Thanks

**Comment by pryorda** [comment]
What version are you on?>

**Comment by pryorda** [comment]
The default is 5000, if you set the value to specs_size: 5000 does it still error?

**Comment by andrewm659** [comment]
I'm having the same issue on VMWARE ESXi 7.0.  Where do I set this?

**Comment by vanlongme** [comment]
same issue on vCenter 7.0

**Comment by pryorda** [comment]
closed for staleness. Readme shows how to set these values.
