### ISSUE TITLE
Cannot collect metrics with docker-compose

### ISSUE THREAD

**Issue by seyfbarhoumi** [pryorda/vmware_exporter#211]
Hello, i've tried the new version of vmware exporter i would say it has way too better performance to the first release, great job.
But i still have the same issue running it inside as a docker-compose service, but it works perfectly as a standalone container.

Here's the docker-compose.yml file content , it's so simple, and should be working
```
version: '3.7'
services:
  exporter:
    image: pryorda/vmware_exporter
    ports:
        - "9272:9272"
    environment:
        VSPHERE_HOST: "****************"
        VSPHERE_USER: "****************"
        VSPHERE_PASSWORD: "*******************"
        VSPHERE_IGNORE_SSL: "True"
        VSPHERE_COLLECT_HOSTS: "True"
        VSPHERE_COLLECT_DATASTORES: "True"
        VSPHERE_COLLECT_VMS: "True"
        VSPHERE_COLLECT_VMGUESTS: "True"
        VSPHERE_COLLECT_SNAPSHOTS: "True" 
```
And here are the logs:
```
exporter_1  | 2020-06-30 14:35:52,026 INFO:Starting web server on port 9272
exporter_1  | 2020-06-30 14:35:54,922 INFO:Start collecting metrics from bams-vcenter
exporter_1  | 2020-06-30 14:35:54,922 INFO:Starting vm metrics collection
exporter_1  | 2020-06-30 14:35:54,922 INFO:Fetching vim.VirtualMachine inventory
exporter_1  | 2020-06-30 14:35:54,924 INFO:Retrieving service instance content
exporter_1  | 2020-06-30 14:35:54,926 INFO:START: _vmware_get_vm_perf_manager_metrics
exporter_1  | 2020-06-30 14:35:54,926 INFO:Fetching vim.Datastore inventory
exporter_1  | 2020-06-30 14:35:54,926 INFO:Starting host metrics collection
exporter_1  | 2020-06-30 14:35:54,926 INFO:Fetching vim.HostSystem inventory
exporter_1  | 2020-06-30 14:35:54,927 INFO:START: _vmware_get_host_perf_manager_metrics
exporter_1  | 2020-06-30 14:35:59,935 ERROR:Traceback (most recent call last):
exporter_1  |   File "/usr/local/lib/python3.6/site-packages/vmware_exporter/vmware_exporter.py", line 1638, in _async_render_GET
exporter_1  |     yield self.generate_latest_metrics(request)
exporter_1  | twisted.internet.defer.FirstError: FirstError[#0, [Failure instance: Traceback: <class 'twisted.internet.defer.FirstError'>: FirstError[#1, [Failure instance: Traceback: <class 'twisted.internet.defer.FirstError'>: FirstError[#0, [Failure instance: Traceback: <class 'socket.gaierror'>: [Errno -3] Try again
exporter_1  | /usr/local/lib/python3.6/site-packages/twisted/internet/defer.py:501:errback
exporter_1  | /usr/local/lib/python3.6/site-packages/twisted/internet/defer.py:568:_startRunCallbacks
exporter_1  | /usr/local/lib/python3.6/site-packages/twisted/internet/defer.py:654:_runCallbacks
exporter_1  | /usr/local/lib/python3.6/site-packages/twisted/internet/defer.py:1475:gotResult
exporter_1  | --- <exception caught here> ---
exporter_1  | /usr/local/lib/python3.6/site-packages/twisted/internet/defer.py:1416:_inlineCallbacks
exporter_1  | /usr/local/lib/python3.6/site-packages/twisted/python/failure.py:512:throwExceptionIntoGenerator
exporter_1  | /usr/local/lib/python3.6/site-packages/vmware_exporter/vmware_exporter.py:623:vm_inventory
exporter_1  | /usr/local/lib/python3.6/site-packages/twisted/internet/defer.py:1416:_inlineCallbacks
exporter_1  | /usr/local/lib/python3.6/site-packages/twisted/python/failure.py:512:throwExceptionIntoGenerator
exporter_1  | /usr/local/lib/python3.6/site-packages/vmware_exporter/vmware_exporter.py:471:batch_fetch_properties
exporter_1  | /usr/local/lib/python3.6/site-packages/twisted/internet/defer.py:1416:_inlineCallbacks
exporter_1  | /usr/local/lib/python3.6/site-packages/twisted/python/failure.py:512:throwExceptionIntoGenerator
exporter_1  | /usr/local/lib/python3.6/site-packages/vmware_exporter/vmware_exporter.py:461:content
exporter_1  | /usr/local/lib/python3.6/site-packages/twisted/internet/defer.py:1416:_inlineCallbacks
exporter_1  | /usr/local/lib/python3.6/site-packages/twisted/python/failure.py:512:throwExceptionIntoGenerator
exporter_1  | /usr/local/lib/python3.6/site-packages/vmware_exporter/vmware_exporter.py:449:connection
exporter_1  | /usr/local/lib/python3.6/site-packages/twisted/python/threadpool.py:250:inContext
exporter_1  | /usr/local/lib/python3.6/site-packages/twisted/python/threadpool.py:266:<lambda>
exporter_1  | /usr/local/lib/python3.6/site-packages/twisted/python/context.py:122:callWithContext
exporter_1  | /usr/local/lib/python3.6/site-packages/twisted/python/context.py:85:callWithContext
exporter_1  | /usr/local/lib/python3.6/site-packages/pyVim/connect.py:847:SmartConnect
exporter_1  | /usr/local/lib/python3.6/site-packages/pyVim/connect.py:726:__FindSupportedVersion
exporter_1  | /usr/local/lib/python3.6/site-packages/pyVim/connect.py:643:__GetServiceVersionDescription
exporter_1  | /usr/local/lib/python3.6/site-packages/pyVim/connect.py:608:__GetElementTree
exporter_1  | /usr/local/lib/python3.6/http/client.py:1262:request
exporter_1  | /usr/local/lib/python3.6/http/client.py:1308:_send_request
exporter_1  | /usr/local/lib/python3.6/http/client.py:1257:endheaders
exporter_1  | /usr/local/lib/python3.6/http/client.py:1036:_send_output
exporter_1  | /usr/local/lib/python3.6/http/client.py:974:send
exporter_1  | /usr/local/lib/python3.6/http/client.py:1415:connect
exporter_1  | /usr/local/lib/python3.6/http/client.py:946:connect
exporter_1  | /usr/local/lib/python3.6/socket.py:704:create_connection
exporter_1  | /usr/local/lib/python3.6/socket.py:745:getaddrinfo
exporter_1  | ]]
exporter_1  | --- <exception caught here> ---
exporter_1  | /usr/local/lib/python3.6/site-packages/vmware_exporter/vmware_exporter.py:930:vm_labels
exporter_1  | /usr/local/lib/python3.6/site-packages/vmware_exporter/defer.py:99:parallelize
exporter_1  | ]]
exporter_1  | --- <exception caught here> ---
exporter_1  | /usr/local/lib/python3.6/site-packages/vmware_exporter/vmware_exporter.py:1320:_vmware_get_vms
exporter_1  | /usr/local/lib/python3.6/site-packages/vmware_exporter/defer.py:99:parallelize
exporter_1  | ]]
exporter_1  | 
exporter_1  | Unhandled error in Deferred:
exporter_1  | 
exporter_1  | Traceback (most recent call last):
exporter_1  | --- <exception caught here> ---
exporter_1  |   File "/usr/local/lib/python3.6/site-packages/vmware_exporter/vmware_exporter.py", line 930, in vm_labels
exporter_1  |     virtual_machines, host_labels = yield parallelize(self.vm_inventory, self.host_labels)
exporter_1  |   File "/usr/local/lib/python3.6/site-packages/vmware_exporter/defer.py", line 99, in parallelize
exporter_1  |     results = yield defer.DeferredList(args, fireOnOneErrback=True)
exporter_1  | twisted.internet.defer.FirstError: FirstError[#0, [Failure instance: Traceback: <class 'socket.gaierror'>: [Errno -3] Try again
exporter_1  | /usr/local/lib/python3.6/site-packages/twisted/internet/defer.py:501:errback
exporter_1  | /usr/local/lib/python3.6/site-packages/twisted/internet/defer.py:568:_startRunCallbacks
exporter_1  | /usr/local/lib/python3.6/site-packages/twisted/internet/defer.py:654:_runCallbacks
exporter_1  | /usr/local/lib/python3.6/site-packages/twisted/internet/defer.py:1475:gotResult
exporter_1  | --- <exception caught here> ---
exporter_1  | /usr/local/lib/python3.6/site-packages/twisted/internet/defer.py:1416:_inlineCallbacks
exporter_1  | /usr/local/lib/python3.6/site-packages/twisted/python/failure.py:512:throwExceptionIntoGenerator
exporter_1  | /usr/local/lib/python3.6/site-packages/vmware_exporter/vmware_exporter.py:623:vm_inventory
exporter_1  | /usr/local/lib/python3.6/site-packages/twisted/internet/defer.py:1416:_inlineCallbacks
exporter_1  | /usr/local/lib/python3.6/site-packages/twisted/python/failure.py:512:throwExceptionIntoGenerator
exporter_1  | /usr/local/lib/python3.6/site-packages/vmware_exporter/vmware_exporter.py:471:batch_fetch_properties
exporter_1  | /usr/local/lib/python3.6/site-packages/twisted/internet/defer.py:1416:_inlineCallbacks
exporter_1  | /usr/local/lib/python3.6/site-packages/twisted/python/failure.py:512:throwExceptionIntoGenerator
exporter_1  | /usr/local/lib/python3.6/site-packages/vmware_exporter/vmware_exporter.py:461:content
exporter_1  | /usr/local/lib/python3.6/site-packages/twisted/internet/defer.py:1416:_inlineCallbacks
exporter_1  | /usr/local/lib/python3.6/site-packages/twisted/python/failure.py:512:throwExceptionIntoGenerator
exporter_1  | /usr/local/lib/python3.6/site-packages/vmware_exporter/vmware_exporter.py:449:connection
exporter_1  | /usr/local/lib/python3.6/site-packages/twisted/python/threadpool.py:250:inContext
exporter_1  | /usr/local/lib/python3.6/site-packages/twisted/python/threadpool.py:266:<lambda>
exporter_1  | /usr/local/lib/python3.6/site-packages/twisted/python/context.py:122:callWithContext
exporter_1  | /usr/local/lib/python3.6/site-packages/twisted/python/context.py:85:callWithContext
exporter_1  | /usr/local/lib/python3.6/site-packages/pyVim/connect.py:847:SmartConnect
exporter_1  | /usr/local/lib/python3.6/site-packages/pyVim/connect.py:726:__FindSupportedVersion
exporter_1  | /usr/local/lib/python3.6/site-packages/pyVim/connect.py:643:__GetServiceVersionDescription
exporter_1  | /usr/local/lib/python3.6/site-packages/pyVim/connect.py:608:__GetElementTree
exporter_1  | /usr/local/lib/python3.6/http/client.py:1262:request
exporter_1  | /usr/local/lib/python3.6/http/client.py:1308:_send_request
exporter_1  | /usr/local/lib/python3.6/http/client.py:1257:endheaders
exporter_1  | /usr/local/lib/python3.6/http/client.py:1036:_send_output
exporter_1  | /usr/local/lib/python3.6/http/client.py:974:send
exporter_1  | /usr/local/lib/python3.6/http/client.py:1415:connect
exporter_1  | /usr/local/lib/python3.6/http/client.py:946:connect
exporter_1  | /usr/local/lib/python3.6/socket.py:704:create_connection
exporter_1  | /usr/local/lib/python3.6/socket.py:745:getaddrinfo
exporter_1  | ]]
exporter_1  | 
exporter_1  | Unhandled error in Deferred:
exporter_1  | 
exporter_1  | Traceback (most recent call last):
exporter_1  |   File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 501, in errback
exporter_1  |     self._startRunCallbacks(fail)
exporter_1  |   File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 568, in _startRunCallbacks
exporter_1  |     self._runCallbacks()
exporter_1  |   File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
exporter_1  |     current.result = callback(current.result, *args, **kw)
exporter_1  |   File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1475, in gotResult
exporter_1  |     _inlineCallbacks(r, g, status)
exporter_1  | --- <exception caught here> ---
exporter_1  |   File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
exporter_1  |     result = result.throwExceptionIntoGenerator(g)
exporter_1  |   File "/usr/local/lib/python3.6/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
exporter_1  |     return g.throw(self.type, self.value, self.tb)
exporter_1  |   File "/usr/local/lib/python3.6/site-packages/vmware_exporter/vmware_exporter.py", line 623, in vm_inventory
exporter_1  |     properties,
exporter_1  |   File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
exporter_1  |     result = result.throwExceptionIntoGenerator(g)
exporter_1  |   File "/usr/local/lib/python3.6/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
exporter_1  |     return g.throw(self.type, self.value, self.tb)
exporter_1  |   File "/usr/local/lib/python3.6/site-packages/vmware_exporter/vmware_exporter.py", line 471, in batch_fetch_properties
exporter_1  |     content = yield self.content
exporter_1  |   File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
exporter_1  |     result = result.throwExceptionIntoGenerator(g)
exporter_1  |   File "/usr/local/lib/python3.6/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
exporter_1  |     return g.throw(self.type, self.value, self.tb)
exporter_1  |   File "/usr/local/lib/python3.6/site-packages/vmware_exporter/vmware_exporter.py", line 461, in content
exporter_1  |     connection = yield self.connection
exporter_1  |   File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
exporter_1  |     result = result.throwExceptionIntoGenerator(g)
exporter_1  |   File "/usr/local/lib/python3.6/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
exporter_1  |     return g.throw(self.type, self.value, self.tb)
exporter_1  |   File "/usr/local/lib/python3.6/site-packages/vmware_exporter/vmware_exporter.py", line 449, in connection
exporter_1  |     sslContext=context,
exporter_1  |   File "/usr/local/lib/python3.6/site-packages/twisted/python/threadpool.py", line 250, in inContext
exporter_1  |     result = inContext.theWork()
exporter_1  |   File "/usr/local/lib/python3.6/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
exporter_1  |     inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
exporter_1  |   File "/usr/local/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
exporter_1  |     return self.currentContext().callWithContext(ctx, func, *args, **kw)
exporter_1  |   File "/usr/local/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
exporter_1  |     return func(*args,**kw)
exporter_1  |   File "/usr/local/lib/python3.6/site-packages/pyVim/connect.py", line 847, in SmartConnect
exporter_1  |     sslContext)
exporter_1  |   File "/usr/local/lib/python3.6/site-packages/pyVim/connect.py", line 726, in __FindSupportedVersion
exporter_1  |     httpProxyPort)
exporter_1  |   File "/usr/local/lib/python3.6/site-packages/pyVim/connect.py", line 643, in __GetServiceVersionDescription
exporter_1  |     httpProxyHost, httpProxyPort)
exporter_1  |   File "/usr/local/lib/python3.6/site-packages/pyVim/connect.py", line 608, in __GetElementTree
exporter_1  |     conn.request("GET", path)
exporter_1  |   File "/usr/local/lib/python3.6/http/client.py", line 1262, in request
exporter_1  |     self._send_request(method, url, body, headers, encode_chunked)
exporter_1  |   File "/usr/local/lib/python3.6/http/client.py", line 1308, in _send_request
exporter_1  |     self.endheaders(body, encode_chunked=encode_chunked)
exporter_1  |   File "/usr/local/lib/python3.6/http/client.py", line 1257, in endheaders
exporter_1  |     self._send_output(message_body, encode_chunked=encode_chunked)
exporter_1  |   File "/usr/local/lib/python3.6/http/client.py", line 1036, in _send_output
exporter_1  |     self.send(msg)
exporter_1  |   File "/usr/local/lib/python3.6/http/client.py", line 974, in send
exporter_1  |     self.connect()
exporter_1  |   File "/usr/local/lib/python3.6/http/client.py", line 1415, in connect
exporter_1  |     super().connect()
exporter_1  |   File "/usr/local/lib/python3.6/http/client.py", line 946, in connect
exporter_1  |     (self.host,self.port), self.timeout, self.source_address)
exporter_1  |   File "/usr/local/lib/python3.6/socket.py", line 704, in create_connection
exporter_1  |     for res in getaddrinfo(host, port, 0, SOCK_STREAM):
exporter_1  |   File "/usr/local/lib/python3.6/socket.py", line 745, in getaddrinfo
exporter_1  |     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
exporter_1  | socket.gaierror: [Errno -3] Try again
```
Need your help please.

**Comment by pryorda** [comment]
This is a get address issue and sounds like its unable to resolve the vcenter address.

**Comment by seyfbarhoumi** [comment]
Thanks it hepled, i just notice that i was using a hostname,, it works perfectly when running a simple container , but when using the image as docker-compose service, swarm service or even as a kuberenetes pod , should use a FQDN instead of hostname.

**Comment by pryorda** [comment]
We use fqdn in kubernetes and it seems to be working great. It sounds like this is resolved now and I'm closing out. Let me know if you still have issues with it.
