### ISSUE TITLE
ERROR:Traceback (most recent call last)

### ISSUE THREAD

**Issue by IamEricqi** [pryorda/vmware_exporter#220]
2020-08-20 07:21:50,767 INFO:Fetched vim.HostSystem inventory (0:00:09.606679)
2020-08-20 07:21:51,024 INFO:Finished collecting metrics from 10.77.188.66
2020-08-20 07:21:51,234 ERROR:Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
StopIteration: [<prometheus_client.core.GaugeMetricFamily object at 0x7f774c6b4320>, <prometheus_client.core.GaugeMetricFamily object at 0x7f774c6b43c8>, <prometheus_client.core.GaugeMetricFamily object at 0x7f774c6b42e8>, <prometheus_client.core.GaugeMetricFamily object at 0x7f774c6b4400>, <prometheus_client.core.GaugeMetricFamily object at 0x7f774c6b42b0>,
 ....... ......

esxi: 
version:5.5 and only read user.

Do you know why?

Thank you!

**Comment by pryorda** [comment]
I would need to see the whole stacktrace.

**Comment by IamEricqi** [comment]
2020-08-28 04:05:54,535 INFO:Finished collecting metrics from 10.77.188.66
2020-08-28 04:05:54,735 ERROR:Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
StopIteration: [<prometheus_client.core.GaugeMetricFamily object at 0x7fafc6a8cef0>, <prometheus_client.core.GaugeMetricFamily object at 0x7fafc83b9e80>, <prometheus_client.core.GaugeMetricFamily object at 0x7fafc83b9ef0>, <prometheus_client.core.GaugeMetricFamily object at 0x7fafc71222e8>, <prometheus_client.core.GaugeMetricFamily object at 0x7fafef1e6550>, <prometheus_client.core.GaugeMetricFamily object at 0x7fafc95a3400>, <prometheus_client.core.GaugeMetricFamily object at 0x7faff01bec50>, <prometheus_client.core.GaugeMetricFamily object at 0x7fafc8de78d0>, <prometheus_client.core.GaugeMetricFamily object at 0x7fafc9288240>, <prometheus_client.core.GaugeMetricFamily object at 0x7fafc847b160>, <prometheus_client.core.GaugeMetricFamily object at 0x7fafdb5b92e8>, <prometheus_client.core.GaugeMetricFamily object at 0x7fafc9930198>, <prometheus_client.core.GaugeMetricFamily object at 0x7fafc702fcf8>, <prometheus_client.core.GaugeMetricFamily object at 0x7fafca10a1d0>, <prometheus_client.core.GaugeMetricFamily object at 0x7fafc69f23c8>, <prometheus_client.core.GaugeMetricFamily object at 0x7fafca6d9fd0>, <prometheus_client.core.GaugeMetricFamily object at 0x7faff0e37e10>, <prometheus_client.core.GaugeMetricFamily object at 0x7fafc9bbc9b0>, <prometheus_client.core.GaugeMetricFamily object at 0x7fafc9e41160>, <prometheus_client.core.GaugeMetricFamily object at 0x7fafc85f8208>, <prometheus_client.core.GaugeMetricFamily object at 0x7fafca168668>, <prometheus_client.core.GaugeMetricFamily object at 0x7fafe0d9f6a0>, <prometheus_client.core.GaugeMetricFamily object at 0x7fafdfca0ef0>, <prometheus_client.core.GaugeMetricFamily object at 0x7fafefb19da0>, <prometheus_client.core.GaugeMetricFamily object at 0x7fafc702cd30>, <prometheus_client.core.GaugeMetricFamily object at 0x7fafc9379be0>, <prometheus_client.core.GaugeMetricFamily object at 0x7fafc89a0940>, <prometheus_client.core.GaugeMetricFamily object at 0x7fafc8591320>, <prometheus_client.core.GaugeMetricFamily object at 0x7fafc9782940>, <prometheus_client.core.GaugeMetricFamily object at 0x7fafc864aa90>, <prometheus_client.core.GaugeMetricFamily object at 0x7fafca035160>, <prometheus_client.core.GaugeMetricFamily object at 0x7fafca035be0>, <prometheus_client.core.GaugeMetricFamily object at 0x7fafc991de10>, <prometheus_client.core.GaugeMetricFamily object at 0x7fafc85f1240>, <prometheus_client.core.GaugeMetricFamily object at 0x7fafd7eb93c8>, <prometheus_client.core.GaugeMetricFamily object at 0x7fafc9361a90>, <prometheus_client.core.GaugeMetricFamily object at 0x7fafd73c36d8>, <prometheus_client.core.GaugeMetricFamily object at 0x7fafd8b62f98>, <prometheus_client.core.GaugeMetricFamily object at 0x7fafd8b62b38>, <prometheus_client.core.GaugeMetricFamily object at 0x7fafdb5f98d0>, <prometheus_client.core.GaugeMetricFamily object at 0x7fafdb5f9438>, <prometheus_client.core.GaugeMetricFamily object at 0x7fafdb5f90b8>, <prometheus_client.core.GaugeMetricFamily object at 0x7fafd87a7748>, <prometheus_client.core.GaugeMetricFamily object at 0x7fafd7419a58>, <prometheus_client.core.GaugeMetricFamily object at 0x7fafd7445860>, <prometheus_client.core.GaugeMetricFamily object at 0x7fafd7ad3f60>, <prometheus_client.core.GaugeMetricFamily object at 0x7fafd7ad3048>, <prometheus_client.core.GaugeMetricFamily object at 0x7fafea5994a8>, <prometheus_client.core.GaugeMetricFamily object at 0x7fafda345b70>, <prometheus_client.core.GaugeMetricFamily object at 0x7fafd7f70048>, <prometheus_client.core.GaugeMetricFamily object at 0x7fafd8895978>, <prometheus_client.core.GaugeMetricFamily object at 0x7fafd7a8cfd0>, <prometheus_client.core.GaugeMetricFamily object at 0x7fafd7a8c080>, <prometheus_client.core.GaugeMetricFamily object at 0x7fafd9edd2e8>, <prometheus_client.core.GaugeMetricFamily object at 0x7fafd989b550>, <prometheus_client.core.GaugeMetricFamily object at 0x7fafd989b6a0>, <prometheus_client.core.GaugeMetricFamily object at 0x7fafd72c90f0>, <prometheus_client.core.GaugeMetricFamily object at 0x7fafd9ca0908>, <prometheus_client.core.GaugeMetricFamily object at 0x7fafc8d954e0>, <prometheus_client.core.GaugeMetricFamily object at 0x7fafe4a982e8>, <prometheus_client.core.GaugeMetricFamily object at 0x7fafd748f550>, <prometheus_client.core.GaugeMetricFamily object at 0x7fafd75a0198>, <prometheus_client.core.GaugeMetricFamily object at 0x7fafd7ea5748>, <prometheus_client.core.GaugeMetricFamily object at 0x7fafd55d8dd8>, <prometheus_client.core.GaugeMetricFamily object at 0x7fafd7a81e10>, <prometheus_client.core.GaugeMetricFamily object at 0x7fafd7a81d30>, <prometheus_client.core.GaugeMetricFamily object at 0x7fafdada4e80>, <prometheus_client.core.GaugeMetricFamily object at 0x7fafd56e1320>, <prometheus_client.core.GaugeMetricFamily object at 0x7fafd56e19b0>, <prometheus_client.core.GaugeMetricFamily object at 0x7fafd5746da0>, <prometheus_client.core.GaugeMetricFamily object at 0x7fafd5746f28>, <prometheus_client.core.GaugeMetricFamily object at 0x7fafd5115be0>, <prometheus_client.core.GaugeMetricFamily object at 0x7fafd5115400>, <prometheus_client.core.GaugeMetricFamily object at 0x7fafd5115278>, <prometheus_client.core.GaugeMetricFamily object at 0x7fafd51154a8>, <prometheus_client.core.GaugeMetricFamily object at 0x7fafd5181b70>, <prometheus_client.core.GaugeMetricFamily object at 0x7fafd54d7e10>, <prometheus_client.core.GaugeMetricFamily object at 0x7fafd54d7c50>, <prometheus_client.core.GaugeMetricFamily object at 0x7fafd7560438>, <prometheus_client.core.GaugeMetricFamily object at 0x7fafd7560668>, <prometheus_client.core.GaugeMetricFamily object at 0x7fafd7b1b748>, <prometheus_client.core.GaugeMetricFamily object at 0x7fafd753c898>]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/vmware_exporter/vmware_exporter.py", line 1012, in _async_render_GET
    yield self.generate_latest_metrics(request)
  File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/usr/local/lib/python3.6/site-packages/vmware_exporter/vmware_exporter.py", line 1061, in generate_latest_metrics
    request.finish()
  File "/usr/local/lib/python3.6/site-packages/twisted/web/server.py", line 286, in finish
    return http.Request.finish(self)
  File "/usr/local/lib/python3.6/site-packages/twisted/web/http.py", line 1080, in finish
    "Request.finish called on a request after its connection was lost; "
RuntimeError: Request.finish called on a request after its connection was lost; use Request.notifyFinish to keep track of this.

2020-08-28 04:05:54,738 INFO:Finished collecting metrics from 10.77.188.66
2020-08-28 04:05:54,929 ERROR:Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
StopIteration

... ...
repeat again

**Comment by pryorda** [comment]
It seems like something is resetting the connection in the middle of a collect. I would start there.

**Comment by pryorda** [comment]
Closing due to inactivity. Please reopen if you still see the issue with 0.13.1.

**Comment by priyadramu** [comment]
@IamEricqi Were you able to resolve this?  I'm facing the same issue in the version 0.13.2.
