### ISSUE TITLE
Problem found when latest (v0.13.1) vmware_exporter container runs on CentOS8.2 

### ISSUE THREAD

**Issue by boonchu** [pryorda/vmware_exporter#232]
I use the same docker-compose.yml to spin up on my local macOS and CentOS 8.2 VM.  I got different results from two environments. MacOS with Desktop Docker gave me with good results, CentOS 8 VM thrown the error on vmware_exporter at the starting time.

```
cat /etc/redhat-release
CentOS Linux release 8.2.2004 (Core)
```

How did I setup on vSphere?

* vSphere 7.0
* CentOS 8.2 VM with podman-compose to run container vmware_exporter
* Use instruction from vmware_exporter README to configure the lab environment.
* Container vmware_exporter version 0.13.1

Results from MacOS (docker-compose)

* Metrics are retrievable from vCenter

Results from CentOS 8 (podman-compose)

```
  File "/usr/local/lib/python3.7/xml/etree/ElementTree.py", line 1315, in XML
    parser.feed(text)
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 8, column 37
```

I proved with my pyvim script and run on CentOS. I entered into vmware_exporter container instance to execute the script. Please noted that this script works fine when I ran on MacOS Docker Desktop edition. I tried with single quote or double one. No luck so far.

```
#!/usr/bin/env python

import ssl
from pyVim.connect import SmartConnect

context = ssl.SSLContext(ssl.PROTOCOL_SSLv23)
context.verify_mode = ssl.CERT_NONE
connect = SmartConnect(host='vcenter1.example.com', user='bot@vsphere.local', pwd='xxxx', port=int("443"), sslContext=context)

datacenter = connect.content.rootFolder.childEntity[0]
print(datacenter)
vms = datacenter.vmFolder.childEntity
for i in vms:
   print(i.name)
Disconnect(connect)
```

```
/etc/vmware_exporter # ./test.py
Traceback (most recent call last):
  File "./test.py", line 8, in <module>
    connect = SmartConnect(host='vcenter1.example.com', user='bot@vsphere.local', pwd='xxxx', port=int("443"), sslContext=context)
  File "/usr/local/lib/python3.7/site-packages/pyVim/connect.py", line 847, in SmartConnect
    sslContext)
  File "/usr/local/lib/python3.7/site-packages/pyVim/connect.py", line 726, in __FindSupportedVersion
    httpProxyPort)
  File "/usr/local/lib/python3.7/site-packages/pyVim/connect.py", line 643, in __GetServiceVersionDescription
    httpProxyHost, httpProxyPort)
  File "/usr/local/lib/python3.7/site-packages/pyVim/connect.py", line 612, in __GetElementTree
    tree = ElementTree.fromstring(response.read())
  File "/usr/local/lib/python3.7/xml/etree/ElementTree.py", line 1315, in XML
    parser.feed(text)
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 8, column 37
```

Not sure what going on.  Please helps.

**Comment by boonchu** [comment]
It works on Fedora OS 32. 

```
[root@cow2 monitoring]# cat /etc/redhat-release
Fedora release 32 (Thirty Two)
[root@cow2 monitoring]# podman -v
podman version 2.1.1
```

Compared to CentOS 8.2

```
[bigchoo@cow3 ~]$ cat /etc/centos-release
CentOS Linux release 8.2.2004 (Core)
[bigchoo@cow3 ~]$ podman -v
podman version 1.6.4
```

**Comment by boonchu** [comment]
Currently I am not going to take any efforts to troubleshoot since I am working on something else. If someone bump into this case, please reopen this ticket or create new ticket though.
