### ISSUE TITLE
UTF8 Error

### ISSUE THREAD

**Issue by bmeneuvrier** [pryorda/vmware_exporter#24]
Hi,
We have a VM called 'Serveur Modèle'.
During scraping, the following error occurs:
[2018-09-19 08:48:17.842438+00:00] Start collecting vcenter metrics for vcenter
[2018-09-19 08:48:18.163349+00:00] Starting VM performance metric collection
[2018-09-19 08:48:18.172564+00:00] Total Virtual Machines: 79
[2018-09-19 08:48:24.360088+00:00] Finish starting vm performance vm collection
[2018-09-19 08:48:24.360130+00:00] Starting VM snapshot metric collection
[2018-09-19 08:48:25.045333+00:00] Finished VM snapshot metric collection
[2018-09-19 08:48:25.045381+00:00] Stop collecting vcenter metrics for vcenter
[2018-09-19 08:48:25.053014+00:00] [Failure instance: Traceback: <type 'exceptions.UnicodeEncodeError'>: 'ascii' codec can't encode character u'\xe8' in position 11: ordinal not in range(128)
/usr/lib/python2.7/dist-packages/twisted/internet/base.py:1208:mainLoop
/usr/lib/python2.7/dist-packages/twisted/internet/base.py:828:runUntilCurrent
/usr/lib/python2.7/dist-packages/twisted/internet/defer.py:457:callback
/usr/lib/python2.7/dist-packages/twisted/internet/defer.py:565:_startRunCallbacks
--- <exception caught here> ---
/usr/lib/python2.7/dist-packages/twisted/internet/defer.py:651:_runCallbacks
/usr/local/bin/vmware_exporter.py:129:generate_latest_metrics
]
Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1208, in mainLoop
    self.runUntilCurrent()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 828, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 457, in callback
    self._startRunCallbacks(result)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 565, in _startRunCallbacks
    self._runCallbacks()
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 651, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/usr/local/bin/vmware_exporter.py", line 129, in generate_latest_metrics
    for k, v in sorted(labels.items())]))
exceptions.UnicodeEncodeError: 'ascii' codec can't encode character u'\xe8' in position 11: ordinal not in range(128)

To fix this issue, I did the following modifications in vmware_exporter.py:
line 128:   k, v.replace('\\', r'\\').replace('\n', r'\n').replace('"', r'\"').encode('utf-8'))
line 139:   request.write(''.join(output))

I don't know if it's the cleanest way to fix the problem, but it works.

**Comment by pryorda** [comment]
@bmeneuvrier Can you try doing the encode before replace and after v. Once you have that done and tested it, Can you create PR?

**Comment by pryorda** [comment]
Closing for inactivity.
