### ISSUE TITLE
Error during Metric collection

### ISSUE THREAD

**Issue by hossman-12** [pryorda/vmware_exporter#243]
I'm running version 0.13.2  on Cent 7 using Python 3.8.7 and when I request data I see the following

2021-02-12 14:06:45,433 INFO:Starting web server on port 9272
2021-02-12 14:07:08,802 INFO:Start collecting metrics from XXXXXXX
2021-02-12 14:07:08,802 INFO:Starting vm metrics collection
2021-02-12 14:07:08,802 INFO:Fetching vim.VirtualMachine inventory
2021-02-12 14:07:08,805 INFO:Retrieving service instance content
2021-02-12 14:07:08,807 INFO:Fetching tags
2021-02-12 14:07:08,810 INFO:START: _vmware_get_vm_perf_manager_metrics
2021-02-12 14:07:08,810 INFO:Fetching vim.Datastore inventory
2021-02-12 14:07:08,811 INFO:Starting host metrics collection
2021-02-12 14:07:08,811 INFO:Fetching vim.HostSystem inventory
2021-02-12 14:07:08,812 INFO:START: _vmware_get_host_perf_manager_metrics
2021-02-12 14:07:08,971 INFO:Retrieved service instance content
2021-02-12 14:07:10,191 INFO:Fetched tags (0:00:01.383570)
2021-02-12 14:07:10,407 INFO:Fetched vim.Datastore inventory (0:00:01.596961)
2021-02-12 14:07:12,131 INFO:Fetched vim.VirtualMachine inventory (0:00:03.328853)
Unhandled error in Deferred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "vmware_exporter.py", line 1336, in _vmware_get_vm_perf_manager_metrics
    self.updateMetricsLabelNames(vm_metrics, ['vm_perf'])
  File "/usr/local/lib/python3.8/site-packages/twisted/internet/defer.py", line 1613, in unwindGenerator
    return _cancellableInlineCallbacks(gen)
  File "/usr/local/lib/python3.8/site-packages/twisted/internet/defer.py", line 1529, in _cancellableInlineCallbacks
    _inlineCallbacks(None, g, status)
--- <exception caught here> ---
  File "/usr/local/lib/python3.8/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "vmware_exporter.py", line 1152, in updateMetricsLabelNames
    metric._labelnames += customAttributesLabelNames
builtins.TypeError: can only concatenate tuple (not "list") to tuple

2021-02-12 14:07:24,562 INFO:Fetched vim.HostSystem inventory (0:00:15.750971)
Unhandled error in Deferred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "vmware_exporter.py", line 1423, in _vmware_get_host_perf_manager_metrics
    self.updateMetricsLabelNames(host_metrics, ['host_perf'])
  File "/usr/local/lib/python3.8/site-packages/twisted/internet/defer.py", line 1613, in unwindGenerator
    return _cancellableInlineCallbacks(gen)
  File "/usr/local/lib/python3.8/site-packages/twisted/internet/defer.py", line 1529, in _cancellableInlineCallbacks
    _inlineCallbacks(None, g, status)
--- <exception caught here> ---
  File "/usr/local/lib/python3.8/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "vmware_exporter.py", line 1152, in updateMetricsLabelNames
    metric._labelnames += customAttributesLabelNames
builtins.TypeError: can only concatenate tuple (not "list") to tuple

Unhandled error in Deferred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "vmware_exporter.py", line 1186, in _vmware_get_datastores
    self.updateMetricsLabelNames(ds_metrics, ['datastores'])
  File "/usr/local/lib/python3.8/site-packages/twisted/internet/defer.py", line 1613, in unwindGenerator
    return _cancellableInlineCallbacks(gen)
  File "/usr/local/lib/python3.8/site-packages/twisted/internet/defer.py", line 1529, in _cancellableInlineCallbacks
    _inlineCallbacks(None, g, status)
--- <exception caught here> ---
  File "/usr/local/lib/python3.8/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "vmware_exporter.py", line 1152, in updateMetricsLabelNames
    metric._labelnames += customAttributesLabelNames
builtins.TypeError: can only concatenate tuple (not "list") to tuple

Unhandled error in Deferred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "vmware_exporter.py", line 1477, in _vmware_get_vms
    self.updateMetricsLabelNames(metrics, ['vms', 'vmguests', 'snapshots'])
  File "/usr/local/lib/python3.8/site-packages/twisted/internet/defer.py", line 1613, in unwindGenerator
    return _cancellableInlineCallbacks(gen)
  File "/usr/local/lib/python3.8/site-packages/twisted/internet/defer.py", line 1529, in _cancellableInlineCallbacks
    _inlineCallbacks(None, g, status)
--- <exception caught here> ---
  File "/usr/local/lib/python3.8/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "vmware_exporter.py", line 1152, in updateMetricsLabelNames
    metric._labelnames += customAttributesLabelNames
builtins.TypeError: can only concatenate tuple (not "list") to tuple

2021-02-12 14:07:33,990 INFO:Finished vm metrics collection
2021-02-12 14:07:34,029 INFO:FIN: _vmware_get_vm_perf_manager_metrics
Unhandled error in Deferred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "vmware_exporter.py", line 1612, in _vmware_get_hosts
    self.updateMetricsLabelNames(host_metrics, ['hosts'])
  File "/usr/local/lib/python3.8/site-packages/twisted/internet/defer.py", line 1613, in unwindGenerator
    return _cancellableInlineCallbacks(gen)
  File "/usr/local/lib/python3.8/site-packages/twisted/internet/defer.py", line 1529, in _cancellableInlineCallbacks
    _inlineCallbacks(None, g, status)
--- <exception caught here> ---
  File "/usr/local/lib/python3.8/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "vmware_exporter.py", line 1152, in updateMetricsLabelNames
    metric._labelnames += customAttributesLabelNames
builtins.TypeError: can only concatenate tuple (not "list") to tuple

2021-02-12 14:07:34,039 INFO:Finished host metrics collection
2021-02-12 14:07:34,052 INFO:FIN: _vmware_get_host_perf_manager_metrics
2021-02-12 14:07:34,069 INFO:Finished collecting metrics from XXXXXXXXXX

I do get results

**Comment by pryorda** [comment]
What vmware version

**Comment by hossman-12** [comment]
vCenters that I've tried  are 6.7u3 and 7.0u1,  ESXi Hosts are 6.7u3

**Comment by gorkemozlu** [comment]
Same here.

2021-06-30 12:30:28,490 INFO:Start collecting metrics from miatsvcv01.migros.local
2021-06-30 12:30:28,490 INFO:Starting vm metrics collection
2021-06-30 12:30:28,490 INFO:Fetching vim.VirtualMachine inventory
2021-06-30 12:30:28,490 INFO:Retrieving service instance content
2021-06-30 12:30:28,491 INFO:START: _vmware_get_vm_perf_manager_metrics
2021-06-30 12:30:28,491 INFO:Fetching vim.Datastore inventory
2021-06-30 12:30:28,491 INFO:Starting host metrics collection
2021-06-30 12:30:28,491 INFO:Fetching vim.HostSystem inventory
2021-06-30 12:30:28,491 INFO:START: _vmware_get_host_perf_manager_metrics
2021-06-30 12:30:28,659 INFO:Retrieved service instance content
2021-06-30 12:30:29,196 INFO:Fetched vim.Datastore inventory (0:00:00.705046)
Unhandled error in Deferred:

Traceback (most recent call last):
--- <exception caught here> ---
  File "/usr/local/lib/python3.7/site-packages/vmware_exporter/vmware_exporter.py", line 1441, in _vmware_get_host_perf_manager_metrics
    self.host_labels,
  File "/usr/local/lib/python3.7/site-packages/vmware_exporter/defer.py", line 99, in parallelize
    results = yield defer.DeferredList(args, fireOnOneErrback=True)
twisted.internet.defer.FirstError: FirstError[#0, [Failure instance: Traceback: <class 'pyVmomi.VmomiSupport.vmodl.fault.SystemError'>: (vmodl.fault.SystemError) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   msg = 'A general system error occurred: Operation was canceled',
   faultCause = <unset>,
   faultMessage = (vmodl.LocalizableMessage) [],
   reason = 'Operation was canceled'
}
/usr/local/lib/python3.7/threading.py:926:_bootstrap_inner
/usr/local/lib/python3.7/threading.py:870:run
/usr/local/lib/python3.7/site-packages/twisted/_threads/_threadworker.py:46:work
/usr/local/lib/python3.7/site-packages/twisted/_threads/_team.py:190:doWork
--- <exception caught here> ---
/usr/local/lib/python3.7/site-packages/twisted/python/threadpool.py:250:inContext
/usr/local/lib/python3.7/site-packages/twisted/python/threadpool.py:266:<lambda>
/usr/local/lib/python3.7/site-packages/twisted/python/context.py:122:callWithContext
/usr/local/lib/python3.7/site-packages/twisted/python/context.py:85:callWithContext
/usr/local/lib/python3.7/site-packages/pyVmomi/VmomiSupport.py:706:<lambda>
/usr/local/lib/python3.7/site-packages/pyVmomi/VmomiSupport.py:512:_InvokeMethod
/usr/local/lib/python3.7/site-packages/pyVmomi/SoapAdapter.py:1397:InvokeMethod
]]

**Comment by dcorneli** [comment]
Same here

**Comment by pryorda** [comment]
Need to set your timeouts longer on the prometheus end. Closing and let me know if this doesn't help.
