### ISSUE TITLE
Intermittent Metric Collection Failures (Request.finish called on a request after its connection was lost)

### ISSUE THREAD

**Issue by gsperry2011** [pryorda/vmware_exporter#266]
Hello,

I am having an issue where the exporter functions probably 90% of the time but it seems to have some problem where prometheus shows no vmware metrics and the "last scraped time" goes higher than 10 seconds. It always seems to recover itself with no service restarted needed. 

Metrics look like this: 
![image](https://user-images.githubusercontent.com/21208713/115768795-c4e9ed00-a378-11eb-9e61-adbdd0cc5a1e.png)

I am seeing this in my logs when the metrics are failing to collect:

```
Apr 22 12:22:05 vmware_exporter: 2021-04-22 12:22:05,039 INFO:Finished collecting metrics from <vcenter>
Apr 22 12:22:05 vmware_exporter: 2021-04-22 12:22:05,075 ERROR:Traceback (most recent call last):
Apr 22 12:22:05 vmware_exporter: File "/opt/prometheus/pythonexporters/vmware-exporter/lib64/python3.6/site-packages/twisted/internet/defer.py", line 1445, in _inlineCallbacks
Apr 22 12:22:05 vmware_exporter: result = current_context.run(g.send, result)
Apr 22 12:22:05 vmware_exporter: File "/opt/prometheus/pythonexporters/vmware-exporter/lib64/python3.6/site-packages/twisted/internet/defer.py", line 47, in run
Apr 22 12:22:05 vmware_exporter: return f(*args, **kwargs)
Apr 22 12:22:05 vmware_exporter: StopIteration
Apr 22 12:22:05 vmware_exporter: During handling of the above exception, another exception occurred:
Apr 22 12:22:05 vmware_exporter: Traceback (most recent call last):
Apr 22 12:22:05 vmware_exporter: File "/opt/prometheus/pythonexporters/vmware-exporter/lib64/python3.6/site-packages/twisted/internet/defer.py", line 1445, in _inlineCallbacks
Apr 22 12:22:05 vmware_exporter: result = current_context.run(g.send, result)
Apr 22 12:22:05 vmware_exporter: File "/opt/prometheus/pythonexporters/vmware-exporter/lib64/python3.6/site-packages/twisted/internet/defer.py", line 47, in run
Apr 22 12:22:05 vmware_exporter: return f(*args, **kwargs)
Apr 22 12:22:05 vmware_exporter: StopIteration: [<prometheus_client.core.GaugeMetricFamily object at 0x7eff6f8c7400>, <prometheus_client.core.GaugeMetricFamily object at 0x7eff6f8c74a8>, <prometheus_client.core.GaugeMetricFamily object at 0x7eff6f8c7240>, <prometheus_client.core.GaugeMetricFamily object at 0x7eff6f8c7080>, <prometheus_client.core.GaugeMetricFamily object at 0x7eff6f8c71d0>, <prometheus_client.core.GaugeMetricFamily object at 0x7eff6f8c7710>, <prometheus_client.core.GaugeMetricFamily object at 0x7eff6f8c7860>, <prometheus_client.core.GaugeMetricFamily object at 0x7eff6f8c7f60>, <prometheus_client.core.GaugeMetricFamily object at 0x7eff6f8c7b38>, <prometheus_client.core.GaugeMetricFamily object at 0x7eff5f4d9128>, <prometheus_client.core.GaugeMetricFamily object at 0x7eff5f4d9048>, <prometheus_client.core.GaugeMetricFamily object at 0x7eff6f8c7a20>, <prometheus_client.core.GaugeMetricFamily object at 0x7eff6f8c78d0>, <prometheus_client.core.GaugeMetricFamily object at 0x7eff6f8c7128>, <prometheus_client.core.GaugeMetricFamily object at 0x7eff6f8c7780>, <prometheus_client.core.GaugeMetricFamily object at 0x7eff6f8c7048>, <prometheus_client.core.GaugeMetricFamily object at 0x7eff6f8c7d68>, <prometheus_client.core.GaugeMetricFamily object at 0x7eff6f8c70b8>, <prometheus_client.core.GaugeMetricFamily object at 0x7eff6f8c7198>, <prometheus_client.core.GaugeMetricFamily object at 0x7eff6f8c7eb8>, <prometheus_client.core.GaugeMetricFamily object at 0x7eff6f8c77f0>, <prometheus_client.core.GaugeMetricFamily object at 0x7eff6f8c7c50>, <prometheus_client.core.GaugeMetricFamily object at 0x7eff6f8c7cf8>, <prometheus_client.core.GaugeMetricFamily object at 0x7eff6f8c7d30>, <prometheus_client.core.GaugeMetricFamily object at 0x7eff6f8c7fd0>, <prometheus_client.core.GaugeMetricFamily object at 0x7eff6f8c7588>, <prometheus_client.core.GaugeMetricFamily object at 0x7eff5f4d9860>, <prometheus_client.core.GaugeMetricFamily object at 0x7eff5f4d9668>, <prometheus_client.core.GaugeMetricFamily object at 0x7eff5f4d9c88>, <prometheus_client.core.GaugeMetricFamily object at 0x7eff5f4d9e10>, <prometheus_client.core.GaugeMetricFamily object at 0x7eff5f4d98d0>, <prometheus_client.core.GaugeMetricFamily object at 0x7eff5f4d95f8>, <prometheus_client.core.GaugeMetricFamily object at 0x7eff57bbc7f0>, <prometheus_client.core.GaugeMetricFamily object at 0x7eff6c5df828>, <prometheus_client.core.GaugeMetricFamily object at 0x7eff6c5df7b8>, <prometheus_client.core.GaugeMetricFamily object at 0x7eff6c5df940>, <prometheus_client.core.GaugeMetricFamily object at 0x7eff6c5dfeb8>, <prometheus_client.core.GaugeMetricFamily object at 0x7eff6c5df358>, <prometheus_client.core.GaugeMetricFamily object at 0x7eff6c5df860>, <prometheus_client.core.GaugeMetricFamily object at 0x7eff6c5df630>, <prometheus_client.core.GaugeMetricFamily object at 0x7eff6c5dfe80>, <prometheus_client.core.GaugeMetricFamily object at 0x7eff6c5dfa20>, <prometheus_client.core.GaugeMetricFamily object at 0x7eff6c5df5c0>, <prometheus_client.core.GaugeMetricFamily object at 0x7eff6c5df6d8>, <prometheus_client.core.GaugeMetricFamily object at 0x7eff6c5df080>, <prometheus_client.core.GaugeMetricFamily object at 0x7eff6c5df160>, <prometheus_client.core.GaugeMetricFamily object at 0x7eff6c5df518>, <prometheus_client.core.GaugeMetricFamily object at 0x7eff6c5df8d0>, <prometheus_client.core.GaugeMetricFamily object at 0x7eff6c5df978>, <prometheus_client.core.GaugeMetricFamily object at 0x7eff6c5dfcc0>, <prometheus_client.core.GaugeMetricFamily object at 0x7eff6c5df588>, <prometheus_client.core.GaugeMetricFamily object at 0x7eff6c5df470>, <prometheus_client.core.GaugeMetricFamily object at 0x7eff6c5df668>, <prometheus_client.core.GaugeMetricFamily object at 0x7eff6c5dfc18>, <prometheus_client.core.GaugeMetricFamily object at 0x7eff6c5df908>, <prometheus_client.core.GaugeMetricFamily object at 0x7eff6c5df0b8>]
Apr 22 12:22:05 vmware_exporter: During handling of the above exception, another exception occurred:
Apr 22 12:22:05 vmware_exporter: Traceback (most recent call last):
Apr 22 12:22:05 vmware_exporter: File "/opt/prometheus/pythonexporters/vmware-exporter/lib64/python3.6/site-packages/vmware_exporter/vmware_exporter.py", line 1922, in _async_render_GET
Apr 22 12:22:05 vmware_exporter: yield self.generate_latest_metrics(request)
Apr 22 12:22:05 vmware_exporter: File "/opt/prometheus/pythonexporters/vmware-exporter/lib64/python3.6/site-packages/twisted/internet/defer.py", line 1445, in _inlineCallbacks
Apr 22 12:22:05 vmware_exporter: result = current_context.run(g.send, result)
Apr 22 12:22:05 vmware_exporter: File "/opt/prometheus/pythonexporters/vmware-exporter/lib64/python3.6/site-packages/twisted/internet/defer.py", line 47, in run
Apr 22 12:22:05 vmware_exporter: return f(*args, **kwargs)
Apr 22 12:22:05 vmware_exporter: File "/opt/prometheus/pythonexporters/vmware-exporter/lib64/python3.6/site-packages/vmware_exporter/vmware_exporter.py", line 1974, in generate_latest_metrics
Apr 22 12:22:05 vmware_exporter: request.finish()
Apr 22 12:22:05 vmware_exporter: File "/opt/prometheus/pythonexporters/vmware-exporter/lib64/python3.6/site-packages/twisted/web/server.py", line 279, in finish
Apr 22 12:22:05 vmware_exporter: return http.Request.finish(self)
Apr 22 12:22:05 vmware_exporter: File "/opt/prometheus/pythonexporters/vmware-exporter/lib64/python3.6/site-packages/twisted/web/http.py", line 1134, in finish
Apr 22 12:22:05 vmware_exporter: "Request.finish called on a request after its connection was lost; "
Apr 22 12:22:05 vmware_exporter: RuntimeError: Request.finish called on a request after its connection was lost; use Request.notifyFinish to keep track of this.
```

Exporter Info:
OS: RHEL7
```
Python 3.6.8
```

```
Package           Version
----------------- ---------
attrs             20.3.0
Automat           20.2.0
certifi           2020.12.5
cffi              1.14.5
chardet           4.0.0
constantly        15.1.0
cryptography      3.4.7
hyperlink         21.0.0
idna              2.10
incremental       21.3.0
pip               21.0.1
prometheus-client 0.0.19
pyasn1            0.4.8
pyasn1-modules    0.2.8
pycparser         2.20
pytz              2021.1
pyvmomi           7.0.2
PyYAML            5.4.1
requests          2.25.1
service-identity  18.1.0
setuptools        56.0.0
six               1.15.0
Twisted           21.2.0
urllib3           1.26.4
vmware-exporter   0.16.0
zope.interface    5.4.0
```

VMware Info:
```
Version 6.7.0
Build 17712750
```

**Comment by pryorda** [comment]
@gsperry2011 you will need to set the timeout on prometheus' end higher. #206 has the configuration to do this. THis container is just connecting to your vmware stack and is reliant on the performance of that.

**Comment by gsperry2011** [comment]
@pryorda thanks for the guidance! I checked the scrape duration (one vcenter) and it seems like it usually comes back within 10 seconds (at least in the last hour). I'll monitor the duration and tune Prometheus so it doesn't timeout under normal behavior.

![image](https://user-images.githubusercontent.com/21208713/115885916-68d9a400-a41e-11eb-97d7-0e15093aeea1.png)
