### ISSUE TITLE
[BUG] vmware_exporter running error

### ISSUE THREAD

**Issue by ilanni2460** [pryorda/vmware_exporter#300]
vmware_exporter running error

this is  error  log :
`2021-11-15 06:42:16,921 INFO:START: _vmware_get_vm_perf_manager_metrics
2021-11-15 06:42:16,921 INFO:Fetching vim.Datastore inventory
2021-11-15 06:42:16,921 INFO:Starting host metrics collection
2021-11-15 06:42:16,921 INFO:Fetching vim.HostSystem inventory
2021-11-15 06:42:16,922 INFO:START: _vmware_get_host_perf_manager_metrics
2021-11-15 06:42:17,109 INFO:Retrieved service instance content
Unhandled error in Deferred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 701, in errback
    self._startRunCallbacks(fail)
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 764, in _startRunCallbacks
    self._runCallbacks()
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 859, in _runCallbacks
    current.result, *args, **kwargs
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1751, in gotResult
    current_context.run(_inlineCallbacks, r, gen, status)
--- <exception caught here> ---
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1658, in _inlineCallbacks
    cast(Failure, result).throwExceptionIntoGenerator, gen
  File "/usr/local/lib/python3.7/site-packages/twisted/python/failure.py", line 500, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/local/lib/python3.7/site-packages/vmware_exporter/vmware_exporter.py", line 1942, in _async_render_GET
    request.finish()
  File "/usr/local/lib/python3.7/site-packages/twisted/web/server.py", line 279, in finish
    return http.Request.finish(self)
  File "/usr/local/lib/python3.7/site-packages/twisted/web/http.py", line 1132, in finish
    "Request.finish called on a request after its connection was lost; "
builtins.RuntimeError: Request.finish called on a request after its connection was lost; use Request.notifyFinish to keep track of this.

Unhandled error in Deferred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 701, in errback
    self._startRunCallbacks(fail)
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 764, in _startRunCallbacks
    self._runCallbacks()
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 859, in _runCallbacks
    current.result, *args, **kwargs
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1751, in gotResult
    current_context.run(_inlineCallbacks, r, gen, status)
--- <exception caught here> ---
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1658, in _inlineCallbacks
    cast(Failure, result).throwExceptionIntoGenerator, gen
  File "/usr/local/lib/python3.7/site-packages/twisted/python/failure.py", line 500, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/local/lib/python3.7/site-packages/vmware_exporter/vmware_exporter.py", line 1942, in _async_render_GET
    request.finish()
  File "/usr/local/lib/python3.7/site-packages/twisted/web/server.py", line 279, in finish
    return http.Request.finish(self)
  File "/usr/local/lib/python3.7/site-packages/twisted/web/http.py", line 1132, in finish
    "Request.finish called on a request after its connection was lost; "
builtins.RuntimeError: Request.finish called on a request after its connection was lost; use Request.notifyFinish to keep track of this.

2021-11-15 06:42:18,277 INFO:Fetched vim.VirtualMachine inventory (0:00:01.356919)
2021-11-15 06:42:18,296 INFO:Fetched vim.Datastore inventory (0:00:01.374444)
2021-11-15 06:42:19,899 INFO:Fetched vim.HostSystem inventory (0:00:02.977969)
2021-11-15 06:42:21,367 INFO:Finished vm metrics collection
2021-11-15 06:42:21,372 INFO:FIN: _vmware_get_vm_perf_manager_metrics
2021-11-15 06:42:21,423 INFO:Finished host metrics collection
2021-11-15 06:42:21,425 INFO:FIN: _vmware_get_host_perf_manager_metrics
2021-11-15 06:42:21,448 INFO:Finished collecting metrics from vc.ilanni.com
2021-11-15 06:42:46,920 INFO:Start collecting metrics from vc.ilanni.com
2021-11-15 06:42:46,920 INFO:Starting vm metrics collection
2021-11-15 06:42:46,921 INFO:Fetching vim.VirtualMachine inventory
2021-11-15 06:42:46,921 INFO:Retrieving service instance content
`

**Comment by pryorda** [comment]
What is your timeout set too?

**Comment by pryorda** [comment]
Sorry I guess I didnt set this in the read me :: https://github.com/pryorda/vmware_exporter/issues/213

**Comment by ilanni2460** [comment]
@pryorda yes, this is prometheus.yml

`  - job_name: 'vmware_exporter'
    **scrape_interval: 1m
    scrape_timeout: 1m**
    static_configs:
    - targets: ['192.168.1.5:9272']
      labels:
        instance: 'vmware_exporter'
        env: 'shangtang'`


prometheus.yml config scrape_interval:1m   is  ok

**Comment by pryorda** [comment]
You might have to set it longer based on the sizing of the cluster and node.

**Comment by ilanni2460** [comment]
@pryorda yes,tks
