### ISSUE TITLE
fetch metrics error:vmware_exporter.py", line 1942, in _async_render_GET 

### ISSUE THREAD

**Issue by ripmars** [pryorda/vmware_exporter#310]
My vCenter version: 7.0.1 (17005016)
I try both docker or run `vmware_exporter -c /path/to/your/config`,but get the error like:

```
2022-03-03 05:24:50,177 INFO:Fetched vim.VirtualMachine inventory (0:03:57.878555)
2022-03-03 05:24:54,399 INFO:Finished vm metrics collection
2022-03-03 05:24:54,453 INFO:Finished host metrics collection
2022-03-03 05:24:54,458 INFO:FIN: _vmware_get_host_perf_manager_metrics
2022-03-03 05:24:54,459 INFO:Fetched vim.Datastore inventory (0:03:50.164912)
2022-03-03 05:24:54,467 INFO:Start collecting metrics from gzvcsa.gzhc.local
2022-03-03 05:24:54,467 INFO:Starting vm metrics collection
2022-03-03 05:24:54,468 INFO:Fetching vim.VirtualMachine inventory
2022-03-03 05:24:54,469 INFO:Retrieving service instance content
2022-03-03 05:24:54,470 INFO:START: _vmware_get_vm_perf_manager_metrics
2022-03-03 05:24:54,471 INFO:Fetching vim.Datastore inventory
2022-03-03 05:24:54,472 INFO:Starting host metrics collection
2022-03-03 05:24:54,472 INFO:Fetching vim.HostSystem inventory
2022-03-03 05:24:54,473 INFO:START: _vmware_get_host_perf_manager_metrics
2022-03-03 05:24:54,474 INFO:Start collecting metrics from gzvcsa.gzhc.local
2022-03-03 05:24:54,474 INFO:Starting vm metrics collection
2022-03-03 05:24:54,475 INFO:Fetching vim.VirtualMachine inventory
2022-03-03 05:24:54,475 INFO:Retrieving service instance content
2022-03-03 05:24:54,476 INFO:START: _vmware_get_vm_perf_manager_metrics
2022-03-03 05:24:54,477 INFO:Fetching vim.Datastore inventory
2022-03-03 05:24:54,477 INFO:Starting host metrics collection
2022-03-03 05:24:54,478 INFO:Fetching vim.HostSystem inventory
2022-03-03 05:24:54,478 INFO:START: _vmware_get_host_perf_manager_metrics
2022-03-03 05:24:54,515 INFO:Finished vm metrics collection
2022-03-03 05:24:54,566 INFO:Finished host metrics collection
2022-03-03 05:24:54,570 INFO:FIN: _vmware_get_host_perf_manager_metrics
^@2022-03-03 05:24:55,835 INFO:Finished vm metrics collection
2022-03-03 05:24:55,885 INFO:Finished host metrics collection
2022-03-03 05:24:55,889 INFO:FIN: _vmware_get_host_perf_manager_metrics
2022-03-03 05:24:57,918 INFO:Retrieved service instance content
2022-03-03 05:25:15,050 INFO:Retrieved service instance content
2022-03-03 05:25:30,741 INFO:Retrieved service instance content
2022-03-03 05:25:46,013 INFO:Retrieved service instance content
Unhandled error in Deferred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 701, in errback
    self._startRunCallbacks(fail)
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 764, in _startRunCallbacks
    self._runCallbacks()
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 859, in _runCallbacks
    current.result, *args, **kwargs
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1751, in gotResult
    current_context.run(_inlineCallbacks, r, gen, status)
--- <exception caught here> ---
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1658, in _inlineCallbacks
    cast(Failure, result).throwExceptionIntoGenerator, gen
  File "/usr/local/lib/python3.7/site-packages/twisted/python/failure.py", line 500, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/local/lib/python3.7/site-packages/vmware_exporter/vmware_exporter.py", line 1942, in _async_render_GET
    request.finish()
  File "/usr/local/lib/python3.7/site-packages/twisted/web/server.py", line 279, in finish
    return http.Request.finish(self)
  File "/usr/local/lib/python3.7/site-packages/twisted/web/http.py", line 1132, in finish
    "Request.finish called on a request after its connection was lost; "
builtins.RuntimeError: Request.finish called on a request after its connection was lost; use Request.notifyFinish to keep track of this.

Unhandled error in Deferred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 701, in errback
    self._startRunCallbacks(fail)
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 764, in _startRunCallbacks
    self._runCallbacks()
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 859, in _runCallbacks
    current.result, *args, **kwargs
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1751, in gotResult
    current_context.run(_inlineCallbacks, r, gen, status)
--- <exception caught here> ---
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1658, in _inlineCallbacks
    cast(Failure, result).throwExceptionIntoGenerator, gen
  File "/usr/local/lib/python3.7/site-packages/twisted/python/failure.py", line 500, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/local/lib/python3.7/site-packages/vmware_exporter/vmware_exporter.py", line 1942, in _async_render_GET
    request.finish()
  File "/usr/local/lib/python3.7/site-packages/twisted/web/server.py", line 279, in finish
    return http.Request.finish(self)
  File "/usr/local/lib/python3.7/site-packages/twisted/web/http.py", line 1132, in finish
    "Request.finish called on a request after its connection was lost; "
builtins.RuntimeError: Request.finish called on a request after its connection was lost; use Request.notifyFinish to keep track of this.

Unhandled error in Deferred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 701, in errback
    self._startRunCallbacks(fail)
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 764, in _startRunCallbacks
    self._runCallbacks()
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 859, in _runCallbacks
    current.result, *args, **kwargs
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1751, in gotResult
    current_context.run(_inlineCallbacks, r, gen, status)
--- <exception caught here> ---
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1658, in _inlineCallbacks
    cast(Failure, result).throwExceptionIntoGenerator, gen
  File "/usr/local/lib/python3.7/site-packages/twisted/python/failure.py", line 500, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/local/lib/python3.7/site-packages/vmware_exporter/vmware_exporter.py", line 1942, in _async_render_GET
    request.finish()
  File "/usr/local/lib/python3.7/site-packages/twisted/web/server.py", line 279, in finish
    return http.Request.finish(self)
  File "/usr/local/lib/python3.7/site-packages/twisted/web/http.py", line 1132, in finish
    "Request.finish called on a request after its connection was lost; "
builtins.RuntimeError: Request.finish called on a request after its connection was lost; use Request.notifyFinish to keep track of this.
```

Hope to get an answer, thanks

**Comment by ripmars** [comment]
related with #266  and #206 ,I chage my prometheus.yml file to 
```
# my global config
global:
  scrape_interval:     120s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 120s # Evaluate rules every 15 seconds. The default is every 1 minute.
  scrape_timeout: 120s
```
now works ~ Thanks
