### ISSUE TITLE
'AttributeError'>: 'str' object has no attribute 'get'

### ISSUE THREAD

**Issue by DanielWeeber** [pryorda/vmware_exporter#311]
```
Mar  3 15:33:05 grafana vmware_exporter[20584]: 2022-03-03 16:33:05,925 INFO:Start collecting metrics from <host>
Mar  3 15:33:05 grafana vmware_exporter[20584]: 2022-03-03 16:33:05,925 INFO:Starting vm metrics collection
Mar  3 15:33:05 grafana vmware_exporter[20584]: 2022-03-03 16:33:05,926 INFO:Fetching vim.VirtualMachine inventory
Mar  3 15:33:05 grafana vmware_exporter[20584]: 2022-03-03 16:33:05,926 INFO:Retrieving service instance content
Mar  3 15:33:05 grafana vmware_exporter[20584]: 2022-03-03 16:33:05,927 INFO:Fetching tags
Mar  3 15:33:05 grafana vmware_exporter[20584]: 2022-03-03 16:33:05,928 INFO:START: _vmware_get_vm_perf_manager_metrics
Mar  3 15:33:05 grafana vmware_exporter[20584]: 2022-03-03 16:33:05,931 INFO:Fetching vim.Datastore inventory
Mar  3 15:33:05 grafana vmware_exporter[20584]: 2022-03-03 16:33:05,931 INFO:Starting host metrics collection
Mar  3 15:33:05 grafana vmware_exporter[20584]: 2022-03-03 16:33:05,931 INFO:Fetching vim.HostSystem inventory
Mar  3 15:33:05 grafana vmware_exporter[20584]: 2022-03-03 16:33:05,932 INFO:START: _vmware_get_host_perf_manager_metrics
Mar  3 15:33:06 grafana vmware_exporter[20584]: 2022-03-03 16:33:06,124 ERROR:Traceback (most recent call last):
Mar  3 15:33:06 grafana vmware_exporter[20584]:   File "/usr/local/lib/python3.8/dist-packages/vmware_exporter-0.18.2-py3.8.egg/vmware_exporter/vmware_exporter.py", line 1937, in _async_render_GET
Mar  3 15:33:06 grafana vmware_exporter[20584]:     yield self.generate_latest_metrics(request)
Mar  3 15:33:06 grafana vmware_exporter[20584]: twisted.internet.defer.FirstError: FirstError[#0, [Failure instance: Traceback: <class 'twisted.internet.defer.FirstError'>: FirstError[#2, [Failure instance: Traceback: <class 'AttributeError'>: 'str' object has no attribute 'get'
Mar  3 15:33:06 grafana vmware_exporter[20584]: /usr/lib/python3/dist-packages/twisted/internet/defer.py:501:errback
Mar  3 15:33:06 grafana vmware_exporter[20584]: /usr/lib/python3/dist-packages/twisted/internet/defer.py:568:_startRunCallbacks
Mar  3 15:33:06 grafana vmware_exporter[20584]: /usr/lib/python3/dist-packages/twisted/internet/defer.py:654:_runCallbacks
Mar  3 15:33:06 grafana vmware_exporter[20584]: /usr/lib/python3/dist-packages/twisted/internet/defer.py:1475:gotResult
Mar  3 15:33:06 grafana vmware_exporter[20584]: --- <exception caught here> ---
Mar  3 15:33:06 grafana vmware_exporter[20584]: /usr/lib/python3/dist-packages/twisted/internet/defer.py:1416:_inlineCallbacks
Mar  3 15:33:06 grafana vmware_exporter[20584]: /usr/lib/python3/dist-packages/twisted/python/failure.py:491:throwExceptionIntoGenerator
Mar  3 15:33:06 grafana vmware_exporter[20584]: /usr/local/lib/python3.8/dist-packages/vmware_exporter-0.18.2-py3.8.egg/vmware_exporter/vmware_exporter.py:1052:vm_tags
Mar  3 15:33:06 grafana vmware_exporter[20584]: /usr/lib/python3/dist-packages/twisted/internet/defer.py:1418:_inlineCallbacks
Mar  3 15:33:06 grafana vmware_exporter[20584]: /usr/local/lib/python3.8/dist-packages/vmware_exporter-0.18.2-py3.8.egg/vmware_exporter/vmware_exporter.py:551:tags
Mar  3 15:33:06 grafana vmware_exporter[20584]: ]]
Mar  3 15:33:06 grafana vmware_exporter[20584]: --- <exception caught here> ---
Mar  3 15:33:06 grafana vmware_exporter[20584]: /usr/local/lib/python3.8/dist-packages/vmware_exporter-0.18.2-py3.8.egg/vmware_exporter/vmware_exporter.py:1501:_vmware_get_vms
Mar  3 15:33:06 grafana vmware_exporter[20584]: /usr/local/lib/python3.8/dist-packages/vmware_exporter-0.18.2-py3.8.egg/vmware_exporter/defer.py:100:parallelize
Mar  3 15:33:06 grafana vmware_exporter[20584]: ]]
Mar  3 15:33:06 grafana vmware_exporter[20584]: Unhandled error in Deferred:
Mar  3 15:33:06 grafana vmware_exporter[20584]: Traceback (most recent call last):
Mar  3 15:33:06 grafana vmware_exporter[20584]:   File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 501, in errback
Mar  3 15:33:06 grafana vmware_exporter[20584]:     self._startRunCallbacks(fail)
Mar  3 15:33:06 grafana vmware_exporter[20584]:   File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 568, in _startRunCallbacks
Mar  3 15:33:06 grafana vmware_exporter[20584]:     self._runCallbacks()
Mar  3 15:33:06 grafana vmware_exporter[20584]:   File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 654, in _runCallbacks
Mar  3 15:33:06 grafana vmware_exporter[20584]:     current.result = callback(current.result, *args, **kw)
Mar  3 15:33:06 grafana vmware_exporter[20584]:   File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 1475, in gotResult
Mar  3 15:33:06 grafana vmware_exporter[20584]:     _inlineCallbacks(r, g, status)
Mar  3 15:33:06 grafana vmware_exporter[20584]: --- <exception caught here> ---
Mar  3 15:33:06 grafana vmware_exporter[20584]:   File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
Mar  3 15:33:06 grafana vmware_exporter[20584]:     result = result.throwExceptionIntoGenerator(g)
Mar  3 15:33:06 grafana vmware_exporter[20584]:   File "/usr/lib/python3/dist-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
Mar  3 15:33:06 grafana vmware_exporter[20584]:     return g.throw(self.type, self.value, self.tb)
Mar  3 15:33:06 grafana vmware_exporter[20584]:   File "/usr/local/lib/python3.8/dist-packages/vmware_exporter-0.18.2-py3.8.egg/vmware_exporter/vmware_exporter.py", line 1052, in vm_tags
Mar  3 15:33:06 grafana vmware_exporter[20584]:     tags = yield self.tags
Mar  3 15:33:06 grafana vmware_exporter[20584]:   File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
Mar  3 15:33:06 grafana vmware_exporter[20584]:     result = g.send(result)
Mar  3 15:33:06 grafana vmware_exporter[20584]:   File "/usr/local/lib/python3.8/dist-packages/vmware_exporter-0.18.2-py3.8.egg/vmware_exporter/vmware_exporter.py", line 551, in tags
Mar  3 15:33:06 grafana vmware_exporter[20584]:     tagName = tagNames.get(attachedObj.get('tag_id'))
Mar  3 15:33:06 grafana vmware_exporter[20584]: builtins.AttributeError: 'str' object has no attribute 'get'
```

**Comment by adidiborg** [comment]
@DanielWeeber I'm getting same error. Were you able to fix this?

**Comment by DanielWeeber** [comment]
hm no, but I don't remember what the fix was.

This is my current config, maybe it helps you

```yml
  vmware_exporter:
    image: pryorda/vmware_exporter:latest
    environment:
      VSPHERE_USER: "<user>"
      VSPHERE_PASSWORD: "<password>"
      VSPHERE_HOST: "<fqdn of center>"
      VSPHERE_IGNORE_SSL: "true"
      VSPHERE_SPECS_SIZE: 2000
      VSPHERE_FETCH_CUSTOM_ATTRIBUTES: "true"
      VSPHERE_FETCH_TAGS: "true"
      VSPHERE_FETCH_ALARMS: "true"
      VSPHERE_COLLECT_VMS: "true"
      VSPHERE_COLLECT_VMGUESTS: "true"
      VSPHERE_COLLECT_DATASTORES: "true"
      VSPHERE_COLLECT_HOSTS: "true"
      VSPHERE_COLLECT_SNAPSHOTS: "true"
    networks:
      - monitoring-network
    depends_on:
      - prometheus
```

**Comment by thuvh** [comment]
what version of vsphere do you use?

**Comment by bhattanil** [comment]
I am also getting same issue. I am using version 7.0.3
