### ISSUE TITLE
Unhandled error in Deferred

### ISSUE THREAD

**Issue by trippinnik** [pryorda/vmware_exporter#313]
Launched as docker and go to metrics and get this. 

Unhandled error in Deferred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 701, in errback
    self._startRunCallbacks(fail)
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 764, in _startRunCallbacks
    self._runCallbacks()
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 859, in _runCallbacks
    current.result, *args, **kwargs
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1751, in gotResult
    current_context.run(_inlineCallbacks, r, gen, status)
--- <exception caught here> ---
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1658, in _inlineCallbacks
    cast(Failure, result).throwExceptionIntoGenerator, gen
  File "/usr/local/lib/python3.7/site-packages/twisted/python/failure.py", line 500, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/local/lib/python3.7/site-packages/vmware_exporter/vmware_exporter.py", line 709, in host_system_inventory
    properties,
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1658, in _inlineCallbacks
    cast(Failure, result).throwExceptionIntoGenerator, gen
  File "/usr/local/lib/python3.7/site-packages/twisted/python/failure.py", line 500, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/local/lib/python3.7/site-packages/vmware_exporter/vmware_exporter.py", line 602, in batch_fetch_properties
    content = yield self.content
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1661, in _inlineCallbacks
    result = current_context.run(gen.send, result)
  File "/usr/local/lib/python3.7/site-packages/vmware_exporter/vmware_exporter.py", line 594, in content
    connection.RetrieveContent
builtins.AttributeError: 'NoneType' object has no attribute 'RetrieveContent'

**Comment by trippinnik** [comment]
oops see the issue.

**Comment by crockk** [comment]
what was your fix? i'm seeing the same error
