### ISSUE TITLE
[Errno -2] Name does not resolve

### ISSUE THREAD

**Issue by Draxter** [pryorda/vmware_exporter#334]
Hi, I'm running my vmware_exporter v0.18.4 as a docker container and trying to connect it to my VMWare vSphere 6.7 with the following configuration:

```
  vmware-exporter:
    image: pryorda/vmware_exporter:v0.18.4
    container_name: vmware-exporter
    ports:
      - 9272
    environment:
      - VSPHERE_HOST="vsphere.domain.com"
      - VSPHERE_USER="administrator@vsphere.local"
      - VSPHERE_PASSWORD="some-password"
    networks:
      my_network:
    restart: unless-stopped

```

I then test by curling from another container:
`curl http://vmware-exporter:9272/metrics`

But receive: '# Collection failed'

Then I check the logs of the vmware-exporter container:
`docker logs vmware-exporter`
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 734, in errback
    self._startRunCallbacks(fail)
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 797, in _startRunCallbacks
    self._runCallbacks()
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 892, in _runCallbacks
    current.result, *args, **kwargs
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1791, in gotResult
    _inlineCallbacks(r, gen, status, context)
--- <exception caught here> ---
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1693, in _inlineCallbacks
    cast(Failure, result).throwExceptionIntoGenerator, gen
  File "/usr/local/lib/python3.7/site-packages/twisted/python/failure.py", line 518, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/local/lib/python3.7/site-packages/vmware_exporter/vmware_exporter.py", line 709, in host_system_inventory
    properties,
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1693, in _inlineCallbacks
    cast(Failure, result).throwExceptionIntoGenerator, gen
  File "/usr/local/lib/python3.7/site-packages/twisted/python/failure.py", line 518, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/local/lib/python3.7/site-packages/vmware_exporter/vmware_exporter.py", line 602, in batch_fetch_properties
    content = yield self.content
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1693, in _inlineCallbacks
    cast(Failure, result).throwExceptionIntoGenerator, gen
  File "/usr/local/lib/python3.7/site-packages/twisted/python/failure.py", line 518, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/local/lib/python3.7/site-packages/vmware_exporter/vmware_exporter.py", line 592, in content
    connection = yield self.connection
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1693, in _inlineCallbacks
    cast(Failure, result).throwExceptionIntoGenerator, gen
  File "/usr/local/lib/python3.7/site-packages/twisted/python/failure.py", line 518, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/local/lib/python3.7/site-packages/vmware_exporter/vmware_exporter.py", line 580, in connection
    sslContext=context,
  File "/usr/local/lib/python3.7/site-packages/twisted/python/threadpool.py", line 244, in inContext
    result = inContext.theWork()  # type: ignore[attr-defined]
  File "/usr/local/lib/python3.7/site-packages/twisted/python/threadpool.py", line 261, in <lambda>
    ctx, func, *args, **kw
  File "/usr/local/lib/python3.7/site-packages/twisted/python/context.py", line 117, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/local/lib/python3.7/site-packages/twisted/python/context.py", line 82, in callWithContext
    return func(*args, **kw)
  File "/usr/local/lib/python3.7/site-packages/pyVim/connect.py", line 850, in SmartConnect
    sslContext)
  File "/usr/local/lib/python3.7/site-packages/pyVim/connect.py", line 724, in __FindSupportedVersion
    httpProxyPort)
  File "/usr/local/lib/python3.7/site-packages/pyVim/connect.py", line 641, in __GetServiceVersionDescription
    httpProxyHost, httpProxyPort)
  File "/usr/local/lib/python3.7/site-packages/pyVim/connect.py", line 606, in __GetElementTree
    conn.request("GET", path)
  File "/usr/local/lib/python3.7/http/client.py", line 1281, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1327, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1276, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1036, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.7/http/client.py", line 976, in send
    self.connect()
  File "/usr/local/lib/python3.7/http/client.py", line 1443, in connect
    super().connect()
  File "/usr/local/lib/python3.7/http/client.py", line 948, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/local/lib/python3.7/socket.py", line 707, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/local/lib/python3.7/socket.py", line 752, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name does not resolve
```

I thought that it maybe was some DNS issue where is cannot resolve the VSPHERE_HOST value of 'vsphere.domain.com', so I replaced it with the IP address, but unfortunately the result is the same as above. To double check this, I also exec'ed into the container and pinged 'vsphere.domain.com', which resolved correctly.

A bit stuck now, and would appreciate any ideas. Thanks.

**Comment by Draxter** [comment]
Fixed it. I had to remove the quotes from the environmental variable values in the `docker-compose.yml` file. I guess vmware_exporter doesn't like them being passed in as strings. Possible bug?
