### ISSUE TITLE
builtins.AttributeError: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by onlywyn** [pryorda/vmware_exporter#335]
Unhandled error in Deferred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/twisted/internet/defer.py", line 700, in errback
    self._startRunCallbacks(fail)
  File "/usr/local/lib/python3.8/dist-packages/twisted/internet/defer.py", line 763, in _startRunCallbacks
    self._runCallbacks()
  File "/usr/local/lib/python3.8/dist-packages/twisted/internet/defer.py", line 857, in _runCallbacks
    current.result = callback(  # type: ignore[misc]
  File "/usr/local/lib/python3.8/dist-packages/twisted/internet/defer.py", line 1750, in gotResult
    current_context.run(_inlineCallbacks, r, gen, status)
--- <exception caught here> ---
  File "/usr/local/lib/python3.8/dist-packages/twisted/internet/defer.py", line 1656, in _inlineCallbacks
    result = current_context.run(
  File "/usr/local/lib/python3.8/dist-packages/twisted/python/failure.py", line 514, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/local/lib/python3.8/dist-packages/vmware_exporter-0.18.4-py3.8.egg/vmware_exporter/vmware_exporter.py", line 1064, in host_tags
    tags = yield self.tags
  File "/usr/local/lib/python3.8/dist-packages/twisted/internet/defer.py", line 1656, in _inlineCallbacks
    result = current_context.run(
  File "/usr/local/lib/python3.8/dist-packages/twisted/python/failure.py", line 514, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/local/lib/python3.8/dist-packages/vmware_exporter-0.18.4-py3.8.egg/vmware_exporter/vmware_exporter.py", line 539, in tags
    attachedObjs = yield self._attachedObjectsOnTags
  File "/usr/local/lib/python3.8/dist-packages/twisted/internet/defer.py", line 1656, in _inlineCallbacks
    result = current_context.run(
  File "/usr/local/lib/python3.8/dist-packages/twisted/python/failure.py", line 514, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/local/lib/python3.8/dist-packages/vmware_exporter-0.18.4-py3.8.egg/vmware_exporter/vmware_exporter.py", line 488, in _attachedObjectsOnTags
    tagIDs = yield self._tagIDs
  File "/usr/local/lib/python3.8/dist-packages/twisted/internet/defer.py", line 1660, in _inlineCallbacks
    result = current_context.run(gen.send, result)
  File "/usr/local/lib/python3.8/dist-packages/vmware_exporter-0.18.4-py3.8.egg/vmware_exporter/vmware_exporter.py", line 470, in _tagIDs
    session.get,
builtins.AttributeError: 'NoneType' object has no attribute 'get'

**Comment by bhattanil** [comment]
For me it works after making fetch_tags as false. And datastores as false.

**Comment by xaoseric** [comment]
set tags to false, and that should fix it for you.
