### ISSUE TITLE
Docker build fails due to missing requirements

### ISSUE THREAD

**Issue by spaceman83** [pryorda/vmware_exporter#350]
Traceback (most recent call last):
  File "/usr/local/bin/vmware_exporter", line 5, in <module>
    from vmware_exporter.vmware_exporter import main
  File "/usr/local/lib/python3.7/site-packages/vmware_exporter/vmware_exporter.py", line 21, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

adding 
requests
to the end of requirements.txt and rebuilding seems to solve it for me

**Comment by spaceman83** [comment]
I see that this was also proposed as a solution in a pull request https://github.com/pryorda/vmware_exporter/pull/345
