### ISSUE TITLE
RuntimeError: Request.finish called on a request after its connection was lost; use Request.notifyFinish to keep track of this

### ISSUE THREAD

**Issue by priyadramu** [pryorda/vmware_exporter#376]
Getting below error when the vmexporter pod starts and crashes infinitely.
exporter version: 0.13.2

```
2023-07-11 14:38:28,290 INFO:Starting web server on port 9272
2023-07-11 14:38:28,842 INFO:Service is UP
2023-07-11 14:38:31,269 INFO:Service is UP
2023-07-11 14:38:41,269 INFO:Service is UP
2023-07-11 14:38:46,276 INFO:Start collecting metrics from devshvc.tstsh.domain.com
2023-07-11 14:38:46,276 INFO:Starting vm metrics collection
2023-07-11 14:38:46,276 INFO:Fetching vim.VirtualMachine inventory
2023-07-11 14:38:46,278 INFO:Retrieving service instance content
2023-07-11 14:38:46,281 INFO:Fetching tags
2023-07-11 14:38:46,282 INFO:START: _vmware_get_vm_perf_manager_metrics
2023-07-11 14:38:46,285 INFO:Fetching vim.Datastore inventory
2023-07-11 14:38:46,287 INFO:Starting host metrics collection
2023-07-11 14:38:46,287 INFO:Fetching vim.HostSystem inventory
2023-07-11 14:38:46,288 INFO:START: _vmware_get_host_perf_manager_metrics
2023-07-11 14:38:46,639 INFO:Retrieved service instance content
2023-07-11 14:38:47,859 INFO:Fetched tags (0:00:01.577650)
2023-07-11 14:38:51,301 INFO:Service is UP
2023-07-11 14:38:54,932 INFO:Fetched vim.Datastore inventory (0:00:08.646276)
2023-07-11 14:38:56,721 INFO:Fetched vim.HostSystem inventory (0:00:10.434461)
2023-07-11 14:38:58,807 INFO:Fetched vim.VirtualMachine inventory (0:00:12.530280)
2023-07-11 14:39:00,299 INFO:Finished vm metrics collection
2023-07-11 14:39:00,302 INFO:Finished host metrics collection
2023-07-11 14:39:00,308 INFO:FIN: _vmware_get_host_perf_manager_metrics
2023-07-11 14:39:01,290 INFO:Service is UP
2023-07-11 14:39:01,313 INFO:Service is UP
2023-07-11 14:39:04,323 INFO:FIN: _vmware_get_vm_perf_manager_metrics
2023-07-11 14:39:04,344 INFO:Finished collecting metrics from devshvc.tstsh.domain.com
2023-07-11 14:39:04,990 ERROR:Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
StopIteration: [<prometheus_client.core.GaugeMetricFamily object at 0x7f342e3ef5d0>, <prometheus_client.core.GaugeMetricFamily object at 0x7f342e3ef610>, <prometheus_client.core.GaugeMetricFamily object at 0x7f342e3ef650>, <prometheus_client.core.GaugeMetricFamily object at 0x7f342e3ef690>, <prometheus_client.core.GaugeMetricFamily object at 0x7f342e3ef6d0>, <prometheus_client.core.GaugeMetricFamily object at 0x7f342e3ef710>, <prometheus_client.core.GaugeMetricFamily object at 0x7f342e3fd090>, <prometheus_client.core.GaugeMetricFamily object at 0x7f342e3fd0d0>, <prometheus_client.core.GaugeMetricFamily object at 0x7f342e3ef750>, <prometheus_client.core.GaugeMetricFamily object at 0x7f342e3ef790>, <prometheus_client.core.GaugeMetricFamily object at 0x7f342e3ef7d0>, <prometheus_client.core.GaugeMetricFamily object at 0x7f342e3ef810>, <prometheus_client.core.GaugeMetricFamily object at 0x7f342e3ef850>, <prometheus_client.core.GaugeMetricFamily object at 0x7f342e3ef910>, <prometheus_client.core.GaugeMetricFamily object at 0x7f342e3ef950>, <prometheus_client.core.GaugeMetricFamily object at 0x7f342e3ef990>, <prometheus_client.core.GaugeMetricFamily object at 0x7f342e3ef9d0>, <prometheus_client.core.GaugeMetricFamily object at 0x7f342e3efa10>, <prometheus_client.core.GaugeMetricFamily object at 0x7f342e3efa50>, <prometheus_client.core.GaugeMetricFamily object at 0x7f342e3efa90>, <prometheus_client.core.GaugeMetricFamily object at 0x7f342e3efad0>, <prometheus_client.core.GaugeMetricFamily object at 0x7f342e3efb10>, <prometheus_client.core.GaugeMetricFamily object at 0x7f342e3efed0>, <prometheus_client.core.GaugeMetricFamily object at 0x7f342e3eff10>, <prometheus_client.core.GaugeMetricFamily object at 0x7f342e3efb50>, <prometheus_client.core.GaugeMetricFamily object at 0x7f342e3efb90>, <prometheus_client.core.GaugeMetricFamily object at 0x7f342e3efbd0>, <prometheus_client.core.GaugeMetricFamily object at 0x7f342e3efc10>, <prometheus_client.core.GaugeMetricFamily object at 0x7f342e3efc50>, <prometheus_client.core.GaugeMetricFamily object at 0x7f342e3efc90>, <prometheus_client.core.GaugeMetricFamily object at 0x7f342e3efcd0>, <prometheus_client.core.GaugeMetricFamily object at 0x7f342e3efd10>, <prometheus_client.core.GaugeMetricFamily object at 0x7f342e3efd50>, <prometheus_client.core.GaugeMetricFamily object at 0x7f342e3efd90>, <prometheus_client.core.GaugeMetricFamily object at 0x7f342e3efdd0>, <prometheus_client.core.GaugeMetricFamily object at 0x7f342e3efe10>, <prometheus_client.core.GaugeMetricFamily object at 0x7f342e3efe50>, <prometheus_client.core.GaugeMetricFamily object at 0x7f342e3efe90>, <prometheus_client.core.GaugeMetricFamily object at 0x7f342e3ef890>, <prometheus_client.core.GaugeMetricFamily object at 0x7f342e3ef8d0>, <prometheus_client.core.GaugeMetricFamily object at 0x7f342e032710>, <prometheus_client.core.GaugeMetricFamily object at 0x7f342e032850>, <prometheus_client.core.GaugeMetricFamily object at 0x7f342e032dd0>, <prometheus_client.core.GaugeMetricFamily object at 0x7f342e032210>, <prometheus_client.core.GaugeMetricFamily object at 0x7f342e032550>, <prometheus_client.core.GaugeMetricFamily object at 0x7f342e0326d0>, <prometheus_client.core.GaugeMetricFamily object at 0x7f342e032790>, <prometheus_client.core.GaugeMetricFamily object at 0x7f342e032610>, <prometheus_client.core.GaugeMetricFamily object at 0x7f342e032a10>, <prometheus_client.core.GaugeMetricFamily object at 0x7f342e032750>, <prometheus_client.core.GaugeMetricFamily object at 0x7f342dbc5250>, <prometheus_client.core.GaugeMetricFamily object at 0x7f342dbc5110>, <prometheus_client.core.GaugeMetricFamily object at 0x7f342dbc5f90>, <prometheus_client.core.GaugeMetricFamily object at 0x7f342dbc5e50>, <prometheus_client.core.GaugeMetricFamily object at 0x7f342dbc5cd0>, <prometheus_client.core.GaugeMetricFamily object at 0x7f342dbc5610>, <prometheus_client.core.GaugeMetricFamily object at 0x7f342dbc5c10>, <prometheus_client.core.GaugeMetricFamily object at 0x7f342dbc5f50>, <prometheus_client.core.GaugeMetricFamily object at 0x7f342dbc5910>, <prometheus_client.core.GaugeMetricFamily object at 0x7f342dbc5710>, <prometheus_client.core.GaugeMetricFamily object at 0x7f342dbc5690>, <prometheus_client.core.GaugeMetricFamily object at 0x7f342dbc5790>, <prometheus_client.core.GaugeMetricFamily object at 0x7f342dbc5ad0>, <prometheus_client.core.GaugeMetricFamily object at 0x7f342dbc5b90>, <prometheus_client.core.GaugeMetricFamily object at 0x7f342dbd0690>, <prometheus_client.core.GaugeMetricFamily object at 0x7f342dbd0c10>, <prometheus_client.core.GaugeMetricFamily object at 0x7f342dbd0550>, <prometheus_client.core.GaugeMetricFamily object at 0x7f342dbd0990>, <prometheus_client.core.GaugeMetricFamily object at 0x7f342dbd0450>, <prometheus_client.core.GaugeMetricFamily object at 0x7f342dbd0d10>, <prometheus_client.core.GaugeMetricFamily object at 0x7f342dbd0110>, <prometheus_client.core.GaugeMetricFamily object at 0x7f342dbd0dd0>, <prometheus_client.core.GaugeMetricFamily object at 0x7f342dbd0d50>, <prometheus_client.core.GaugeMetricFamily object at 0x7f342dbd00d0>, <prometheus_client.core.GaugeMetricFamily object at 0x7f342dbd03d0>, <prometheus_client.core.GaugeMetricFamily object at 0x7f342dbd0810>, <prometheus_client.core.GaugeMetricFamily object at 0x7f342dbd0150>, <prometheus_client.core.GaugeMetricFamily object at 0x7f342dbd06d0>, <prometheus_client.core.GaugeMetricFamily object at 0x7f342dbd0f10>, <prometheus_client.core.GaugeMetricFamily object at 0x7f342df12d90>, <prometheus_client.core.GaugeMetricFamily object at 0x7f342db18a50>, <prometheus_client.core.GaugeMetricFamily object at 0x7f342db18310>, <prometheus_client.core.GaugeMetricFamily object at 0x7f342db18050>, <prometheus_client.core.GaugeMetricFamily object at 0x7f342db18d90>, <prometheus_client.core.GaugeMetricFamily object at 0x7f342db18490>, <prometheus_client.core.GaugeMetricFamily object at 0x7f342db18e90>, <prometheus_client.core.GaugeMetricFamily object at 0x7f342db18550>, <prometheus_client.core.GaugeMetricFamily object at 0x7f342db18f90>]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/vmware_exporter/vmware_exporter.py", line 1840, in _async_render_GET
    yield self.generate_latest_metrics(request)
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/usr/local/lib/python3.7/site-packages/vmware_exporter/vmware_exporter.py", line 1892, in generate_latest_metrics
    request.finish()
  File "/usr/local/lib/python3.7/site-packages/twisted/web/server.py", line 286, in finish
    return http.Request.finish(self)
  File "/usr/local/lib/python3.7/site-packages/twisted/web/http.py", line 1080, in finish
    "Request.finish called on a request after its connection was lost; "
RuntimeError: Request.finish called on a request after its connection was lost; use Request.notifyFinish to keep track of this.

2023-07-11 14:39:11,269 INFO:Service is UP
2023-07-11 14:39:11,270 INFO:Service is UP
2023-07-11 14:39:16,277 INFO:Start collecting metrics from devshvc.tstsh.domain.com
2023-07-11 14:39:16,277 INFO:Starting vm metrics collection
2023-07-11 14:39:16,277 INFO:Fetching vim.VirtualMachine inventory
2023-07-11 14:39:16,277 INFO:Retrieving service instance content
2023-07-11 14:39:16,278 INFO:Fetching tags
2023-07-11 14:39:16,279 INFO:START: _vmware_get_vm_perf_manager_metrics
2023-07-11 14:39:16,282 INFO:Fetching vim.Datastore inventory
2023-07-11 14:39:16,283 INFO:Starting host metrics collection
2023-07-11 14:39:16,283 INFO:Fetching vim.HostSystem inventory
2023-07-11 14:39:16,283 INFO:START: _vmware_get_host_perf_manager_metrics
2023-07-11 14:39:16,652 INFO:Retrieved service instance content
Unhandled error in Deferred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 501, in errback
    self._startRunCallbacks(fail)
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 568, in _startRunCallbacks
    self._runCallbacks()
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1475, in gotResult
    _inlineCallbacks(r, g, status)
--- <exception caught here> ---
  File "/usr/local/lib/python3.7/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/local/lib/python3.7/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/local/lib/python3.7/site-packages/vmware_exporter/vmware_exporter.py", line 1845, in _async_render_GET
    request.finish()
  File "/usr/local/lib/python3.7/site-packages/twisted/web/server.py", line 286, in finish
    return http.Request.finish(self)
  File "/usr/local/lib/python3.7/site-packages/twisted/web/http.py", line 1080, in finish
    "Request.finish called on a request after its connection was lost; "
builtins.RuntimeError: Request.finish called on a request after its connection was lost; use Request.notifyFinish to keep track of this.
```
Also tried setting the scrape timeout to 240s

```
  podMetricsEndpoints:
  - interval: 240s
    path: /metrics
    port: http
    scheme: http
    scrapeTimeout: 240s
```

**Comment by pryorda** [comment]
It still looks like your timeouts are not set correctly or its taking to long to gather metrics.
