### ISSUE TITLE
Failure instance: Traceback: <class 'KeyError'>: 'summary.config.numCpu'

### ISSUE THREAD

**Issue by dannyk81** [pryorda/vmware_exporter#46]
Started hitting this in one of my environments:
```
Dec 27 15:01:58 prometheus-01 docker-vmware-exporter[6744]: [2018-12-27 15:01:58.129410+00:00] Start collecting metrics from <vcenter>
Dec 27 15:01:58 prometheus-01 docker-vmware-exporter[6744]: [2018-12-27 15:01:58.213902+00:00] Starting inventory collection
Dec 27 15:01:58 prometheus-01 docker-vmware-exporter[6744]: [2018-12-27 15:01:58.832281+00:00] Finished inventory collection
Dec 27 15:01:58 prometheus-01 docker-vmware-exporter[6744]: [2018-12-27 15:01:58.832866+00:00] Starting datastore metrics collection
Dec 27 15:01:58 prometheus-01 docker-vmware-exporter[6744]: [2018-12-27 15:01:58.833736+00:00] Starting host metrics collection
Dec 27 15:01:58 prometheus-01 docker-vmware-exporter[6744]: [2018-12-27 15:01:58.834292+00:00] Starting VM metrics collection
Dec 27 15:01:58 prometheus-01 docker-vmware-exporter[6744]: [2018-12-27 15:01:58.875157+00:00] Finished datastore metrics collection
Dec 27 15:01:58 prometheus-01 docker-vmware-exporter[6744]: [2018-12-27 15:01:58.884837+00:00] Finished host metrics collection
Dec 27 15:01:59 prometheus-01 docker-vmware-exporter[6744]: [2018-12-27 15:01:59.011146+00:00] [Failure instance: Traceback: <class 'KeyError'>: 'summary.config.numCpu'
Dec 27 15:01:59 prometheus-01 docker-vmware-exporter[6744]: /usr/local/lib/python3.6/site-packages/twisted/internet/base.py:1276:mainLoop
Dec 27 15:01:59 prometheus-01 docker-vmware-exporter[6744]: /usr/local/lib/python3.6/site-packages/twisted/internet/base.py:902:runUntilCurrent
Dec 27 15:01:59 prometheus-01 docker-vmware-exporter[6744]: /usr/local/lib/python3.6/site-packages/twisted/internet/defer.py:460:callback
Dec 27 15:01:59 prometheus-01 docker-vmware-exporter[6744]: /usr/local/lib/python3.6/site-packages/twisted/internet/defer.py:568:_startRunCallbacks
Dec 27 15:01:59 prometheus-01 docker-vmware-exporter[6744]: --- <exception caught here> ---
Dec 27 15:01:59 prometheus-01 docker-vmware-exporter[6744]: /usr/local/lib/python3.6/site-packages/twisted/internet/defer.py:654:_runCallbacks
Dec 27 15:01:59 prometheus-01 docker-vmware-exporter[6744]: /usr/local/lib/python3.6/site-packages/vmware_exporter/vmware_exporter.py:687:generate_latest_metrics
Dec 27 15:01:59 prometheus-01 docker-vmware-exporter[6744]: /usr/local/lib/python3.6/site-packages/prometheus_client/exposition.py:63:generate_latest
Dec 27 15:01:59 prometheus-01 docker-vmware-exporter[6744]: /usr/local/lib/python3.6/site-packages/prometheus_client/core.py:97:collect
Dec 27 15:01:59 prometheus-01 docker-vmware-exporter[6744]: /usr/local/lib/python3.6/site-packages/vmware_exporter/vmware_exporter.py:216:collect
Dec 27 15:01:59 prometheus-01 docker-vmware-exporter[6744]: /usr/local/lib/python3.6/site-packages/vmware_exporter/vmware_exporter.py:442:_vmware_get_vms
Dec 27 15:01:59 prometheus-01 docker-vmware-exporter[6744]: ]
Dec 27 15:01:59 prometheus-01 docker-vmware-exporter[6744]: Traceback (most recent call last):
Dec 27 15:01:59 prometheus-01 docker-vmware-exporter[6744]: File "/usr/local/lib/python3.6/site-packages/twisted/internet/base.py", line 1276, in mainLoop
Dec 27 15:01:59 prometheus-01 docker-vmware-exporter[6744]: self.runUntilCurrent()
Dec 27 15:01:59 prometheus-01 docker-vmware-exporter[6744]: File "/usr/local/lib/python3.6/site-packages/twisted/internet/base.py", line 902, in runUntilCurrent
Dec 27 15:01:59 prometheus-01 docker-vmware-exporter[6744]: call.func(*call.args, **call.kw)
Dec 27 15:01:59 prometheus-01 docker-vmware-exporter[6744]: File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 460, in callback
Dec 27 15:01:59 prometheus-01 docker-vmware-exporter[6744]: self._startRunCallbacks(result)
Dec 27 15:01:59 prometheus-01 docker-vmware-exporter[6744]: File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 568, in _startRunCallbacks
Dec 27 15:01:59 prometheus-01 docker-vmware-exporter[6744]: self._runCallbacks()
Dec 27 15:01:59 prometheus-01 docker-vmware-exporter[6744]: --- <exception caught here> ---
Dec 27 15:01:59 prometheus-01 docker-vmware-exporter[6744]: File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
Dec 27 15:01:59 prometheus-01 docker-vmware-exporter[6744]: current.result = callback(current.result, *args, **kw)
Dec 27 15:01:59 prometheus-01 docker-vmware-exporter[6744]: File "/usr/local/lib/python3.6/site-packages/vmware_exporter/vmware_exporter.py", line 687, in generate_latest_metrics
Dec 27 15:01:59 prometheus-01 docker-vmware-exporter[6744]: output = generate_latest(registry)
Dec 27 15:01:59 prometheus-01 docker-vmware-exporter[6744]: File "/usr/local/lib/python3.6/site-packages/prometheus_client/exposition.py", line 63, in generate_latest
Dec 27 15:01:59 prometheus-01 docker-vmware-exporter[6744]: for metric in registry.collect():
Dec 27 15:01:59 prometheus-01 docker-vmware-exporter[6744]: File "/usr/local/lib/python3.6/site-packages/prometheus_client/core.py", line 97, in collect
Dec 27 15:01:59 prometheus-01 docker-vmware-exporter[6744]: for metric in collector.collect():
Dec 27 15:01:59 prometheus-01 docker-vmware-exporter[6744]: File "/usr/local/lib/python3.6/site-packages/vmware_exporter/vmware_exporter.py", line 216, in collect
Dec 27 15:01:59 prometheus-01 docker-vmware-exporter[6744]: virtual_machines = self._vmware_get_vms(content, metrics, host_inventory)
Dec 27 15:01:59 prometheus-01 docker-vmware-exporter[6744]: File "/usr/local/lib/python3.6/site-packages/vmware_exporter/vmware_exporter.py", line 442, in _vmware_get_vms
Dec 27 15:01:59 prometheus-01 docker-vmware-exporter[6744]: metrics['vmware_vm_num_cpu'].add_metric(labels, row['summary.config.numCpu'])
Dec 27 15:01:59 prometheus-01 docker-vmware-exporter[6744]: builtins.KeyError: 'summary.config.numCpu'
```

There were no changes in the environment, we are pretty much in a freeze during the holidays, so no new VMs/etc...

**Comment by pryorda** [comment]
I sent more or less this exact same thing in an email but it didn't go through.

**Comment by dannyk81** [comment]
I've modified my `DEBUG` to this as a kind of band-aid, but we should consider what other checks are needed:

```
diff --git a/vmware_exporter/vmware_exporter.py b/vmware_exporter/vmware_exporter.py
index f5a38b2..e59ad92 100755
--- a/vmware_exporter/vmware_exporter.py
+++ b/vmware_exporter/vmware_exporter.py
@@ -430,6 +430,13 @@ class VmwareCollector():
             ]

             if self.collect_only['vms'] is True:
+                # DEBUG
+                if 'summary.config.numCpu' not in row:
+                    log('VM ID: {0}, Name: {1} is missing Number of CPUs, Power state is: {2}, skipping this VM'.format(
+                        moid, row['name'], row['runtime.powerState'])
+                        )
+                    continue
+
                 vm_power_state = 1 if row['runtime.powerState'] == 'poweredOn' else 0
                 metrics['vmware_vm_power_state'].add_metric(labels, vm_power_state)
```

**Comment by Jc2k** [comment]
Along similar lines - There’s a check in my outstanding PR to only do performance metrics for vms that are on.

**Comment by dannyk81** [comment]
I hope to have some time to review your pending PR this year, if not, next year 😄

**Comment by pryorda** [comment]
I'll be reviewing it shortly. So far my initial pass over looks gud!

**Comment by Jc2k** [comment]
@dannyk81 are you happy that v0.4.2 fixes this for your env?

**Comment by dannyk81** [comment]
@jc2k I don't have a chance to validate this now, but considering the safeguards we've added I don't think we'll hit this again.

Thanks! closing this...
