### ISSUE TITLE
Release v0.4.2 : Docker Image : Twisted bug

### ISSUE THREAD

**Issue by toastomatic** [pryorda/vmware_exporter#74]
The v0.4.2 Docker image is using Twisted 18.9.0, which apparently shipped with bug:

https://twistedmatrix.com/trac/ticket/9410

This bug causes failed pulls, while spitting out the following traceback:

```
[2019-01-16 20:45:18.843973+00:00] Starting web server on port 9272
[2019-01-16 20:45:21.586008+00:00] Start collecting metrics from <redacted>
[2019-01-16 20:45:21.697253+00:00] Starting inventory collection
[2019-01-16 20:45:23.220044+00:00] Finished inventory collection
[2019-01-16 20:45:23.220248+00:00] Starting vm metrics collection
[2019-01-16 20:45:23.222406+00:00] Starting host metrics collection
[2019-01-16 20:45:23.352528+00:00] Finished host metrics collection
[2019-01-16 20:45:25.548729+00:00] START: _vmware_get_vm_perf_manager_metrics
[2019-01-16 20:45:26.007193+00:00] START: _vmware_get_vm_perf_manager_metrics: QUERY
[2019-01-16 20:45:30.705149+00:00] FIN: _vmware_get_vm_perf_manager_metrics: QUERY
[2019-01-16 20:45:30.800046+00:00] FIN: _vmware_get_vm_perf_manager_metrics
[2019-01-16 20:45:30.801162+00:00] Finished vm metrics collection
[2019-01-16 20:45:30.834423+00:00] Finished collecting metrics from <redacted>
[2019-01-16 20:45:31.272678+00:00] Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
StopIteration: [<prometheus_client.core.GaugeMetricFamily object at 0x7f69b4d37f98>, <prometheus_client.core.GaugeMetricFamily object at 0x7f69b4d37e80>, <prometheus_client.core.GaugeMetricFamily object at 0x7f69b4d37f28>, <prometheus_client.core.GaugeMetricFamily object at 0x7f69b4d371d0>, <prometheus_client.core.GaugeMetricFamily object at 0x7f69bb6816a0>, <prometheus_client.core.GaugeMetricFamily object at 0x7f69b4e1e2b0>, <prometheus_client.core.GaugeMetricFamily object at 0x7f69b4e1e2e8>, <prometheus_client.core.GaugeMetricFamily object at 0x7f69b4e1e320>, <prometheus_client.core.GaugeMetricFamily object at 0x7f69b4e1e358>, <prometheus_client.core.GaugeMetricFamily object at 0x7f69b4e1e390>, <prometheus_client.core.GaugeMetricFamily object at 0x7f69b4e1e3c8>, <prometheus_client.core.GaugeMetricFamily object at 0x7f69b4e1e400>, <prometheus_client.core.GaugeMetricFamily object at 0x7f69b4e1e438>, <prometheus_client.core.GaugeMetricFamily object at 0x7f69b48cd0b8>, <prometheus_client.core.GaugeMetricFamily object at 0x7f69b48cd2b0>, <prometheus_client.core.GaugeMetricFamily object at 0x7f69b48cd2e8>, <prometheus_client.core.GaugeMetricFamily object at 0x7f69b48cd278>, <prometheus_client.core.GaugeMetricFamily object at 0x7f69b48cd4a8>, <prometheus_client.core.GaugeMetricFamily object at 0x7f69b48cd1d0>, <prometheus_client.core.GaugeMetricFamily object at 0x7f69b48cd198>, <prometheus_client.core.GaugeMetricFamily object at 0x7f69b48cd518>, <prometheus_client.core.GaugeMetricFamily object at 0x7f69b48cdb38>]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/vmware_exporter/vmware_exporter.py", line 686, in _async_render_GET
    yield self.generate_latest_metrics(request)
  File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/usr/local/lib/python3.6/site-packages/vmware_exporter/vmware_exporter.py", line 733, in generate_latest_metrics
    request.write(output)
  File "/usr/local/lib/python3.6/site-packages/twisted/web/server.py", line 238, in write
    http.Request.write(self, data)
  File "/usr/local/lib/python3.6/site-packages/twisted/web/http.py", line 1122, in write
    self.channel.writeHeaders(version, code, reason, headers)
AttributeError: 'NoneType' object has no attribute 'writeHeaders'


[2019-01-16 20:46:14.382899+00:00] Start collecting metrics from <redacted>
[2019-01-16 20:46:14.493398+00:00] Starting inventory collection
[2019-01-16 20:46:16.002297+00:00] Finished inventory collection
[2019-01-16 20:46:16.002345+00:00] Starting vm metrics collection
[2019-01-16 20:46:16.002777+00:00] Starting host metrics collection
[2019-01-16 20:46:16.122627+00:00] Finished host metrics collection
Unhandled error in Deferred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 501, in errback
    self._startRunCallbacks(fail)
  File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 568, in _startRunCallbacks
    self._runCallbacks()
  File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1475, in gotResult
    _inlineCallbacks(r, g, status)
--- <exception caught here> ---
  File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/local/lib/python3.6/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/local/lib/python3.6/site-packages/vmware_exporter/vmware_exporter.py", line 690, in _async_render_GET
    request.write(b'# Collection failed')
  File "/usr/local/lib/python3.6/site-packages/twisted/web/server.py", line 238, in write
    http.Request.write(self, data)
  File "/usr/local/lib/python3.6/site-packages/twisted/web/http.py", line 1137, in write
    self.channel.writeSequence(toChunk(data))
builtins.AttributeError: 'NoneType' object has no attribute 'writeSequence'
```

In order to get around the issue, I dropped Twisted's version down a major release to 17.9.0:

```
$ cat Dockerfile
FROM pryorda/vmware_exporter:v0.4.2

USER root
RUN apk add musl-dev gcc py3-setuptools
RUN pip uninstall -y twisted && \
    pip install twisted==17.9.0
```

Now everything is running happily. 

Below is my config:

```
$ cat config/vmware-exporter.yml
default:
    vsphere_host: "<redacted>"  # vcenter endpoint
    vsphere_user: "<redacted>"
    vsphere_password: "<redacted>"
    ignore_ssl: True
    collect_only:
        vms: True
        vmguests: True
        datastores: False
        hosts: True
        snapshots: False
```

**Comment by Jc2k** [comment]
Hi @toastomatic 

Thanks for the info, the trac link is really useful. We had seen that bug, but only when a scrape was interrupted or Prometheus timed it out. Annoying log entry, but I haven’t seen it cause any issues by itself. Can you confirm when/how it was manifesting for you?

**Comment by toastomatic** [comment]
Hey @Jc2k 

With Twisted 18.9.0 installed, the collection process will run for a few minutes, then hit the traceback. Once the traceback is thrown, it will continue to run through the collection process, hit the traceback then attempt to collect again. This pattern persists until the container is restarted. At which point things will return to normal, until the pattern shows up again.

All the while my Grafana graphs will show data gaps that correspond directly with the traceback timings.

Below shows the pattern I'm referring to:

```
# docker-compose up -d
Creating volume "vmware-exporter_vmware-exporter-config" with local driver
Creating vmware-exporter ... done
# docker logs vmware-exporter -f
[2019-01-16 22:09:27.741100+00:00] Starting web server on port 9272
[2019-01-16 22:10:14.382052+00:00] Start collecting metrics from <redacted>
[2019-01-16 22:10:14.500969+00:00] Starting inventory collection
[2019-01-16 22:10:16.006166+00:00] Finished inventory collection
[2019-01-16 22:10:16.006300+00:00] Starting vm metrics collection
[2019-01-16 22:10:16.008459+00:00] Starting host metrics collection
[2019-01-16 22:10:16.107971+00:00] Finished host metrics collection
[2019-01-16 22:10:18.282833+00:00] START: _vmware_get_vm_perf_manager_metrics
[2019-01-16 22:10:18.757899+00:00] START: _vmware_get_vm_perf_manager_metrics: QUERY
[2019-01-16 22:10:23.501693+00:00] FIN: _vmware_get_vm_perf_manager_metrics: QUERY
[2019-01-16 22:10:23.612175+00:00] FIN: _vmware_get_vm_perf_manager_metrics
[2019-01-16 22:10:23.613110+00:00] Finished vm metrics collection
[2019-01-16 22:10:23.642861+00:00] Finished collecting metrics from <redacted>
[2019-01-16 22:11:14.379743+00:00] Start collecting metrics from <redacted>
[2019-01-16 22:11:14.504845+00:00] Starting inventory collection
[2019-01-16 22:11:16.004858+00:00] Finished inventory collection
[2019-01-16 22:11:16.004894+00:00] Starting vm metrics collection
[2019-01-16 22:11:16.005304+00:00] Starting host metrics collection
[2019-01-16 22:11:16.102795+00:00] Finished host metrics collection
[2019-01-16 22:11:18.289956+00:00] START: _vmware_get_vm_perf_manager_metrics
[2019-01-16 22:11:18.763140+00:00] START: _vmware_get_vm_perf_manager_metrics: QUERY
[2019-01-16 22:11:23.415687+00:00] FIN: _vmware_get_vm_perf_manager_metrics: QUERY
[2019-01-16 22:11:23.583183+00:00] FIN: _vmware_get_vm_perf_manager_metrics
[2019-01-16 22:11:23.584028+00:00] Finished vm metrics collection
[2019-01-16 22:11:23.613478+00:00] Finished collecting metrics from <redacted>
[2019-01-16 22:12:14.379559+00:00] Start collecting metrics from <redacted>
[2019-01-16 22:12:14.486087+00:00] Starting inventory collection
[2019-01-16 22:12:15.988808+00:00] Finished inventory collection
[2019-01-16 22:12:15.988843+00:00] Starting vm metrics collection
[2019-01-16 22:12:15.989256+00:00] Starting host metrics collection
[2019-01-16 22:12:16.089733+00:00] Finished host metrics collection
[2019-01-16 22:12:18.284488+00:00] START: _vmware_get_vm_perf_manager_metrics
[2019-01-16 22:12:18.731692+00:00] START: _vmware_get_vm_perf_manager_metrics: QUERY
[2019-01-16 22:12:23.451676+00:00] FIN: _vmware_get_vm_perf_manager_metrics: QUERY
[2019-01-16 22:12:23.618491+00:00] FIN: _vmware_get_vm_perf_manager_metrics
[2019-01-16 22:12:23.619211+00:00] Finished vm metrics collection
[2019-01-16 22:12:23.648637+00:00] Finished collecting metrics from <redacted>
[2019-01-16 22:13:14.379330+00:00] Start collecting metrics from <redacted>
[2019-01-16 22:13:14.541817+00:00] Starting inventory collection
[2019-01-16 22:13:16.151240+00:00] Finished inventory collection
[2019-01-16 22:13:16.151293+00:00] Starting vm metrics collection
[2019-01-16 22:13:16.151710+00:00] Starting host metrics collection
[2019-01-16 22:13:16.265074+00:00] Finished host metrics collection
[2019-01-16 22:13:18.426606+00:00] START: _vmware_get_vm_perf_manager_metrics
[2019-01-16 22:13:18.875426+00:00] START: _vmware_get_vm_perf_manager_metrics: QUERY
[2019-01-16 22:13:23.570821+00:00] FIN: _vmware_get_vm_perf_manager_metrics: QUERY
[2019-01-16 22:13:23.684817+00:00] FIN: _vmware_get_vm_perf_manager_metrics
[2019-01-16 22:13:23.685974+00:00] Finished vm metrics collection
[2019-01-16 22:13:23.715760+00:00] Finished collecting metrics from <redacted>
(..SNIP..)
[2019-01-16 22:17:18.395652+00:00] Start collecting metrics from <redacted>
[2019-01-16 22:17:26.634406+00:00] Starting inventory collection
[2019-01-16 22:17:28.121590+00:00] Finished inventory collection
[2019-01-16 22:17:28.121634+00:00] Starting vm metrics collection
[2019-01-16 22:17:28.122023+00:00] Starting host metrics collection
Unhandled error in Deferred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 501, in errback
    self._startRunCallbacks(fail)
  File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 568, in _startRunCallbacks
    self._runCallbacks()
  File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1475, in gotResult
    _inlineCallbacks(r, g, status)
--- <exception caught here> ---
  File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/local/lib/python3.6/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/local/lib/python3.6/site-packages/vmware_exporter/vmware_exporter.py", line 690, in _async_render_GET
    request.write(b'# Collection failed')
  File "/usr/local/lib/python3.6/site-packages/twisted/web/server.py", line 238, in write
    http.Request.write(self, data)
  File "/usr/local/lib/python3.6/site-packages/twisted/web/http.py", line 1137, in write
    self.channel.writeSequence(toChunk(data))
builtins.AttributeError: 'NoneType' object has no attribute 'writeSequence'

[2019-01-16 22:17:30.461502+00:00] START: _vmware_get_vm_perf_manager_metrics
[2019-01-16 22:17:30.925738+00:00] START: _vmware_get_vm_perf_manager_metrics: QUERY
[2019-01-16 22:17:32.235170+00:00] Finished host metrics collection
[2019-01-16 22:17:50.003710+00:00] FIN: _vmware_get_vm_perf_manager_metrics: QUERY
[2019-01-16 22:17:50.097619+00:00] FIN: _vmware_get_vm_perf_manager_metrics
[2019-01-16 22:17:50.098345+00:00] Finished vm metrics collection
[2019-01-16 22:17:50.126945+00:00] Finished collecting metrics from <redacted>
[2019-01-16 22:17:50.567547+00:00] Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
StopIteration: [<prometheus_client.core.GaugeMetricFamily object at 0x7fb615e1e588>, <prometheus_client.core.GaugeMetricFamily object at 0x7fb615e1e4e0>, <prometheus_client.core.GaugeMetricFamily object at 0x7fb615e1e470>, <prometheus_client.core.GaugeMetricFamily object at 0x7fb615e1e4a8>, <prometheus_client.core.GaugeMetricFamily object at 0x7fb615e1e400>, <prometheus_client.core.GaugeMetricFamily object at 0x7fb615e1ef98>, <prometheus_client.core.GaugeMetricFamily object at 0x7fb615e1efd0>, <prometheus_client.core.GaugeMetricFamily object at 0x7fb615cff0b8>, <prometheus_client.core.GaugeMetricFamily object at 0x7fb615cff0f0>, <prometheus_client.core.GaugeMetricFamily object at 0x7fb615cff080>, <prometheus_client.core.GaugeMetricFamily object at 0x7fb615cff160>, <prometheus_client.core.GaugeMetricFamily object at 0x7fb615cff128>, <prometheus_client.core.GaugeMetricFamily object at 0x7fb615cff1d0>, <prometheus_client.core.GaugeMetricFamily object at 0x7fb61651f0b8>, <prometheus_client.core.GaugeMetricFamily object at 0x7fb61651f6d8>, <prometheus_client.core.GaugeMetricFamily object at 0x7fb61651f3c8>, <prometheus_client.core.GaugeMetricFamily object at 0x7fb61651f6a0>, <prometheus_client.core.GaugeMetricFamily object at 0x7fb61651f8d0>, <prometheus_client.core.GaugeMetricFamily object at 0x7fb61651f7f0>, <prometheus_client.core.GaugeMetricFamily object at 0x7fb61651f860>, <prometheus_client.core.GaugeMetricFamily object at 0x7fb61651f1d0>, <prometheus_client.core.GaugeMetricFamily object at 0x7fb61651fa58>]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/vmware_exporter/vmware_exporter.py", line 686, in _async_render_GET
    yield self.generate_latest_metrics(request)
  File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/usr/local/lib/python3.6/site-packages/vmware_exporter/vmware_exporter.py", line 733, in generate_latest_metrics
    request.write(output)
  File "/usr/local/lib/python3.6/site-packages/twisted/web/server.py", line 238, in write
    http.Request.write(self, data)
  File "/usr/local/lib/python3.6/site-packages/twisted/web/http.py", line 1122, in write
    self.channel.writeHeaders(version, code, reason, headers)
AttributeError: 'NoneType' object has no attribute 'writeHeaders'

[2019-01-16 22:18:18.396067+00:00] Start collecting metrics from <redacted>
[2019-01-16 22:18:27.425356+00:00] Caught vmodl fault: [Errno -3] Try again
[2019-01-16 22:18:27.425592+00:00] b'Cannot connect to vmware'
[2019-01-16 22:18:27.425918+00:00] Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/vmware_exporter/vmware_exporter.py", line 686, in _async_render_GET
    yield self.generate_latest_metrics(request)
  File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/usr/local/lib/python3.6/site-packages/vmware_exporter/vmware_exporter.py", line 728, in generate_latest_metrics
    registry.register(ListCollector(metrics))
  File "/usr/local/lib/python3.6/site-packages/vmware_exporter/vmware_exporter.py", line 612, in __init__
    self.metrics = list(metrics)
TypeError: 'NoneType' object is not iterable

[2019-01-16 22:19:14.382644+00:00] Start collecting metrics from <redacted>
Unhandled error in Deferred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 501, in errback
    self._startRunCallbacks(fail)
  File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 568, in _startRunCallbacks
    self._runCallbacks()
  File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1475, in gotResult
    _inlineCallbacks(r, g, status)
--- <exception caught here> ---
  File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/local/lib/python3.6/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/local/lib/python3.6/site-packages/vmware_exporter/vmware_exporter.py", line 690, in _async_render_GET
    request.write(b'# Collection failed')
  File "/usr/local/lib/python3.6/site-packages/twisted/web/server.py", line 238, in write
    http.Request.write(self, data)
  File "/usr/local/lib/python3.6/site-packages/twisted/web/http.py", line 1122, in write
    self.channel.writeHeaders(version, code, reason, headers)
builtins.AttributeError: 'NoneType' object has no attribute 'writeHeaders'

[2019-01-16 22:19:19.937375+00:00] Starting inventory collection
[2019-01-16 22:19:21.416660+00:00] Finished inventory collection
[2019-01-16 22:19:21.416707+00:00] Starting vm metrics collection
[2019-01-16 22:19:21.417159+00:00] Starting host metrics collection
[2019-01-16 22:19:21.520535+00:00] Finished host metrics collection
Unhandled error in Deferred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 501, in errback
    self._startRunCallbacks(fail)
  File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 568, in _startRunCallbacks
    self._runCallbacks()
  File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1475, in gotResult
    _inlineCallbacks(r, g, status)
--- <exception caught here> ---
  File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/local/lib/python3.6/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/local/lib/python3.6/site-packages/vmware_exporter/vmware_exporter.py", line 690, in _async_render_GET
    request.write(b'# Collection failed')
  File "/usr/local/lib/python3.6/site-packages/twisted/web/server.py", line 238, in write
    http.Request.write(self, data)
  File "/usr/local/lib/python3.6/site-packages/twisted/web/http.py", line 1137, in write
    self.channel.writeSequence(toChunk(data))
builtins.AttributeError: 'NoneType' object has no attribute 'writeSequence'

[2019-01-16 22:19:23.748705+00:00] START: _vmware_get_vm_perf_manager_metrics
[2019-01-16 22:19:24.245328+00:00] START: _vmware_get_vm_perf_manager_metrics: QUERY
[2019-01-16 22:19:29.003424+00:00] FIN: _vmware_get_vm_perf_manager_metrics: QUERY
[2019-01-16 22:19:29.209132+00:00] FIN: _vmware_get_vm_perf_manager_metrics
[2019-01-16 22:19:29.209796+00:00] Finished vm metrics collection
[2019-01-16 22:19:29.236573+00:00] Finished collecting metrics from <redacted>
[2019-01-16 22:19:29.672862+00:00] Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
StopIteration: [<prometheus_client.core.GaugeMetricFamily object at 0x7fb61351ff60>, <prometheus_client.core.GaugeMetricFamily object at 0x7fb61351ffd0>, <prometheus_client.core.GaugeMetricFamily object at 0x7fb61351fe80>, <prometheus_client.core.GaugeMetricFamily object at 0x7fb61351fe48>, <prometheus_client.core.GaugeMetricFamily object at 0x7fb613380080>, <prometheus_client.core.GaugeMetricFamily object at 0x7fb613380320>, <prometheus_client.core.GaugeMetricFamily object at 0x7fb6133803c8>, <prometheus_client.core.GaugeMetricFamily object at 0x7fb613380390>, <prometheus_client.core.GaugeMetricFamily object at 0x7fb613380438>, <prometheus_client.core.GaugeMetricFamily object at 0x7fb613380400>, <prometheus_client.core.GaugeMetricFamily object at 0x7fb6133804a8>, <prometheus_client.core.GaugeMetricFamily object at 0x7fb613380470>, <prometheus_client.core.GaugeMetricFamily object at 0x7fb613380518>, <prometheus_client.core.GaugeMetricFamily object at 0x7fb613bb5358>, <prometheus_client.core.GaugeMetricFamily object at 0x7fb613bb56a0>, <prometheus_client.core.GaugeMetricFamily object at 0x7fb613bb5cc0>, <prometheus_client.core.GaugeMetricFamily object at 0x7fb613bb5be0>, <prometheus_client.core.GaugeMetricFamily object at 0x7fb613bb5ac8>, <prometheus_client.core.GaugeMetricFamily object at 0x7fb613bb5e10>, <prometheus_client.core.GaugeMetricFamily object at 0x7fb613bb5400>, <prometheus_client.core.GaugeMetricFamily object at 0x7fb613bb53c8>, <prometheus_client.core.GaugeMetricFamily object at 0x7fb613bb5438>]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/vmware_exporter/vmware_exporter.py", line 686, in _async_render_GET
    yield self.generate_latest_metrics(request)
  File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/usr/local/lib/python3.6/site-packages/vmware_exporter/vmware_exporter.py", line 733, in generate_latest_metrics
    request.write(output)
  File "/usr/local/lib/python3.6/site-packages/twisted/web/server.py", line 238, in write
    http.Request.write(self, data)
  File "/usr/local/lib/python3.6/site-packages/twisted/web/http.py", line 1122, in write
    self.channel.writeHeaders(version, code, reason, headers)
AttributeError: 'NoneType' object has no attribute 'writeHeaders'

[2019-01-16 22:20:14.380588+00:00] Start collecting metrics from <redacted>
[2019-01-16 22:20:14.491361+00:00] Starting inventory collection
[2019-01-16 22:20:15.986933+00:00] Finished inventory collection
[2019-01-16 22:20:15.987147+00:00] Starting vm metrics collection
[2019-01-16 22:20:15.987817+00:00] Starting host metrics collection
[2019-01-16 22:20:16.091148+00:00] Finished host metrics collection
[2019-01-16 22:20:18.329835+00:00] START: _vmware_get_vm_perf_manager_metrics
Unhandled error in Deferred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 501, in errback
    self._startRunCallbacks(fail)
  File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 568, in _startRunCallbacks
    self._runCallbacks()
  File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1475, in gotResult
    _inlineCallbacks(r, g, status)
--- <exception caught here> ---
  File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/local/lib/python3.6/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/local/lib/python3.6/site-packages/vmware_exporter/vmware_exporter.py", line 690, in _async_render_GET
    request.write(b'# Collection failed')
  File "/usr/local/lib/python3.6/site-packages/twisted/web/server.py", line 238, in write
    http.Request.write(self, data)
  File "/usr/local/lib/python3.6/site-packages/twisted/web/http.py", line 1137, in write
    self.channel.writeSequence(toChunk(data))
builtins.AttributeError: 'NoneType' object has no attribute 'writeSequence'

[2019-01-16 22:20:18.877593+00:00] START: _vmware_get_vm_perf_manager_metrics: QUERY
[2019-01-16 22:20:24.107586+00:00] FIN: _vmware_get_vm_perf_manager_metrics: QUERY
[2019-01-16 22:20:24.201577+00:00] FIN: _vmware_get_vm_perf_manager_metrics
[2019-01-16 22:20:24.202866+00:00] Finished vm metrics collection
[2019-01-16 22:20:24.232477+00:00] Finished collecting metrics from <redacted>
[2019-01-16 22:21:14.396251+00:00] Start collecting metrics from <redacted>
[2019-01-16 22:21:18.808416+00:00] Starting inventory collection
[2019-01-16 22:21:20.337776+00:00] Finished inventory collection
[2019-01-16 22:21:20.337825+00:00] Starting vm metrics collection
[2019-01-16 22:21:20.338224+00:00] Starting host metrics collection
[2019-01-16 22:21:20.471447+00:00] Finished host metrics collection
[2019-01-16 22:21:22.970154+00:00] START: _vmware_get_vm_perf_manager_metrics
[2019-01-16 22:21:23.391156+00:00] START: _vmware_get_vm_perf_manager_metrics: QUERY
[2019-01-16 22:21:28.251094+00:00] FIN: _vmware_get_vm_perf_manager_metrics: QUERY
[2019-01-16 22:21:28.516804+00:00] FIN: _vmware_get_vm_perf_manager_metrics
[2019-01-16 22:21:28.517875+00:00] Finished vm metrics collection
[2019-01-16 22:21:28.548751+00:00] Finished collecting metrics from <redacted>
[2019-01-16 22:21:28.985042+00:00] Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
StopIteration: [<prometheus_client.core.GaugeMetricFamily object at 0x7fb61526c4a8>, <prometheus_client.core.GaugeMetricFamily object at 0x7fb61526ccc0>, <prometheus_client.core.GaugeMetricFamily object at 0x7fb61526cb00>, <prometheus_client.core.GaugeMetricFamily object at 0x7fb61526cba8>, <prometheus_client.core.GaugeMetricFamily object at 0x7fb61526cb70>, <prometheus_client.core.GaugeMetricFamily object at 0x7fb61526c048>, <prometheus_client.core.GaugeMetricFamily object at 0x7fb61526c7f0>, <prometheus_client.core.GaugeMetricFamily object at 0x7fb61526cf98>, <prometheus_client.core.GaugeMetricFamily object at 0x7fb61526c550>, <prometheus_client.core.GaugeMetricFamily object at 0x7fb61526cf60>, <prometheus_client.core.GaugeMetricFamily object at 0x7fb61526cef0>, <prometheus_client.core.GaugeMetricFamily object at 0x7fb61526c748>, <prometheus_client.core.GaugeMetricFamily object at 0x7fb61526ce10>, <prometheus_client.core.GaugeMetricFamily object at 0x7fb6140484e0>, <prometheus_client.core.GaugeMetricFamily object at 0x7fb614048710>, <prometheus_client.core.GaugeMetricFamily object at 0x7fb614048390>, <prometheus_client.core.GaugeMetricFamily object at 0x7fb614048160>, <prometheus_client.core.GaugeMetricFamily object at 0x7fb6140480b8>, <prometheus_client.core.GaugeMetricFamily object at 0x7fb614048b38>, <prometheus_client.core.GaugeMetricFamily object at 0x7fb614048128>, <prometheus_client.core.GaugeMetricFamily object at 0x7fb614048470>, <prometheus_client.core.GaugeMetricFamily object at 0x7fb614048978>]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/vmware_exporter/vmware_exporter.py", line 686, in _async_render_GET
    yield self.generate_latest_metrics(request)
  File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/usr/local/lib/python3.6/site-packages/vmware_exporter/vmware_exporter.py", line 733, in generate_latest_metrics
    request.write(output)
  File "/usr/local/lib/python3.6/site-packages/twisted/web/server.py", line 238, in write
    http.Request.write(self, data)
  File "/usr/local/lib/python3.6/site-packages/twisted/web/http.py", line 1122, in write
    self.channel.writeHeaders(version, code, reason, headers)
AttributeError: 'NoneType' object has no attribute 'writeHeaders'
```
![screen shot 2019-01-16 at 3 30 01 pm](https://user-images.githubusercontent.com/46762078/51283231-cd3a6d00-19a4-11e9-834a-866fc88be04a.png)

**Comment by toastomatic** [comment]
As for the scrape timings: Prometheus is setup to scrape the container entry point every minute, and the scrape duration takes ~10 seconds.

**Comment by toastomatic** [comment]
I think I've nailed down where the issue is coming from: My scrape duration is 10+ seconds long, Prometheus's default scrape_timeout is 10s. So if the scrape takes 10.21s, it'll abort the scrape attempt, at which point the connections get shuttered and the Twisted bug appears.  

Increasing the scrape_timeout to 30s prevent the bug from cropping up, even under Twisted 18.9.0. 

So in sort @Jc2k you were correct in your initial assessment that this was a connection interruption issue. The tracebacks are themselves benign, and not the cause of the data loss I was seeing. Downgrading Twisted to 17.9.0 appears to have simply hidden the fact that the timeout was being hit, although it did allow the exporter to recover after a blip rather than spiraling into a traceback hole.
