### ISSUE TITLE
Failure to run directly, and wont build

### ISSUE THREAD

**Issue by AndreasDavour** [pryorda/vmware_exporter#86]
```
[root@c383pc-pmetheus ~]# git clone https://github.com/pryorda/vmware_exporter.git
Cloning into 'vmware_exporter'...
remote: Enumerating objects: 66, done.
remote: Counting objects: 100% (66/66), done.
remote: Compressing objects: 100% (55/55), done.
remote: Total 535 (delta 26), reused 40 (delta 11), pack-reused 469
Receiving objects: 100% (535/535), 154.51 KiB | 0 bytes/s, done.
Resolving deltas: 100% (281/281), done.
[root@c383pc-pmetheus ~]# cd vmware_exporter/
[root@c383pc-pmetheus vmware_exporter]# python vmware_exporter/vmware_exporter.py
  File "vmware_exporter/vmware_exporter.py", line 218
    return list(metrics.values())   # noqa: F705
SyntaxError: 'return' with argument inside generator
```

```
[root@c383pc-pmetheus vmware_exporter]# python setup.py install
running install
running bdist_egg
running egg_info
creating vmware_exporter.egg-info
writing requirements to vmware_exporter.egg-info/requires.txt
writing vmware_exporter.egg-info/PKG-INFO
writing top-level names to vmware_exporter.egg-info/top_level.txt
writing dependency_links to vmware_exporter.egg-info/dependency_links.txt
writing entry points to vmware_exporter.egg-info/entry_points.txt
writing manifest file 'vmware_exporter.egg-info/SOURCES.txt'
reading manifest file 'vmware_exporter.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'vmware_exporter.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib
creating build/lib/vmware_exporter
copying vmware_exporter/__init__.py -> build/lib/vmware_exporter
copying vmware_exporter/defer.py -> build/lib/vmware_exporter
copying vmware_exporter/helpers.py -> build/lib/vmware_exporter
copying vmware_exporter/vmware_exporter.py -> build/lib/vmware_exporter
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/vmware_exporter
copying build/lib/vmware_exporter/__init__.py -> build/bdist.linux-x86_64/egg/vmware_exporter
copying build/lib/vmware_exporter/defer.py -> build/bdist.linux-x86_64/egg/vmware_exporter
copying build/lib/vmware_exporter/helpers.py -> build/bdist.linux-x86_64/egg/vmware_exporter
copying build/lib/vmware_exporter/vmware_exporter.py -> build/bdist.linux-x86_64/egg/vmware_exporter
byte-compiling build/bdist.linux-x86_64/egg/vmware_exporter/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/vmware_exporter/defer.py to defer.pyc
SyntaxError: 'return' with argument inside generator (defer.py, line 100)

byte-compiling build/bdist.linux-x86_64/egg/vmware_exporter/helpers.py to helpers.pyc
byte-compiling build/bdist.linux-x86_64/egg/vmware_exporter/vmware_exporter.py to vmware_exporter.pyc
SyntaxError: 'return' with argument inside generator (vmware_exporter.py, line 218)

creating build/bdist.linux-x86_64/egg/EGG-INFO
copying vmware_exporter.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying vmware_exporter.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying vmware_exporter.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying vmware_exporter.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying vmware_exporter.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying vmware_exporter.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating dist
creating 'dist/vmware_exporter-0.7.0-py2.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing vmware_exporter-0.7.0-py2.7.egg
Removing /usr/lib/python2.7/site-packages/vmware_exporter-0.7.0-py2.7.egg
Copying vmware_exporter-0.7.0-py2.7.egg to /usr/lib/python2.7/site-packages
vmware-exporter 0.7.0 is already the active version in easy-install.pth
Installing vmware_exporter script to /usr/bin

Installed /usr/lib/python2.7/site-packages/vmware_exporter-0.7.0-py2.7.egg
Processing dependencies for vmware-exporter==0.7.0
Traceback (most recent call last):
  File "setup.py", line 20, in <module>
    'vmware_exporter=vmware_exporter.vmware_exporter:main'
  File "/usr/lib64/python2.7/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/usr/lib64/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/site-packages/setuptools/command/install.py", line 73, in run
    self.do_egg_install()
  File "/usr/lib/python2.7/site-packages/setuptools/command/install.py", line 101, in do_egg_install
    cmd.run()
  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 380, in run
    self.easy_install(spec, not self.no_deps)
  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 604, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 655, in install_item
    self.process_distribution(spec, dist, deps)
  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 706, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 631, in resolve
    requirements.extend(dist.requires(req.extras)[::-1])
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2489, in requires
    dm = self._dep_map
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2474, in _dep_map
    for extra,reqs in split_sections(self._get_metadata(name)):
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2964, in split_sections
    for line in yield_lines(s):
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2161, in yield_lines
    for ss in strs:
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2503, in _get_metadata
    for line in self.get_metadata_lines(name):
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 1429, in get_metadata_lines
    return yield_lines(self.get_metadata(name))
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 1421, in get_metadata
    return self._get(self._fn(self.egg_info,name))
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 1486, in _get
    return self.loader.get_data(path)
zipimport.ZipImportError: bad local file header in /usr/lib/python2.7/site-packages/vmware_exporter-0.7.0-py2.7.egg
```

**Comment by Jc2k** [comment]
Hi

You need to run it on python 3.

Cheers

**Comment by AndreasDavour** [comment]
Traceback (most recent call last):
  File "vmware_exporter/vmware_exporter.py", line 17, in <module>
    import pytz
ModuleNotFoundError: No module named 'pytz'

So what kind of package is needed then? I have  installed pytz using pip, I have tried to install pytz and python34-pytz which are the packages available to RHEL7/CentOS7. 

Still that same error.

**Comment by Jc2k** [comment]
It’s easy if you know how, and frustrating if you don’t. When you’ve been doing python for 15 years you just don’t see the things a new user will cut themselves on so sorry you are having a shit time.

TBH we all use the Dockerized version of this so haven’t hit any of these issues before. We have recently adopted the pypi project from the original author but no one has contributed a detailed non-Docker setup yet.

When I’m devving I use something called virtualenv and install all my python dependencies from the python upstream repository into an instance of virtualenv. Distros would disagree but they can’t really keep up with the rate of change of the stuff they are packaging. Even if I was trying to use district packages I would probably use Debian Stretch so just not see how rough it gets on RHEL.

This code expects to be run installed. How do we dev if without installing it? Pip supports editable installs. If you were devving it like me you would do

```
pip3 install -e .
```

From inside the project folder and with a virtualenv active.

If you wanted to install from git you could do

```
pip3 install .
```

From inside the project folder.

Standard practice would be to installed a tagged release from pypi with pip.

```
pip install vmware_exporter
```

All 3 of these will create a vmware_exporter bin for you to run, and avoid this error.

Sorry for typos, on phone. Good luck.

**Comment by Jc2k** [comment]
(And to be clear, that error isn’t a python version error it’s a thing isn’t installed error.)

**Comment by AndreasDavour** [comment]
Thanks a lot for the detailed description. Very much appreciated. It is indeed a bit opaque when not used to the workflow.
