### ISSUE TITLE
object has no attribute 'writeHeaders'

### ISSUE THREAD

**Issue by slis** [pryorda/vmware_exporter#87]
Hi, 

on version 0.7.0, centos 7, getting random fail to export, like every 12h 1-3 times with this error below.

Thanks, great software 👍 
```
During handling of the above exception, another exception occurred:

[2019-02-08 12:14:33.523685+00:00] Traceback (most recent call last):
  File "/usr/local/lib64/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
StopIteration: ((vim.PerformanceManager.EntityMetricBase) [
   (vim.PerformanceManager.EntityMetric) {
      dynamicType = <unset>,
      dynamicProperty = (vmodl.DynamicProperty) [],
      entity = 'vim.VirtualMachine:vm-10212',
      sampleInfo = (vim.PerformanceManager.SampleInfo) [
         (vim.PerformanceManager.SampleInfo) {
            dynamicType = <unset>,
            dynamicProperty = (vmodl.DynamicProperty) [],
            timestamp = 2019-02-08T12:14:20Z,
            interval = 20
         }
      ],
      value = (vim.PerformanceManager.MetricSeries) [
         (vim.PerformanceManager.IntSeries) {
            dynamicType = <unset>,
            dynamicProperty = (vmodl.DynamicProperty) [],
            id = (vim.PerformanceManager.MetricId) {
               dynamicType = <unset>,
               dynamicProperty = (vmodl.DynamicProperty) [],
               counterId = 12,
               instance = ''
            },
            value = (long) [
               22
            ]
         },

```
```

Traceback (most recent call last):
  File "/usr/local/lib64/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
StopIteration: [<prometheus_client.core.GaugeMetricFamily object at 0x7fd6519135f8>, <prometheus_client.core.GaugeMetricFamily object at 0x7fd6519137b8>, <prometheus_client.core.GaugeMetricFamily object at 0x7fd6519135c0>, <prometheus_client.core.GaugeMetricFamily object at 0x7fd651913518>, <prometheus_client.core.GaugeMetricFamily object at 0x7fd651913748>, <prometheus_client.core.GaugeMetricFamily object at 0x7fd651913550>, <prometheus_client.core.GaugeMetricFamily object at 0x7fd651913a58>, <prometheus_client.core.GaugeMetricFamily object at 0x7fd651913be0>, <prometheus_client.core.GaugeMetricFamily object at 0x7fd651913630>, <prometheus_client.core.GaugeMetricFamily object at 0x7fd651529588>, <prometheus_client.core.GaugeMetricFamily object at 0x7fd6515290b8>, <prometheus_client.core.GaugeMetricFamily object at 0x7fd6515292b0>, <prometheus_client.core.GaugeMetricFamily object at 0x7fd6515292e8>, <prometheus_client.core.GaugeMetricFamily object at 0x7fd651529358>, <prometheus_client.core.GaugeMetricFamily object at 0x7fd651529390>, <prometheus_client.core.GaugeMetricFamily object at 0x7fd6515293c8>, <prometheus_client.core.GaugeMetricFamily object at 0x7fd651529400>, <prometheus_client.core.GaugeMetricFamily object at 0x7fd651529438>, <prometheus_client.core.GaugeMetricFamily object at 0x7fd6515294a8>, <prometheus_client.core.GaugeMetricFamily object at 0x7fd6515290f0>, <prometheus_client.core.GaugeMetricFamily object at 0x7fd6515294e0>, <prometheus_client.core.GaugeMetricFamily object at 0x7fd651529470>, <prometheus_client.core.GaugeMetricFamily object at 0x7fd651529748>, <prometheus_client.core.GaugeMetricFamily object at 0x7fd6515297f0>, <prometheus_client.core.GaugeMetricFamily object at 0x7fd651529940>, <prometheus_client.core.GaugeMetricFamily object at 0x7fd651529978>, <prometheus_client.core.GaugeMetricFamily object at 0x7fd651529a20>, <prometheus_client.core.GaugeMetricFamily object at 0x7fd6514d5550>, <prometheus_client.core.GaugeMetricFamily object at 0x7fd6514d5588>, <prometheus_client.core.GaugeMetricFamily object at 0x7fd6514d55c0>, <prometheus_client.core.GaugeMetricFamily object at 0x7fd6514d55f8>, <prometheus_client.core.GaugeMetricFamily object at 0x7fd6514d5630>, <prometheus_client.core.GaugeMetricFamily object at 0x7fd6514d56a0>, <prometheus_client.core.GaugeMetricFamily object at 0x7fd6514d56d8>, <prometheus_client.core.GaugeMetricFamily object at 0x7fd6514d5780>, <prometheus_client.core.GaugeMetricFamily object at 0x7fd6514d5668>]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/vmware_exporter/vmware_exporter.py", line 806, in _async_render_GET
    yield self.generate_latest_metrics(request)
  File "/usr/local/lib64/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/usr/local/lib/python3.6/site-packages/vmware_exporter/vmware_exporter.py", line 853, in generate_latest_metrics
    request.write(output)
  File "/usr/local/lib64/python3.6/site-packages/twisted/web/server.py", line 238, in write
    http.Request.write(self, data)
  File "/usr/local/lib64/python3.6/site-packages/twisted/web/http.py", line 1122, in write
    self.channel.writeHeaders(version, code, reason, headers)
AttributeError: 'NoneType' object has no attribute 'writeHeaders'
```

**Comment by Jc2k** [comment]
Hi!

This happens when your Prometheus timeout is too low. It’s disconnecting before it has collected all the metrics, so twisted has no socket left to write to! The esx api is quite slow :(
