### ISSUE TITLE
 'dict' object has no attribute 'extend'

### ISSUE THREAD

**Issue by slis** [pryorda/vmware_exporter#88]
Now getting different error, with different vcenter 

`[2019-02-09 20:04:59.231355+00:00] Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/vmware_exporter/vmware_exporter.py", line 806, in _async_render_GET
    yield self.generate_latest_metrics(request)
twisted.internet.defer.FirstError: FirstError[#0, [Failure instance: Traceback: <class 'twisted.internet.defer.FirstError'>: FirstError[#1, [Failure instance: Traceback: <class 'twisted.internet.defer.FirstError'>: FirstError[#1, [Failure instance: Traceback: <class 'AttributeError'>: 'dict' object has no attribute 'extend'
/usr/local/lib64/python3.6/site-packages/twisted/internet/defer.py:501:errback
/usr/local/lib64/python3.6/site-packages/twisted/internet/defer.py:568:_startRunCallbacks
/usr/local/lib64/python3.6/site-packages/twisted/internet/defer.py:654:_runCallbacks
/usr/local/lib64/python3.6/site-packages/twisted/internet/defer.py:1475:gotResult
--- <exception caught here> ---
/usr/local/lib64/python3.6/site-packages/twisted/internet/defer.py:1416:_inlineCallbacks
/usr/local/lib64/python3.6/site-packages/twisted/python/failure.py:491:throwExceptionIntoGenerator
/usr/local/lib/python3.6/site-packages/vmware_exporter/vmware_exporter.py:421:host_labels
/usr/local/lib64/python3.6/site-packages/twisted/python/threadpool.py:250:inContext
/usr/local/lib64/python3.6/site-packages/twisted/python/threadpool.py:266:<lambda>
/usr/local/lib64/python3.6/site-packages/twisted/python/context.py:122:callWithContext
/usr/local/lib64/python3.6/site-packages/twisted/python/context.py:85:callWithContext
/usr/local/lib/python3.6/site-packages/vmware_exporter/vmware_exporter.py:421:<lambda>
/usr/local/lib/python3.6/site-packages/vmware_exporter/vmware_exporter.py:414:_collect
]]
--- <exception caught here> ---
/usr/local/lib/python3.6/site-packages/vmware_exporter/vmware_exporter.py:429:vm_labels
/usr/local/lib/python3.6/site-packages/vmware_exporter/defer.py:99:parallelize
]]
--- <exception caught here> ---
/usr/local/lib/python3.6/site-packages/vmware_exporter/vmware_exporter.py:594:_vmware_get_vms
/usr/local/lib/python3.6/site-packages/vmware_exporter/defer.py:99:parallelize
]]

Unhandled error in Deferred:

Traceback (most recent call last):
--- <exception caught here> ---
  File "/usr/local/lib/python3.6/site-packages/vmware_exporter/vmware_exporter.py", line 429, in vm_labels
    virtual_machines, host_labels = yield parallelize(self.vm_inventory, self.host_labels)
  File "/usr/local/lib/python3.6/site-packages/vmware_exporter/defer.py", line 99, in parallelize
    results = yield defer.DeferredList(args, fireOnOneErrback=True)
twisted.internet.defer.FirstError: FirstError[#1, [Failure instance: Traceback: <class 'AttributeError'>: 'dict' object has no attribute 'extend'
/usr/local/lib64/python3.6/site-packages/twisted/internet/defer.py:501:errback
/usr/local/lib64/python3.6/site-packages/twisted/internet/defer.py:568:_startRunCallbacks
/usr/local/lib64/python3.6/site-packages/twisted/internet/defer.py:654:_runCallbacks
/usr/local/lib64/python3.6/site-packages/twisted/internet/defer.py:1475:gotResult
--- <exception caught here> ---
/usr/local/lib64/python3.6/site-packages/twisted/internet/defer.py:1416:_inlineCallbacks
/usr/local/lib64/python3.6/site-packages/twisted/python/failure.py:491:throwExceptionIntoGenerator
/usr/local/lib/python3.6/site-packages/vmware_exporter/vmware_exporter.py:421:host_labels
/usr/local/lib64/python3.6/site-packages/twisted/python/threadpool.py:250:inContext
/usr/local/lib64/python3.6/site-packages/twisted/python/threadpool.py:266:<lambda>
/usr/local/lib64/python3.6/site-packages/twisted/python/context.py:122:callWithContext
/usr/local/lib64/python3.6/site-packages/twisted/python/context.py:85:callWithContext
/usr/local/lib/python3.6/site-packages/vmware_exporter/vmware_exporter.py:421:<lambda>
/usr/local/lib/python3.6/site-packages/vmware_exporter/vmware_exporter.py:414:_collect
]]

Unhandled error in Deferred:

Traceback (most recent call last):
--- <exception caught here> ---
  File "/usr/local/lib/python3.6/site-packages/vmware_exporter/vmware_exporter.py", line 429, in vm_labels
    virtual_machines, host_labels = yield parallelize(self.vm_inventory, self.host_labels)
  File "/usr/local/lib/python3.6/site-packages/vmware_exporter/defer.py", line 99, in parallelize
    results = yield defer.DeferredList(args, fireOnOneErrback=True)
twisted.internet.defer.FirstError: FirstError[#1, [Failure instance: Traceback: <class 'AttributeError'>: 'dict' object has no attribute 'extend'
/usr/local/lib64/python3.6/site-packages/twisted/internet/defer.py:501:errback
/usr/local/lib64/python3.6/site-packages/twisted/internet/defer.py:568:_startRunCallbacks
/usr/local/lib64/python3.6/site-packages/twisted/internet/defer.py:654:_runCallbacks
/usr/local/lib64/python3.6/site-packages/twisted/internet/defer.py:1475:gotResult
--- <exception caught here> ---
/usr/local/lib64/python3.6/site-packages/twisted/internet/defer.py:1416:_inlineCallbacks
/usr/local/lib64/python3.6/site-packages/twisted/python/failure.py:491:throwExceptionIntoGenerator
/usr/local/lib/python3.6/site-packages/vmware_exporter/vmware_exporter.py:421:host_labels
/usr/local/lib64/python3.6/site-packages/twisted/python/threadpool.py:250:inContext
/usr/local/lib64/python3.6/site-packages/twisted/python/threadpool.py:266:<lambda>
/usr/local/lib64/python3.6/site-packages/twisted/python/context.py:122:callWithContext
/usr/local/lib64/python3.6/site-packages/twisted/python/context.py:85:callWithContext
/usr/local/lib/python3.6/site-packages/vmware_exporter/vmware_exporter.py:421:<lambda>
/usr/local/lib/python3.6/site-packages/vmware_exporter/vmware_exporter.py:414:_collect
]]

Unhandled error in Deferred:

Traceback (most recent call last):
  File "/usr/local/lib64/python3.6/site-packages/twisted/internet/defer.py", line 501, in errback
    self._startRunCallbacks(fail)
  File "/usr/local/lib64/python3.6/site-packages/twisted/internet/defer.py", line 568, in _startRunCallbacks
    self._runCallbacks()
  File "/usr/local/lib64/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/usr/local/lib64/python3.6/site-packages/twisted/internet/defer.py", line 1475, in gotResult
    _inlineCallbacks(r, g, status)
--- <exception caught here> ---
  File "/usr/local/lib64/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/local/lib64/python3.6/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/local/lib/python3.6/site-packages/vmware_exporter/vmware_exporter.py", line 421, in host_labels
    result = yield threads.deferToThread(lambda: _collect(dc, dc.hostFolder))
  File "/usr/local/lib64/python3.6/site-packages/twisted/python/threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "/usr/local/lib64/python3.6/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/usr/local/lib64/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/local/lib64/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "/usr/local/lib/python3.6/site-packages/vmware_exporter/vmware_exporter.py", line 421, in <lambda>
    result = yield threads.deferToThread(lambda: _collect(dc, dc.hostFolder))
  File "/usr/local/lib/python3.6/site-packages/vmware_exporter/vmware_exporter.py", line 414, in _collect
    host_inventory.extend(_collect(dc, folder))
builtins.AttributeError: 'dict' object has no attribute 'extend'

Unhandled error in Deferred:

Traceback (most recent call last):
  File "/usr/local/lib64/python3.6/site-packages/twisted/internet/defer.py", line 501, in errback
    self._startRunCallbacks(fail)
  File "/usr/local/lib64/python3.6/site-packages/twisted/internet/defer.py", line 568, in _startRunCallbacks
    self._runCallbacks()
  File "/usr/local/lib64/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/usr/local/lib64/python3.6/site-packages/twisted/internet/defer.py", line 1475, in gotResult
    _inlineCallbacks(r, g, status)
--- <exception caught here> ---
  File "/usr/local/lib64/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/local/lib64/python3.6/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/local/lib/python3.6/site-packages/vmware_exporter/vmware_exporter.py", line 421, in host_labels
    result = yield threads.deferToThread(lambda: _collect(dc, dc.hostFolder))
  File "/usr/local/lib64/python3.6/site-packages/twisted/python/threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "/usr/local/lib64/python3.6/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/usr/local/lib64/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/local/lib64/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "/usr/local/lib/python3.6/site-packages/vmware_exporter/vmware_exporter.py", line 421, in <lambda>
    result = yield threads.deferToThread(lambda: _collect(dc, dc.hostFolder))
  File "/usr/local/lib/python3.6/site-packages/vmware_exporter/vmware_exporter.py", line 414, in _collect
    host_inventory.extend(_collect(dc, folder))
builtins.AttributeError: 'dict' object has no attribute 'extend'

`

**Comment by pryorda** [comment]
What version are you running and how is it installed?

**Comment by slis** [comment]
You mean exporter or vsphere version?

Exporter is 0.7.0,
vsphere is 6.5 
i did pip install vmware_expoerter with python3.6 on centos 7

**Comment by pryorda** [comment]
Whats the hierarchy in vmware? Can you get me the exact steps to reproduce as well?

**Comment by slis** [comment]
I just checked, and there is folder under Hosts and Clusters tab.

**Comment by slis** [comment]
If I create folder under Hosts and Clusters tab I can reproduce almost same error, but there is no hosts in created folder.

```
 Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/vmware_exporter/vmware_exporter.py", line 806, in _async_render_GET
    yield self.generate_latest_metrics(request)
twisted.internet.defer.FirstError: FirstError[#2, [Failure instance: Traceback: <class 'twisted.internet.defer.FirstError'>: FirstError[#1, [Failure instance: Traceback: <class 'AttributeError'>: 'vim.Folder' object has no attribute 'datastoreFolder'
/usr/local/lib64/python3.6/site-packages/twisted/internet/defer.py:501:errback
/usr/local/lib64/python3.6/site-packages/twisted/internet/defer.py:568:_startRunCallbacks
/usr/local/lib64/python3.6/site-packages/twisted/internet/defer.py:654:_runCallbacks
/usr/local/lib64/python3.6/site-packages/twisted/internet/defer.py:1475:gotResult
--- <exception caught here> ---
/usr/local/lib64/python3.6/site-packages/twisted/internet/defer.py:1416:_inlineCallbacks
/usr/local/lib64/python3.6/site-packages/twisted/python/failure.py:491:throwExceptionIntoGenerator
/usr/local/lib/python3.6/site-packages/vmware_exporter/vmware_exporter.py:392:datastore_labels
/usr/local/lib64/python3.6/site-packages/twisted/python/threadpool.py:250:inContext
/usr/local/lib64/python3.6/site-packages/twisted/python/threadpool.py:266:<lambda>
/usr/local/lib64/python3.6/site-packages/twisted/python/context.py:122:callWithContext
/usr/local/lib64/python3.6/site-packages/twisted/python/context.py:85:callWithContext
/usr/local/lib/python3.6/site-packages/vmware_exporter/vmware_exporter.py:392:<lambda>
]]
--- <exception caught here> ---
/usr/local/lib/python3.6/site-packages/vmware_exporter/vmware_exporter.py:486:_vmware_get_datastores
/usr/local/lib/python3.6/site-packages/vmware_exporter/defer.py:99:parallelize
]]

Unhandled error in Deferred:

Traceback (most recent call last):
  File "/usr/local/lib64/python3.6/site-packages/twisted/internet/defer.py", line 501, in errback
    self._startRunCallbacks(fail)
  File "/usr/local/lib64/python3.6/site-packages/twisted/internet/defer.py", line 568, in _startRunCallbacks
    self._runCallbacks()
  File "/usr/local/lib64/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/usr/local/lib64/python3.6/site-packages/twisted/internet/defer.py", line 1475, in gotResult
    _inlineCallbacks(r, g, status)
--- <exception caught here> ---
  File "/usr/local/lib64/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/local/lib64/python3.6/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/local/lib/python3.6/site-packages/vmware_exporter/vmware_exporter.py", line 392, in datastore_labels
    result = yield threads.deferToThread(lambda: _collect(dc, dc.datastoreFolder))
  File "/usr/local/lib64/python3.6/site-packages/twisted/python/threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "/usr/local/lib64/python3.6/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/usr/local/lib64/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/local/lib64/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "/usr/local/lib/python3.6/site-packages/vmware_exporter/vmware_exporter.py", line 392, in <lambda>
    result = yield threads.deferToThread(lambda: _collect(dc, dc.datastoreFolder))
builtins.AttributeError: 'vim.Folder' object has no attribute 'datastoreFolder'

[2019-02-09 22:52:08.167025+00:00] Fetched vim.VirtualMachine inventory (0:00:03.819219)
Unhandled error in Deferred:

Traceback (most recent call last):
--- <exception caught here> ---
  File "/usr/local/lib/python3.6/site-packages/vmware_exporter/vmware_exporter.py", line 429, in vm_labels
    virtual_machines, host_labels = yield parallelize(self.vm_inventory, self.host_labels)
  File "/usr/local/lib/python3.6/site-packages/vmware_exporter/defer.py", line 99, in parallelize
    results = yield defer.DeferredList(args, fireOnOneErrback=True)
twisted.internet.defer.FirstError: FirstError[#1, [Failure instance: Traceback: <class 'AttributeError'>: 'vim.Folder' object has no attribute 'hostFolder'
/usr/local/lib64/python3.6/site-packages/twisted/internet/defer.py:501:errback
/usr/local/lib64/python3.6/site-packages/twisted/internet/defer.py:568:_startRunCallbacks
/usr/local/lib64/python3.6/site-packages/twisted/internet/defer.py:654:_runCallbacks
/usr/local/lib64/python3.6/site-packages/twisted/internet/defer.py:1475:gotResult
--- <exception caught here> ---
/usr/local/lib64/python3.6/site-packages/twisted/internet/defer.py:1416:_inlineCallbacks
/usr/local/lib64/python3.6/site-packages/twisted/python/failure.py:491:throwExceptionIntoGenerator
/usr/local/lib/python3.6/site-packages/vmware_exporter/vmware_exporter.py:421:host_labels
/usr/local/lib64/python3.6/site-packages/twisted/python/threadpool.py:250:inContext
/usr/local/lib64/python3.6/site-packages/twisted/python/threadpool.py:266:<lambda>
/usr/local/lib64/python3.6/site-packages/twisted/python/context.py:122:callWithContext
/usr/local/lib64/python3.6/site-packages/twisted/python/context.py:85:callWithContext
/usr/local/lib/python3.6/site-packages/vmware_exporter/vmware_exporter.py:421:<lambda>
]]

Unhandled error in Deferred:

Traceback (most recent call last):
--- <exception caught here> ---
  File "/usr/local/lib/python3.6/site-packages/vmware_exporter/vmware_exporter.py", line 429, in vm_labels
    virtual_machines, host_labels = yield parallelize(self.vm_inventory, self.host_labels)
  File "/usr/local/lib/python3.6/site-packages/vmware_exporter/defer.py", line 99, in parallelize
    results = yield defer.DeferredList(args, fireOnOneErrback=True)
twisted.internet.defer.FirstError: FirstError[#1, [Failure instance: Traceback: <class 'AttributeError'>: 'vim.Folder' object has no attribute 'hostFolder'
/usr/local/lib64/python3.6/site-packages/twisted/internet/defer.py:501:errback
/usr/local/lib64/python3.6/site-packages/twisted/internet/defer.py:568:_startRunCallbacks
/usr/local/lib64/python3.6/site-packages/twisted/internet/defer.py:654:_runCallbacks
/usr/local/lib64/python3.6/site-packages/twisted/internet/defer.py:1475:gotResult
--- <exception caught here> ---
/usr/local/lib64/python3.6/site-packages/twisted/internet/defer.py:1416:_inlineCallbacks
/usr/local/lib64/python3.6/site-packages/twisted/python/failure.py:491:throwExceptionIntoGenerator
/usr/local/lib/python3.6/site-packages/vmware_exporter/vmware_exporter.py:421:host_labels
/usr/local/lib64/python3.6/site-packages/twisted/python/threadpool.py:250:inContext
/usr/local/lib64/python3.6/site-packages/twisted/python/threadpool.py:266:<lambda>
/usr/local/lib64/python3.6/site-packages/twisted/python/context.py:122:callWithContext
/usr/local/lib64/python3.6/site-packages/twisted/python/context.py:85:callWithContext
/usr/local/lib/python3.6/site-packages/vmware_exporter/vmware_exporter.py:421:<lambda>
]]

Unhandled error in Deferred:

Traceback (most recent call last):
  File "/usr/local/lib64/python3.6/site-packages/twisted/internet/defer.py", line 501, in errback
    self._startRunCallbacks(fail)
  File "/usr/local/lib64/python3.6/site-packages/twisted/internet/defer.py", line 568, in _startRunCallbacks
    self._runCallbacks()
  File "/usr/local/lib64/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/usr/local/lib64/python3.6/site-packages/twisted/internet/defer.py", line 1475, in gotResult
    _inlineCallbacks(r, g, status)
--- <exception caught here> ---
  File "/usr/local/lib64/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/local/lib64/python3.6/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/local/lib/python3.6/site-packages/vmware_exporter/vmware_exporter.py", line 421, in host_labels
    result = yield threads.deferToThread(lambda: _collect(dc, dc.hostFolder))
  File "/usr/local/lib64/python3.6/site-packages/twisted/python/threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "/usr/local/lib64/python3.6/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/usr/local/lib64/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/local/lib64/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "/usr/local/lib/python3.6/site-packages/vmware_exporter/vmware_exporter.py", line 421, in <lambda>
    result = yield threads.deferToThread(lambda: _collect(dc, dc.hostFolder))
builtins.AttributeError: 'vim.Folder' object has no attribute 'hostFolder'

Unhandled error in Deferred:

Traceback (most recent call last):
  File "/usr/local/lib64/python3.6/site-packages/twisted/internet/defer.py", line 501, in errback
    self._startRunCallbacks(fail)
  File "/usr/local/lib64/python3.6/site-packages/twisted/internet/defer.py", line 568, in _startRunCallbacks
    self._runCallbacks()
  File "/usr/local/lib64/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/usr/local/lib64/python3.6/site-packages/twisted/internet/defer.py", line 1475, in gotResult
    _inlineCallbacks(r, g, status)
--- <exception caught here> ---
  File "/usr/local/lib64/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/local/lib64/python3.6/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/local/lib/python3.6/site-packages/vmware_exporter/vmware_exporter.py", line 421, in host_labels
    result = yield threads.deferToThread(lambda: _collect(dc, dc.hostFolder))
  File "/usr/local/lib64/python3.6/site-packages/twisted/python/threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "/usr/local/lib64/python3.6/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/usr/local/lib64/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/local/lib64/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "/usr/local/lib/python3.6/site-packages/vmware_exporter/vmware_exporter.py", line 421, in <lambda>
    result = yield threads.deferToThread(lambda: _collect(dc, dc.hostFolder))
builtins.AttributeError: 'vim.Folder' object has no attribute 'hostFolder'

```

**Comment by pryorda** [comment]
This is related to #63. Lets close for now can you follow up on that issue? Thanks.

**Comment by slis** [comment]
Thanks, I deleted Folder from Clusters and Hosts tab now it works.
