### ISSUE TITLE
error while run vmware_exporter command

### ISSUE THREAD

**Issue by vdvas** [pryorda/vmware_exporter#96]
On Debian GNU/Linux 9.8 (stretch)
When i run command
vmware_exporter -c config.yml 
I het this error 
```
Traceback (most recent call last):
  File "/usr/local/bin/vmware_exporter", line 11, in <module>
    load_entry_point('vmware-exporter==0.7.3', 'console_scripts', 'vmware_exporter')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 561, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/vmware_exporter-0.7.3-py2.7.egg/vmware_exporter/vmware_exporter.py", line 218
SyntaxError: 'return' with argument inside generator
```

**Comment by Jc2k** [comment]
Hi! That error means you installed on py2, we need py3.

**Comment by vdvas** [comment]
Thanks.
I change default python envirolment to python 3.5 from 2.7 and rerun setup.
