### ISSUE TITLE
SSL: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by vdvas** [pryorda/vmware_exporter#97]
When i run vmware_exporter -c config.yml
I see error
```
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:720)
```
What I need to setup? Maybe i must install certificate of vcenter in prometheus server?

```
Unhandled error in Deferred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/Twisted-19.2.0rc1-py3.5-linux-x86_64.egg/twisted/internet/defer.py", line 501, in errback
    self._startRunCallbacks(fail)
  File "/usr/local/lib/python3.5/dist-packages/Twisted-19.2.0rc1-py3.5-linux-x86_64.egg/twisted/internet/defer.py", line 568, in _startRunCallbacks
    self._runCallbacks()
  File "/usr/local/lib/python3.5/dist-packages/Twisted-19.2.0rc1-py3.5-linux-x86_64.egg/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/usr/local/lib/python3.5/dist-packages/Twisted-19.2.0rc1-py3.5-linux-x86_64.egg/twisted/internet/defer.py", line 1475, in gotResult
    _inlineCallbacks(r, g, status)
--- <exception caught here> ---
  File "/usr/local/lib/python3.5/dist-packages/Twisted-19.2.0rc1-py3.5-linux-x86_64.egg/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/local/lib/python3.5/dist-packages/Twisted-19.2.0rc1-py3.5-linux-x86_64.egg/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/local/lib/python3.5/dist-packages/vmware_exporter-0.7.3-py3.5.egg/vmware_exporter/vmware_exporter.py", line 390, in datastore_labels
    dcs = yield self.datacenter_inventory
  File "/usr/local/lib/python3.5/dist-packages/Twisted-19.2.0rc1-py3.5-linux-x86_64.egg/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/local/lib/python3.5/dist-packages/Twisted-19.2.0rc1-py3.5-linux-x86_64.egg/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/local/lib/python3.5/dist-packages/vmware_exporter-0.7.3-py3.5.egg/vmware_exporter/vmware_exporter.py", line 361, in datacenter_inventory
    content = yield self.content
  File "/usr/local/lib/python3.5/dist-packages/Twisted-19.2.0rc1-py3.5-linux-x86_64.egg/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/local/lib/python3.5/dist-packages/Twisted-19.2.0rc1-py3.5-linux-x86_64.egg/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/local/lib/python3.5/dist-packages/vmware_exporter-0.7.3-py3.5.egg/vmware_exporter/vmware_exporter.py", line 252, in content
    connection = yield self.connection
  File "/usr/local/lib/python3.5/dist-packages/Twisted-19.2.0rc1-py3.5-linux-x86_64.egg/twisted/internet/defer.py", line 1416, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/local/lib/python3.5/dist-packages/Twisted-19.2.0rc1-py3.5-linux-x86_64.egg/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/local/lib/python3.5/dist-packages/vmware_exporter-0.7.3-py3.5.egg/vmware_exporter/vmware_exporter.py", line 240, in connection
    sslContext=context,
  File "/usr/local/lib/python3.5/dist-packages/Twisted-19.2.0rc1-py3.5-linux-x86_64.egg/twisted/python/threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "/usr/local/lib/python3.5/dist-packages/Twisted-19.2.0rc1-py3.5-linux-x86_64.egg/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/usr/local/lib/python3.5/dist-packages/Twisted-19.2.0rc1-py3.5-linux-x86_64.egg/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/local/lib/python3.5/dist-packages/Twisted-19.2.0rc1-py3.5-linux-x86_64.egg/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "/usr/local/lib/python3.5/dist-packages/pyvmomi-6.7.1.2018.12-py3.5.egg/pyVim/connect.py", line 836, in SmartConnect

  File "/usr/local/lib/python3.5/dist-packages/pyvmomi-6.7.1.2018.12-py3.5.egg/pyVim/connect.py", line 718, in __FindSupportedVersion

  File "/usr/local/lib/python3.5/dist-packages/pyvmomi-6.7.1.2018.12-py3.5.egg/pyVim/connect.py", line 638, in __GetServiceVersionDescription

  File "/usr/local/lib/python3.5/dist-packages/pyvmomi-6.7.1.2018.12-py3.5.egg/pyVim/connect.py", line 604, in __GetElementTree

  File "/usr/lib/python3.5/http/client.py", line 1107, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1152, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1103, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/usr/lib/python3.5/http/client.py", line 1261, in connect
    server_hostname=server_hostname)
  File "/usr/lib/python3.5/ssl.py", line 385, in wrap_socket
    _context=self)
  File "/usr/lib/python3.5/ssl.py", line 760, in __init__
    self.do_handshake()
  File "/usr/lib/python3.5/ssl.py", line 996, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib/python3.5/ssl.py", line 641, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:720)
```

**Comment by dannyk81** [comment]
You probably have self-signed certificate on your vCenter, so your config must include `ignore_ssl: False`

**Comment by vdvas** [comment]
Thanks. It works.
